/* ═══════════════════════════════════════════════════════
   card-data.ts — Static card pool & enemy definitions
   Prisma-free, works in Netlify static build
   ═══════════════════════════════════════════════════════ */

export type AbilityType = "攻撃" | "防御" | "効果" | "必殺"

export interface GameCard {
  id: string
  name: string
  imageUrl: string
  flavorText: string
  rarity: "C" | "R" | "SR"
  affiliation: string
  // 4 abilities per card
  attack: number
  defense: number
  effect: string
  effectValue: number
  ultimate: number
  ultimateName: string
}

export interface EnemyPhase {
  triggerHpPercent: number
  message: string
  attackBonus: number
  selfHealPerTurn?: number
}

export interface Enemy {
  id: string
  name: string
  title: string
  maxHp: number
  attackPower: number
  imageUrl: string
  description: string
  difficulty: "NORMAL" | "HARD" | "BOSS" | "FINAL"
  reward: string
  phases: EnemyPhase[]
  specialRule?: string
}

/* ═══════════════════════════════════════════════════════
   64枚のキャラクターカードプール
   Wiki全キャラクターを1枚ずつのカードとして収録
   ═══════════════════════════════════════════════════════ */
const I = (n: string) => `https://raw.githubusercontent.com/gentaron/image/main/${n}`

export const ALL_CARDS: GameCard[] = [
  /* ════════════════════════════════════════
     SR ×14 — 伝説級キャラクター
     ════════════════════════════════════════ */
  {
    id: "char-diana",
    name: "ディアナ",
    imageUrl: I("Diana.png"),
    flavorText: "「初代Wonder Woman。光の裁きが悪を断つ。」",
    rarity: "SR",
    affiliation: "Gigapolis西大陸",
    attack: 7,
    defense: 4,
    effect: "シールド+5",
    effectValue: 5,
    ultimate: 16,
    ultimateName: "光の裁き",
  },
  {
    id: "char-jen",
    name: "ジェン",
    imageUrl: I("Jen.png"),
    flavorText: "「Lv938+。Valoriaの覇者が放つ絶対的一撃。」",
    rarity: "SR",
    affiliation: "Valoria連合圏",
    attack: 8,
    defense: 3,
    effect: "敵に5ダメージ＋HPを2回復",
    effectValue: 5,
    ultimate: 18,
    ultimateName: "覇王の絶対一撃",
  },
  {
    id: "char-celia",
    name: "セリア・ドミニクス",
    imageUrl: I("CeliaDminix.png"),
    flavorText: "「黄金期の女王。一撃に全ての栄光を込めて。」",
    rarity: "SR",
    affiliation: "Selinopolis",
    attack: 7,
    defense: 5,
    effect: "HPを5回復",
    effectValue: 5,
    ultimate: 17,
    ultimateName: "黄金の皇劍",
  },
  {
    id: "char-alpha-kane",
    name: "アルファ・ケイン",
    imageUrl: I("AlphaKane.png"),
    flavorText: "「シャドウ・リベリオンの魂。量子ハックで世界を変えた。」",
    rarity: "SR",
    affiliation: "シャドウ・リベリオン",
    attack: 8,
    defense: 3,
    effect: "敵の攻撃力低下",
    effectValue: 3,
    ultimate: 17,
    ultimateName: "量子ハック・カオス",
  },
  {
    id: "char-layla",
    name: "レイラ・ヴィレル・ノヴァ",
    imageUrl: I("LaylaVirelNova.png"),
    flavorText: "「Pink Voltageの最終演舞。プラズマが全てを焼き尽くす。」",
    rarity: "SR",
    affiliation: "AURALIS第二世代",
    attack: 9,
    defense: 3,
    effect: "敵に6ダメージ",
    effectValue: 6,
    ultimate: 18,
    ultimateName: "プラズマ・フィナーレ",
  },
  {
    id: "char-kate-claudia",
    name: "ケイト・クラウディア",
    imageUrl: I("KateClaudia.png"),
    flavorText: "「AURALIS創設者。共鳴の極致が敵を滅ぼす。」",
    rarity: "SR",
    affiliation: "AURALIS第一世代",
    attack: 6,
    defense: 5,
    effect: "HPを5回復＋シールド+3",
    effectValue: 5,
    ultimate: 15,
    ultimateName: "共鳴の極致",
  },
  {
    id: "char-lily-steiner",
    name: "リリー・スタイナー",
    imageUrl: I("LillieSteiner.png"),
    flavorText: "「最終章の歌。旋律が刃となり敵を貫く。」",
    rarity: "SR",
    affiliation: "AURALIS第一世代",
    attack: 6,
    defense: 5,
    effect: "HPを4回復",
    effectValue: 4,
    ultimate: 15,
    ultimateName: "終章の鎮魂歌",
  },
  {
    id: "char-mina",
    name: "ミナ・エウレカ・エルンスト",
    imageUrl: I("MinaEurekaErnst.png"),
    flavorText: "「超次元弾発射。次元を超えた一撃が標的を消滅させる。」",
    rarity: "SR",
    affiliation: "AURALIS第二世代",
    attack: 8,
    defense: 3,
    effect: "次元ピラミッド展開",
    effectValue: 5,
    ultimate: 18,
    ultimateName: "超次元弾",
  },
  {
    id: "char-iris",
    name: "アイリス",
    imageUrl: I("Iris.png"),
    flavorText: "「トリニティの指導者。次元の刃で運命を断ち切る。」",
    rarity: "SR",
    affiliation: "トリニティ・アライアンス",
    attack: 7,
    defense: 4,
    effect: "敵に5ダメージ＋シールド+3",
    effectValue: 5,
    ultimate: 17,
    ultimateName: "次元斬り",
  },
  {
    id: "char-sylvia-crow",
    name: "シルヴィア・クロウ",
    imageUrl: I("SylviaCrow.png"),
    flavorText: "「Eros-7のエスパー。念動力の嵐が敵を圧倒する。」",
    rarity: "SR",
    affiliation: "Eros-7",
    attack: 7,
    defense: 4,
    effect: "敵に5ダメージ",
    effectValue: 5,
    ultimate: 16,
    ultimateName: "念動嵐撃",
  },
  {
    id: "char-ayaka-rin",
    name: "アヤカ・リン",
    imageUrl: I("AyakaRin.png"),
    flavorText: "「Lv.842搾精ハンター。カウパー波が全てを狩る。」",
    rarity: "SR",
    affiliation: "Eros-7",
    attack: 8,
    defense: 3,
    effect: "敵の攻撃力低下",
    effectValue: 3,
    ultimate: 17,
    ultimateName: "カウパー波・インフィニティ",
  },
  {
    id: "char-fariel",
    name: "ファリエル",
    imageUrl: I("Fariel.png"),
    flavorText: "「ボグダス最強の戦力。旋風の一撃が山を断つ。」",
    rarity: "SR",
    affiliation: "ボグダス・ジャベリン",
    attack: 7,
    defense: 5,
    effect: "シールド+5",
    effectValue: 5,
    ultimate: 16,
    ultimateName: "旋風断山撃",
  },
  {
    id: "char-ninigis",
    name: "ニニギス・カラス",
    imageUrl: I("NinigisKaras.png"),
    flavorText: "「ボグダスの切り札。カラスの如き速さで標的を屠る。」",
    rarity: "SR",
    affiliation: "ボグダス・ジャベリン",
    attack: 8,
    defense: 3,
    effect: "敵に5ダメージ",
    effectValue: 5,
    ultimate: 16,
    ultimateName: "鴉魔一閃",
  },
  {
    id: "char-slime-woman",
    name: "スライム・ウーマン",
    imageUrl: I("SlimeWoman.png"),
    flavorText: "「高次元からの干渉。スライムの波が全てを飲み込む。」",
    rarity: "SR",
    affiliation: "高次元存在",
    attack: 6,
    defense: 6,
    effect: "敵に4ダメージ＋HPを4回復",
    effectValue: 4,
    ultimate: 15,
    ultimateName: "高次元スライム・ウェーブ",
  },

  /* ════════════════════════════════════════
     R ×32 — 中堅キャラクター
     ════════════════════════════════════════ */
  {
    id: "char-erios-wald",
    name: "エリオス・ウォルド",
    imageUrl: I("EriosWald.png"),
    flavorText: "「テリアン反乱軍の旗手。自由のための剣。」",
    rarity: "R",
    affiliation: "テリアン反乱軍",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "自由の反乱剣",
  },
  {
    id: "char-gentaro",
    name: "弦太郎",
    imageUrl: I("Gentaro.png"),
    flavorText: "「Lv569。AURALISを支える不屈の戦士。」",
    rarity: "R",
    affiliation: "AURALIS関連",
    attack: 5,
    defense: 3,
    effect: "シールド+3",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "不屈の居合斬り",
  },
  {
    id: "char-sebastian",
    name: "セバスチャン・ヴァレリウス",
    imageUrl: I("SebastianValerius.png"),
    flavorText: "「ボグダス・ジャベリンの指揮官。正確無比な一射。」",
    rarity: "R",
    affiliation: "ボグダス・ジャベリン",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ",
    effectValue: 3,
    ultimate: 11,
    ultimateName: "精密狙撃弾",
  },
  {
    id: "char-gareth",
    name: "ガレス",
    imageUrl: I("Gareth.png"),
    flavorText: "「ボグダスの猛将。正面突破を信条とする。」",
    rarity: "R",
    affiliation: "ボグダス・ジャベリン",
    attack: 5,
    defense: 3,
    effect: "シールド+3",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "正面突破・粉砕",
  },
  {
    id: "char-leon",
    name: "レオン",
    imageUrl: I("Leon.png"),
    flavorText: "「シルバー・ヴェノム幹部。冷酷な一撃。」",
    rarity: "R",
    affiliation: "シルバー・ヴェノム",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ＋HPを2回復",
    effectValue: 3,
    ultimate: 11,
    ultimateName: "毒牙の冷刃",
  },
  {
    id: "char-izumi",
    name: "イズミ",
    imageUrl: I("Izumi.png"),
    flavorText: "「アルファ・ヴェノムのリーダー。両性具有の戦闘力。」",
    rarity: "R",
    affiliation: "アルファ・ヴェノム",
    attack: 6,
    defense: 2,
    effect: "敵に4ダメージ",
    effectValue: 4,
    ultimate: 12,
    ultimateName: "双極のヴェノム・ストライク",
  },
  {
    id: "char-goldilocks",
    name: "ゴルディロックス",
    imageUrl: I("Goldilocks.png"),
    flavorText: "「アルファ・ヴェノムの破壊担当。」",
    rarity: "R",
    affiliation: "アルファ・ヴェノム",
    attack: 6,
    defense: 2,
    effect: "敵に3ダメージ",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "暴走破壊衝動",
  },
  {
    id: "char-lastman",
    name: "ラストマン",
    imageUrl: I("Lastman.png"),
    flavorText: "「シルバー・ヴェノム残党。最後の力を振り絞る一撃。」",
    rarity: "R",
    affiliation: "シルバー・ヴェノム残党",
    attack: 6,
    defense: 2,
    effect: "HPを3回復",
    effectValue: 3,
    ultimate: 11,
    ultimateName: "ラスト・リベンジャー",
  },
  {
    id: "char-temirtaron",
    name: "テミルタロン",
    imageUrl: I("Temirtaron.png"),
    flavorText: "「サイケデリック・コスモロジーの具現化。」",
    rarity: "R",
    affiliation: "テンプル・オブ・ホライゾン",
    attack: 5,
    defense: 3,
    effect: "敵の攻撃力低下",
    effectValue: 2,
    ultimate: 10,
    ultimateName: "幻覚波動・コスモロジー",
  },
  {
    id: "char-lilith-vane",
    name: "リリス・ヴェイン",
    imageUrl: I("LilithVane.png"),
    flavorText: "「Eros-7の女性リーダー。搾取技術の制圧者。」",
    rarity: "R",
    affiliation: "Eros-7",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ＋シールド+2",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "搾取の支配者・インペリアル",
  },
  {
    id: "char-garo",
    name: "ガロ",
    imageUrl: I("Garo.png"),
    flavorText: "「シャドウ・ユニオンの男性リーダー。反逆の剣。」",
    rarity: "R",
    affiliation: "シャドウ・ユニオン",
    attack: 6,
    defense: 2,
    effect: "敵に3ダメージ",
    effectValue: 3,
    ultimate: 11,
    ultimateName: "反逆者の漆黒剣",
  },
  {
    id: "char-karla-velm",
    name: "カーラ・ヴェルム",
    imageUrl: I("KarlaVelm.png"),
    flavorText: "「スクイーズ・アビスの建設者。搾取プラズマ弾。」",
    rarity: "R",
    affiliation: "Eros-7",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "搾取プラズマカノン",
  },
  {
    id: "char-aria-sol",
    name: "アリア・ソル",
    imageUrl: I("AriaSol.png"),
    flavorText: "「惑星連邦構想の推進者。次元の光で敵を射抜く。」",
    rarity: "R",
    affiliation: "惑星連邦構想派",
    attack: 5,
    defense: 3,
    effect: "HPを3回復",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "次元光線・フェデレーション",
  },
  {
    id: "char-tina-gue",
    name: "ティナ/グエ",
    imageUrl: I("TinaGue.png"),
    flavorText: "「地下街の支配者。深い闇が仲間を守る。」",
    rarity: "R",
    affiliation: "地下街",
    attack: 4,
    defense: 4,
    effect: "シールド+4",
    effectValue: 4,
    ultimate: 9,
    ultimateName: "地下街の深淵結界",
  },
  {
    id: "char-kate-patton",
    name: "ケイト・パットン",
    imageUrl: I("KatePatton.png"),
    flavorText: "「AURALIS第二世代。癒やしの共鳴で隊を守る。」",
    rarity: "R",
    affiliation: "AURALIS第二世代",
    attack: 4,
    defense: 4,
    effect: "HPを4回復",
    effectValue: 4,
    ultimate: 9,
    ultimateName: "共鳴の癒やし・リジェネ",
  },
  {
    id: "char-castina",
    name: "カスチーナ・テンペスト",
    imageUrl: I("CastinaTempest.png"),
    flavorText: "「クロセヴィアの守護者。嵐の如き防壁。」",
    rarity: "R",
    affiliation: "クロセヴィア",
    attack: 4,
    defense: 5,
    effect: "シールド+4",
    effectValue: 4,
    ultimate: 9,
    ultimateName: "嵐の絶対防壁",
  },
  {
    id: "char-elena",
    name: "エレナ",
    imageUrl: I("Elena.png"),
    flavorText: "「ヴァーミリオン元機関長。経験に裏打ちされた結界。」",
    rarity: "R",
    affiliation: "ヴァーミリオン諜報機関",
    attack: 4,
    defense: 5,
    effect: "シールド+4",
    effectValue: 4,
    ultimate: 9,
    ultimateName: "経験の鉄壁結界",
  },
  {
    id: "char-aina",
    name: "アイナ・フォン・リースフェルト",
    imageUrl: I("AinaVonRiesfeld.png"),
    flavorText: "「ボグダス歴戦の防衛兵。堅牢な盾。」",
    rarity: "R",
    affiliation: "ボグダス・ジャベリン",
    attack: 3,
    defense: 5,
    effect: "シールド+4",
    effectValue: 4,
    ultimate: 8,
    ultimateName: "リースフェルト大盾陣",
  },
  {
    id: "char-casteria",
    name: "カステリア・グレンヴェルト",
    imageUrl: I("CasteriaGrenvelt.png"),
    flavorText: "「Gigapolis西大陸の防衛者。」",
    rarity: "R",
    affiliation: "Gigapolis西大陸",
    attack: 4,
    defense: 4,
    effect: "HPを3回復＋シールド+2",
    effectValue: 3,
    ultimate: 9,
    ultimateName: "西大陸防衛陣",
  },
  {
    id: "char-timur-shah",
    name: "ティムール・シャー",
    imageUrl: I("TimurShah.png"),
    flavorText: "「移民団のリーダー。10次元理論の防壁。」",
    rarity: "R",
    affiliation: "移民団",
    attack: 4,
    defense: 4,
    effect: "敵の攻撃力低下",
    effectValue: 2,
    ultimate: 9,
    ultimateName: "10次元理論の防壁",
  },
  {
    id: "char-zena",
    name: "ゼナ",
    imageUrl: I("Zena.png"),
    flavorText: "「Eros-7の女性商人。商売の利益で軍資金を供給。」",
    rarity: "R",
    affiliation: "Eros-7",
    attack: 4,
    defense: 4,
    effect: "HPを3回復",
    effectValue: 3,
    ultimate: 9,
    ultimateName: "利潤の補給戦略",
  },
  {
    id: "char-el-forhaus",
    name: "エル・フォルハウス",
    imageUrl: I("ElForhaus.png"),
    flavorText: "「新時代のルーキー。経済改革の先駆者。」",
    rarity: "R",
    affiliation: "コーポラタムパブリカ",
    attack: 4,
    defense: 3,
    effect: "HPを3回復＋シールド+2",
    effectValue: 3,
    ultimate: 9,
    ultimateName: "経済改革ショックウェーブ",
  },
  {
    id: "char-lillie-ardent",
    name: "リリー・アーデント",
    imageUrl: I("LillieArdent.png"),
    flavorText: "「AURALIS第二世代。献身的な癒やしの手。」",
    rarity: "R",
    affiliation: "AURALIS第二世代",
    attack: 3,
    defense: 4,
    effect: "HPを4回復",
    effectValue: 4,
    ultimate: 9,
    ultimateName: "献身の聖なる手",
  },
  {
    id: "char-ninny",
    name: "ニニー・オッフェンバッハ",
    imageUrl: I("NinnyOffenbach.png"),
    flavorText: "「クローン継承のハッカー。計算された一撃。」",
    rarity: "R",
    affiliation: "AURALIS第二世代",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ＋HPを2回復",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "クローン・ハック・オーバーロード",
  },
  {
    id: "char-fiona",
    name: "フィオナ",
    imageUrl: I("Fiona.png"),
    flavorText: "「ブルーローズのCOO。計算高い策略。」",
    rarity: "R",
    affiliation: "ブルーローズ",
    attack: 4,
    defense: 3,
    effect: "敵に3ダメージ＋シールド+2",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "策略の青薔薇一撃",
  },
  {
    id: "char-marina",
    name: "マリーナ・ボビン",
    imageUrl: I("MarinaBobbin.png"),
    flavorText: "「ミエルテンガ総統。国を癒やす手。」",
    rarity: "R",
    affiliation: "ミエルテンガ",
    attack: 3,
    defense: 4,
    effect: "HPを4回復",
    effectValue: 4,
    ultimate: 9,
    ultimateName: "総統の癒やしの手",
  },
  {
    id: "char-levilia",
    name: "レヴィリア・サーペンティナ",
    imageUrl: I("LeviliaSerpentina.png"),
    flavorText: "「シルバー・ヴェノムの毒蛇。見えない毒牙。」",
    rarity: "R",
    affiliation: "シルバー・ヴェノム",
    attack: 5,
    defense: 3,
    effect: "敵に4ダメージ",
    effectValue: 4,
    ultimate: 11,
    ultimateName: "毒蛇の幻影牙",
  },
  {
    id: "char-willie",
    name: "ウィリー",
    imageUrl: I("Willie.png"),
    flavorText: "「アイリスのパートナー。常に側で支える。」",
    rarity: "R",
    affiliation: "ヴァーミリオン",
    attack: 4,
    defense: 4,
    effect: "HPを3回復＋シールド+2",
    effectValue: 3,
    ultimate: 9,
    ultimateName: "絆の共鳴シールド",
  },
  {
    id: "char-white-noise",
    name: "ホワイトノイズ",
    imageUrl: I("WhiteNoise.png"),
    flavorText: "「ボグダスの通信兵。情報の流れが勝利を導く。」",
    rarity: "R",
    affiliation: "ボグダス・ジャベリン",
    attack: 4,
    defense: 3,
    effect: "敵の攻撃力低下",
    effectValue: 2,
    ultimate: 9,
    ultimateName: "ノイズ・ジャミング・ウェーブ",
  },
  {
    id: "char-wadrina",
    name: "ワドリナ",
    imageUrl: I("Wadrina.png"),
    flavorText: "「ボグダスの後方要員。」",
    rarity: "R",
    affiliation: "ボグダス・ジャベリン",
    attack: 4,
    defense: 4,
    effect: "シールド+3",
    effectValue: 3,
    ultimate: 8,
    ultimateName: "後方支援プロトコル",
  },
  {
    id: "char-azazel",
    name: "アザゼル・ヘクトパス",
    imageUrl: I("AzazelHectopus.png"),
    flavorText: "「ヴァーミリオンの異形戦力。触手の一撃。」",
    rarity: "R",
    affiliation: "ヴァーミリオン",
    attack: 5,
    defense: 3,
    effect: "敵に4ダメージ",
    effectValue: 4,
    ultimate: 11,
    ultimateName: "触手の異形捕縛",
  },
  {
    id: "char-jun",
    name: "ジュン",
    imageUrl: I("Jun.png"),
    flavorText: "「スライム・ウーマンと関わりを持つ者。不可解な力。」",
    rarity: "R",
    affiliation: "不詳",
    attack: 4,
    defense: 4,
    effect: "HPを3回復＋敵に2ダメージ",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "不可解次元干渉波",
  },

  /* ── 宇宙文明圏カード ── */
  {
    id: "char-alzen-carlin",
    name: "アルゼン・カーリーン",
    imageUrl: "/logo.svg",
    flavorText: "「グランベル大統領。宇宙最大の経済帝国を率いる。」",
    rarity: "R",
    affiliation: "グランベル",
    attack: 5,
    defense: 5,
    effect: "HPを4回復",
    effectValue: 4,
    ultimate: 11,
    ultimateName: "経済帝国の絶対支配",
  },
  {
    id: "char-greymond-houser",
    name: "グレイモンド・ハウザー",
    imageUrl: "/logo.svg",
    flavorText: "「ティエリア総帥。宇宙最強の軍事力を指揮する。」",
    rarity: "R",
    affiliation: "ティエリア",
    attack: 6,
    defense: 3,
    effect: "敵に4ダメージ",
    effectValue: 4,
    ultimate: 11,
    ultimateName: "軍事力の絶対防衛",
  },
  {
    id: "char-liana-solis",
    name: "女王リアナ・ソリス",
    imageUrl: "/logo.svg",
    flavorText: "「エレシオン女王。医療と再生の力で宇宙を癒す。」",
    rarity: "R",
    affiliation: "エレシオン",
    attack: 4,
    defense: 5,
    effect: "HPを4回復＋シールド+2",
    effectValue: 4,
    ultimate: 10,
    ultimateName: "再生の女王の慈悲",
  },
  {
    id: "char-madris-kernel",
    name: "マドリス・カーネル",
    imageUrl: "/logo.svg",
    flavorText: "「ファルージャ代表。文化の力で争いを鎮める。」",
    rarity: "R",
    affiliation: "ファルージャ",
    attack: 3,
    defense: 4,
    effect: "敵の攻撃力低下",
    effectValue: 2,
    ultimate: 9,
    ultimateName: "文化調停の外交術",
  },
  {
    id: "char-nathan-corind",
    name: "ネイサン・コリンド",
    imageUrl: "/logo.svg",
    flavorText: "「ディオクレニス宰相。科学で宇宙の未来を拓く。」",
    rarity: "R",
    affiliation: "ディオクレニス",
    attack: 4,
    defense: 4,
    effect: "シールド+4",
    effectValue: 4,
    ultimate: 10,
    ultimateName: "科学の結晶シールド",
  },
  {
    id: "char-ronan-arthur",
    name: "ロナン・アーサ",
    imageUrl: "/logo.svg",
    flavorText: "「アポロンの騎士王。ケンタウロスレーザーの英雄。」",
    rarity: "SR",
    affiliation: "アポロン文明圏",
    attack: 7,
    defense: 4,
    effect: "敵に5ダメージ",
    effectValue: 5,
    ultimate: 17,
    ultimateName: "ケンタウロスレーザー",
  },

  /* ════════════════════════════════════════
     C ×18 — 一般キャラクター
     ════════════════════════════════════════ */
  {
    id: "char-vivietta",
    name: "ヴィヴィエッタ",
    imageUrl: I("Vivietta.png"),
    flavorText: "「四楓院ヴィヴィエッタ。救出された後も力を尽くす。」",
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    attack: 3,
    defense: 3,
    effect: "HPを2回復",
    effectValue: 2,
    ultimate: 7,
    ultimateName: "四楓院の慈悲",
  },
  {
    id: "char-sheron",
    name: "シェロン・ジェラス",
    imageUrl: I("SheronJeras.png"),
    flavorText: "「ボグダスの後方支援兵。」",
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    attack: 3,
    defense: 2,
    effect: "シールド+2",
    effectValue: 2,
    ultimate: 6,
    ultimateName: "支援兵の陣太鼓",
  },
  {
    id: "char-ilmise",
    name: "イルミーゼ",
    imageUrl: I("Ilmise.png"),
    flavorText: "「ボグダスの衛生兵。負傷者を守る。」",
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    attack: 2,
    defense: 3,
    effect: "HPを3回復",
    effectValue: 3,
    ultimate: 6,
    ultimateName: "衛生兵の救急処置",
  },
  {
    id: "char-piatrino",
    name: "ピアトリーノ",
    imageUrl: I("Piatrino.png"),
    flavorText: "「ブルーローズの防衛兵。」",
    rarity: "C",
    affiliation: "ブルーローズ",
    attack: 3,
    defense: 3,
    effect: "シールド+3",
    effectValue: 3,
    ultimate: 7,
    ultimateName: "青薔薇の守護陣",
  },
  {
    id: "char-myu",
    name: "ミュー",
    imageUrl: I("Myu.png"),
    flavorText: "「Gigapolisの守護存在。」",
    rarity: "C",
    affiliation: "Gigapolis",
    attack: 3,
    defense: 3,
    effect: "HPを2回復＋シールド+1",
    effectValue: 2,
    ultimate: 7,
    ultimateName: "守護ミュー・バリア",
  },
  {
    id: "char-gil",
    name: "ギル",
    imageUrl: I("Gil.png"),
    flavorText: "「アルファ・ヴェノムの盾役。」",
    rarity: "C",
    affiliation: "アルファ・ヴェノム",
    attack: 2,
    defense: 3,
    effect: "シールド+3",
    effectValue: 3,
    ultimate: 6,
    ultimateName: "ヴェノム・ガード",
  },
  {
    id: "char-aj",
    name: "AJ",
    imageUrl: I("AJ.png"),
    flavorText: "「アルファ・ヴェノムの情報屋。」",
    rarity: "C",
    affiliation: "アルファ・ヴェノム",
    attack: 3,
    defense: 2,
    effect: "敵に2ダメージ",
    effectValue: 2,
    ultimate: 6,
    ultimateName: "情報ハック・クラック",
  },
  {
    id: "char-sitra",
    name: "シトラ・セレス",
    imageUrl: I("SitraCeles.png"),
    flavorText: "「Gigapolisの謎めいた存在。」",
    rarity: "C",
    affiliation: "Gigapolis",
    attack: 3,
    defense: 2,
    effect: "敵に2ダメージ",
    effectValue: 2,
    ultimate: 7,
    ultimateName: "セレスの神秘光",
  },
  {
    id: "char-master-venom",
    name: "マスター・ヴェノム",
    imageUrl: I("MasterVenom.png"),
    flavorText: "「シルバー・ヴェノムの創設者。毒の知識。」",
    rarity: "C",
    affiliation: "シルバー・ヴェノム",
    attack: 3,
    defense: 2,
    effect: "敵に3ダメージ",
    effectValue: 3,
    ultimate: 7,
    ultimateName: "マスターヴェノム・エキス",
  },
  {
    id: "char-gabby",
    name: "フレデリック・ギャビー",
    imageUrl: I("FredericGabby.png"),
    flavorText: "「ボグダスの歴戦の兵。着実な一撃。」",
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    attack: 3,
    defense: 2,
    effect: "敵に2ダメージ",
    effectValue: 2,
    ultimate: 6,
    ultimateName: "歴戦のベテラン斬り",
  },
  {
    id: "char-miyushari",
    name: "ミユシャリ",
    imageUrl: I("Miyushari.png"),
    flavorText: "「ボグダス・ジャベリンの歩兵部隊。」",
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    attack: 3,
    defense: 2,
    effect: "シールド+2",
    effectValue: 2,
    ultimate: 6,
    ultimateName: "ジャベリン突撃陣形",
  },
  {
    id: "char-yeshibato",
    name: "イェシバトー",
    imageUrl: I("Yeshibato.png"),
    flavorText: "「ボグダス・ジャベリンの斥候兵。」",
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    attack: 3,
    defense: 2,
    effect: "敵に2ダメージ",
    effectValue: 2,
    ultimate: 6,
    ultimateName: "斥候の隠密射撃",
  },
  {
    id: "char-yonik",
    name: "ヨニック",
    imageUrl: I("Yonik.png"),
    flavorText: "「ブルーローズの戦士。堅実な剣術。」",
    rarity: "C",
    affiliation: "ブルーローズ",
    attack: 3,
    defense: 3,
    effect: "シールド+2",
    effectValue: 2,
    ultimate: 7,
    ultimateName: "ブルーローズの剣舞",
  },
  {
    id: "char-bobristy",
    name: "ボブリスティ",
    imageUrl: I("Bobristy.png"),
    flavorText: "「アルファ・ヴェノムの突撃兵。」",
    rarity: "C",
    affiliation: "アルファ・ヴェノム",
    attack: 4,
    defense: 1,
    effect: "敵に2ダメージ",
    effectValue: 2,
    ultimate: 6,
    ultimateName: "ヴェノム・ラッシュ",
  },
  {
    id: "char-aike-lopez",
    name: "アイク・ロペス",
    imageUrl: I("AikeLopez.png"),
    flavorText: "「SSレンジ / V7の戦闘要員。」",
    rarity: "C",
    affiliation: "SSレンジ",
    attack: 3,
    defense: 2,
    effect: "敵に2ダメージ",
    effectValue: 2,
    ultimate: 7,
    ultimateName: "SSレンジ・アサルト",
  },
  {
    id: "char-katarina",
    name: "カタリナ",
    imageUrl: I("Katarina.png"),
    flavorText: "「アルファ・ヴェノムの暗殺者。速い一撃。」",
    rarity: "C",
    affiliation: "アルファ・ヴェノム",
    attack: 4,
    defense: 1,
    effect: "敵に3ダメージ",
    effectValue: 3,
    ultimate: 7,
    ultimateName: "暗殺者の疾風ナイフ",
  },
  {
    id: "char-rafael-drake",
    name: "ラファエル・ドレイク",
    imageUrl: "/logo.svg",
    flavorText: "「トロン・コーポレーションCEO。ZAMLTの宇宙軍事力を統括。旗艦カリバーンを指揮。」",
    rarity: "R",
    affiliation: "ZAMLT",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "重工業の鉄槌",
  },
  {
    id: "char-carlos-vandam",
    name: "カルロス・ヴァンダム",
    imageUrl: "/logo.svg",
    flavorText: "「マモン・コーポレーションCEO。ZAMLTの経済的基盤を構築。慎重な戦略家。」",
    rarity: "R",
    affiliation: "ZAMLT",
    attack: 4,
    defense: 4,
    effect: "シールド+3",
    effectValue: 3,
    ultimate: 9,
    ultimateName: "金融の支配者",
  },
  {
    id: "char-arthur-grimm",
    name: "アーサー・グリム",
    imageUrl: "/logo.svg",
    flavorText: "「ゼブラ・コーポレーションCEO。次元技術を独占するZAMLT最危険の企業。」",
    rarity: "R",
    affiliation: "ZAMLT",
    attack: 3,
    defense: 5,
    effect: "敵の攻撃力低下",
    effectValue: 3,
    ultimate: 9,
    ultimateName: "情報操作の黒幕",
  },
  {
    id: "char-elizabeth-lindberg",
    name: "エリザベス・リンドバーグ",
    imageUrl: "/logo.svg",
    flavorText: "「ルレンツ・コーポレーションCEO。次元の塔とカタリスト・コア建造を主導。」",
    rarity: "R",
    affiliation: "ZAMLT",
    attack: 4,
    defense: 4,
    effect: "シールド+3",
    effectValue: 3,
    ultimate: 10,
    ultimateName: "Registryの絶対管理",
  },
  {
    id: "char-iris-nova",
    name: "アイリス・ノヴァ",
    imageUrl: "/logo.svg",
    flavorText: "「アロエオイル・コーポレーションCEO。次元エネルギー兵器開発の専門家。」",
    rarity: "R",
    affiliation: "ZAMLT",
    attack: 4,
    defense: 3,
    effect: "敵に3ダメージ",
    effectValue: 3,
    ultimate: 9,
    ultimateName: "インフラ掌握の一手",
  },
  {
    id: "char-elliot-strass",
    name: "エリオット・シュトラス",
    imageUrl: "/logo.svg",
    flavorText: "「ZAMLT総帥。経済支配の絶対権力。」",
    rarity: "R",
    affiliation: "ZAMLT",
    attack: 5,
    defense: 4,
    effect: "シールド+4",
    effectValue: 4,
    ultimate: 11,
    ultimateName: "経済支配の絶対命令",
  },
  {
    id: "char-reid-kakizaki",
    name: "レイド・カキザキ",
    imageUrl: I("ReidKakizaki.png"),
    flavorText: "「アイアン・シンジケートの戦士。」",
    rarity: "C",
    affiliation: "アイアン・シンジケート",
    attack: 3,
    defense: 2,
    effect: "シールド+2",
    effectValue: 2,
    ultimate: 6,
    ultimateName: "シンジケート・アイアンパンチ",
  },
  {
    id: "char-mikael-gabrieli",
    name: "ミカエル・ガブリエリ",
    imageUrl: I("MikaelGabrieli.png"),
    flavorText: "「ファールージャ社の警備員。」",
    rarity: "C",
    affiliation: "ファールージャ社",
    attack: 3,
    defense: 3,
    effect: "シールド+2",
    effectValue: 2,
    ultimate: 6,
    ultimateName: "警備員の警棒スマッシュ",
  },
]

/* ═══════════════════════════════════════════════════════
   10体のエネミー
   ═══════════════════════════════════════════════════════ */
export const ENEMIES: Enemy[] = [
  /* ── NORMAL ×4 ── */
  {
    id: "stardust-dragon",
    name: "スターダスト・ドラゴン",
    title: "星屑の守護者",
    maxHp: 28,
    attackPower: 4,
    imageUrl: "/logo.svg",
    description: "E16連星系の深部に棲む古代竜。星屑を纏い、その息吹は小惑星を灰に変える。",
    difficulty: "NORMAL",
    reward: "星屑の鱗を入手",
    phases: [{ triggerHpPercent: 50, message: "翼を広げ炎を吐く！", attackBonus: 2 }],
  },
  {
    id: "phantom-walker",
    name: "霊体ウォーカー",
    title: "彷徨える亡者",
    maxHp: 22,
    attackPower: 3,
    imageUrl: "/logo.svg",
    description: "次元境界を彷徨う幽霊のような存在。実体を持たず、傷ついても自ら再生する。",
    difficulty: "NORMAL",
    reward: "霊体の核を入手",
    phases: [
      {
        triggerHpPercent: 40,
        message: "霊体が揺らめく…",
        attackBonus: 1,
        selfHealPerTurn: 2,
      },
    ],
    specialRule: "HP40%以下から毎ターン2回復する",
  },
  {
    id: "iron-golem",
    name: "鉄塊ゴーレム",
    title: "廃工場の番人",
    maxHp: 35,
    attackPower: 5,
    imageUrl: "/logo.svg",
    description: "放棄された軍事工場で自動稼働する巨大な機械番人。装甲はどんな攻撃も弾く。",
    difficulty: "NORMAL",
    reward: "精製鉄塊を入手",
    phases: [{ triggerHpPercent: 60, message: "装甲が赤く焼ける！", attackBonus: 3 }],
    specialRule: "防御能力の効果が半減する（シールド値÷2）",
  },
  {
    id: "venom-hydra",
    name: "毒沼ヒュドラ",
    title: "沼地の多頭竜",
    maxHp: 30,
    attackPower: 3,
    imageUrl: "/logo.svg",
    description: "瘴気に満ちた沼に潜む多頭の竜。首を斬っても再生し、毒で敵を蝕む。",
    difficulty: "NORMAL",
    reward: "毒腺エキスを入手",
    phases: [
      { triggerHpPercent: 66, message: "首が1本再生した！", attackBonus: 1 },
      { triggerHpPercent: 33, message: "さらに首が増える！", attackBonus: 2 },
    ],
    specialRule: "毎ターン終了時プレイヤーに1毒ダメージ",
  },
  /* ── HARD ×3 ── */
  {
    id: "frost-guardian",
    name: "氷獄の守護者",
    title: "絶対零度の鎧",
    maxHp: 42,
    attackPower: 5,
    imageUrl: "/logo.svg",
    description: "永久凍土の最深部で眠る氷の巨人。その鎧は絶対零度の冷気で硬化している。",
    difficulty: "HARD",
    reward: "永久凍土の結晶を入手",
    phases: [
      {
        triggerHpPercent: 50,
        message: "氷の鎧が砕け…本体が現れた！",
        attackBonus: 4,
      },
    ],
    specialRule: "バトル開始時味方全体に1ダメージ。防御能力の効果が半減する（シールド値÷2）",
  },
  {
    id: "flame-spirit",
    name: "炎の精霊王",
    title: "業火の化身",
    maxHp: 36,
    attackPower: 7,
    imageUrl: "/logo.svg",
    description: "太古の火山に宿る炎の精霊。その熱量は防壁すら溶かし、近づく者を灰に変える。",
    difficulty: "HARD",
    reward: "業火の核石を入手",
    phases: [
      { triggerHpPercent: 70, message: "炎が激しくなる！", attackBonus: 2 },
      { triggerHpPercent: 30, message: "核爆発！", attackBonus: 4 },
    ],
    specialRule: "防御能力を使うたびに自分が1ダメージ",
  },
  {
    id: "void-spider",
    name: "深淵の大蜘蛛",
    title: "虚無の糸使い",
    maxHp: 45,
    attackPower: 4,
    imageUrl: "/logo.svg",
    description: "次元の裂け目に巣食う巨大蜘蛛。透明な糸で獲物を縛り上げ、動きを封じる。",
    difficulty: "HARD",
    reward: "次元の糸を入手",
    phases: [{ triggerHpPercent: 45, message: "捕縛糸を放つ！", attackBonus: 2 }],
    specialRule: "偶数ターンはプレイヤーが防御能力を使用できない",
  },
  /* ── BOSS ×2 ── */
  {
    id: "fallen-angel",
    name: "堕落した天使",
    title: "翼なき裁判者",
    maxHp: 65,
    attackPower: 8,
    imageUrl: "/logo.svg",
    description:
      "かつてAURALISの守護天使だったが、次元崩壊に巻き込まれ堕天した。3段階の怒りを持つ。",
    difficulty: "BOSS",
    reward: "堕天の羽根を入手",
    phases: [
      {
        triggerHpPercent: 66,
        message: "神の怒りを解放する！",
        attackBonus: 2,
      },
      {
        triggerHpPercent: 33,
        message: "最後の審判…！",
        attackBonus: 4,
        selfHealPerTurn: 3,
      },
    ],
    specialRule: "HP33%以下から毎ターン3回復＋攻撃力+4",
  },
  {
    id: "void-reaper",
    name: "ヴォイドリーパー",
    title: "時空の刈り手",
    maxHp: 75,
    attackPower: 9,
    imageUrl: "/logo.svg",
    description: "虚無から現れ、存在そのものを刈り取る死神。3フェーズの力で時空を歪める。",
    difficulty: "BOSS",
    reward: "虚無の鎌を入手",
    phases: [
      { triggerHpPercent: 75, message: "時空が歪む…", attackBonus: 1 },
      { triggerHpPercent: 50, message: "次元切断！", attackBonus: 3 },
      { triggerHpPercent: 25, message: "存在が消えていく…", attackBonus: 5 },
    ],
    specialRule: "フェーズ移行時プレイヤーに3ダメージ",
  },
  /* ── FINAL ×1 ── */
  {
    id: "void-king",
    name: "虚無の王",
    title: "終焉の支配者",
    maxHp: 100,
    attackPower: 11,
    imageUrl: "/logo.svg",
    description:
      "全ての虚無の根源。宇宙の終わりを体現する存在。必殺能力のみが最終フェーズを突破できる。",
    difficulty: "FINAL",
    reward: "虚無の王冠を入手。全クリア達成！",
    phases: [
      { triggerHpPercent: 80, message: "宇宙が震える…", attackBonus: 2 },
      { triggerHpPercent: 55, message: "虚無の爆発！", attackBonus: 4 },
      {
        triggerHpPercent: 30,
        message: "終焉の意志…！",
        attackBonus: 6,
        selfHealPerTurn: 5,
      },
    ],
    specialRule: "HP30%以下から毎ターン5回復。必殺能力のみが最終フェーズを突破できる",
  },
]
