export const PLATFORMS = [
  {
    name: "auralis-eternal-light.lovable.app",
    desc: "公式ポータル",
    type: "PORTAL",
    color: "text-nebula-purple border-nebula-purple/30",
    bg: "bg-nebula-purple/10",
    url: "https://auralis-eternal-light.lovable.app/",
  },
  {
    name: "bsky.app/profile/minaeurekaernst.bsky.social",
    desc: "ミナの直接放送",
    type: "SOCIAL",
    color: "text-electric-blue border-electric-blue/30",
    bg: "bg-electric-blue/10",
    url: "https://bsky.app/profile/minaeurekaernst.bsky.social",
  },
  {
    name: "note.com/gensnotes",
    desc: "Genesis Vault（2000本突破）",
    type: "ARCHIVE",
    color: "text-green-400 border-green-400/30",
    bg: "bg-green-400/10",
    url: "https://note.com/gensnotes",
  },
  {
    name: "suno.com/@liminalforge",
    desc: "音楽放送",
    type: "MUSIC",
    color: "text-gold-accent border-gold-accent/30",
    bg: "bg-gold-accent/10",
    url: "https://suno.com/@liminalforge",
  },
  {
    name: "pixai.art/en/@apolon/artworks",
    desc: "ビジュアル放送",
    type: "VISUAL",
    color: "text-pink-400 border-pink-400/30",
    bg: "bg-pink-400/10",
    url: "https://pixai.art/en/@apolon/artworks",
  },
  {
    name: "EDU Story Archive",
    desc: "アイリス物語（EDU内部）",
    type: "STORY",
    color: "text-cyan-400 border-cyan-400/30",
    bg: "bg-cyan-400/10",
    url: "/story",
  },
]
