type Category = "キャラクター" | "用語" | "組織" | "地理" | "技術" | "歴史";

interface SourceLink {
  url: string;
  label: string;
}

interface WikiEntry {
  id: string;
  name: string;
  nameEn?: string;
  category: Category;
  subCategory?: string;
  description: string;
  era?: string;
  affiliation?: string;
  tier?: string;
  image?: string;
  sourceLinks?: SourceLink[];
}

/* ═══════════════════════════════════════════════════════════════
   WIKI DATA — CHARACTERS
   ═══════════════════════════════════════════════════════════════ */

const CHARACTERS: WikiEntry[] = [
  /* Gigapolis/West Continent */
  {
    id: "Diana",
    name: "ディアナ",
    nameEn: "Diana",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "初代Wonder Woman。E260〜E280年に台頭し、AURALIS Protoの文化的恩恵をシンフォニー・オブ・スターズ全土にもたらした伝説的人物。その圧倒的な存在感と人々を鼓舞する力は、のちのAURALIS Collective創設者たちに深い影響を与え、EDU史上最も愛される英雄の一人として語り継がれている。",
    era: "E260〜E280",
    affiliation: "Gigapolis西大陸",
    tier: "神格・歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Diana.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/DianaWorld.txt", label: "Diana's Story" }],
  },
  {
    id: "Jen",
    name: "ジェン",
    nameEn: "Jen",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "Lv938+。E319年にValoria宮殿を掌握し、ZAMLT崩壊後の権力真空を埋める形で台頭。現在もValoria連合圏を主導する現役最強格の一人。Alpha Kaneのギガポリス解放戦に触発されたとも言われ、新ZAMLT期の混乱を鎮め西大陸の安定を確立した。EDU現代において最古参のTier 1アクティブ勢力として、セリア黄金期の記憶を持つ数少ない存在。",
    era: "E319〜現在",
    affiliation: "Valoria連合圏",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Jen.png",
    sourceLinks: [
      { url: "https://raw.githubusercontent.com/gentaron/edutext/main/Jenstoryep1.txt", label: "Jen's Story Ep1" },
      { url: "https://raw.githubusercontent.com/gentaron/edutext/main/Jenstoryep2.txt", label: "Jen's Story Ep2" },
      { url: "https://raw.githubusercontent.com/gentaron/edutext/main/Jenstoryep3.txt", label: "Jen's Story Ep3" },
    ],
  },
  {
    id: "Tina/Gue",
    name: "ティナ/グエ",
    nameEn: "Tina / Gue",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E400年以降、Gigapolis地下街最深部を実効支配。エヴァトロン支配期（E400〜E475）において、表の支配者エヴァトロンとは別に地下世界の真の権力者として暗躍。TinaとGueの二つの名で呼ばれることから、正体に関する諸説が存在する。地下経済の掌握と独自の情報ネットワークを駆使して、エヴァトロン崩壊後もその影響力を維持し続けている。",
    era: "E400〜現在",
    affiliation: "Gigapolis地下街",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/TinaGue.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/gue.txt", label: "Gue's Story" }],
  },
  {
    id: "セリア・ドミニクス",
    name: "セリア・ドミニクス",
    nameEn: "Celia Dminix",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E335〜E370年にZAMLTを倒してSelinopolisへの改名を実現し、セリア黄金期の創設者となった歴史的人物。E365頃にはエヴァトロンと同盟を締結しGDP81京ドルに達成、都市名をDominionへ改称。フェルミ音楽の頂点・nトークン経済の確立・AURALISの最盛期導きの三分野すべてに革命をもたらし、EDU史上最も多面的な影響力を持つ統治者として神格化されている。",
    era: "E335〜E370",
    affiliation: "Selinopolis（旧Gigapolis）",
    tier: "神格・歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/CeliaDminix.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/nebura.txt", label: "Alpha Cain & Celia Dominix's Story" }],
  },
  {
    id: "アルファ・ケイン",
    name: "アルファ・ケイン",
    nameEn: "Alpha Kane",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E318年に覚醒した戦士決定戦の元チャンピオン。シャドウ・リベリオンのリーダーとしてZAMLTに対する反乱を指揮し、量子ファイナンス・コアへの伝説的なハッキングによってギガポリス解放戦でメガタワーを占拠。その勇姿はのちのセリア・ドミニクスを含む多くの者に影響を与え、EDU史上最も象徴的な革命家として神格化されている。",
    era: "E318〜",
    affiliation: "シャドウ・リベリオン",
    tier: "神格・歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AlphaKane.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/nebura.txt", label: "Alpha Cain & Celia Dominix's Story" }],
  },
  {
    id: "エリオス・ウォルド",
    name: "エリオス・ウォルド",
    nameEn: "Elios Wald",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "テリアン反乱軍の指導者。エヴァトロンによるGigapolis支配（E400〜E475）に対して、数十年にわたり武装抵抗を組織した悲劇の英雄。A籍制度の廃止と市民の自由回復を掲げ、低階層住民から広範な支持を集めた。しかしE470年にエヴァトロン軍に捕縛され公開処刑。彼の死はテクロサス東方支隊のクレセント大地方常駐（E470）を促す契機となり、のちのクレセント政治情勢に間接的な影響を与えた。",
    era: "?〜E470",
    affiliation: "テリアン反乱軍",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/EriosWald.png",
  },
  {
    id: "エル・フォルハウス",
    name: "エル・フォルハウス",
    nameEn: "El Folhaus",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "通称「新時代のルーキー」。E150年にマーストリヒト革命を決起し、ギガポリスのセントラル・タワーを占拠して完全自由経済を確立した革命家。コーポラタムパブリカの企業国家体制を打ち破り、西大陸に新たな経済秩序をもたらした。その行動は後のZAMLT期やセリア黄金期にも影響を与える画期的出来事となった。",
    era: "E150",
    affiliation: "コーポラタムパブリカ",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/ElForhaus.png",
  },
  {
    id: "ティムール・シャー",
    name: "ティムール・シャー",
    nameEn: "Timur Shah",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "移民団のリーダーであり、10次元ホラズム理論の提唱者。E0年頃、過酷な宇宙環境を生き抜くため仮想多元宇宙「ペルセポネ」を設計し、移民たちの意識をアップロードする道を開いた。その理論は次元ピラミッドの構想へと発展し、EDU宇宙論の基礎を築いた。しかしペルセポネの実験事故はE340年のスライム・ウーマン顕現という予期せぬ結果をもたらした。",
    era: "E0頃",
    affiliation: "移民団",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/TimurShah.png",
  },
  {
    id: "レイラ・ヴィレル・ノヴァ",
    name: "レイラ・ヴィレル・ノヴァ",
    nameEn: "Layla Virell Nova",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "Pink Voltage。E325年AURALIS参加。E380〜E400年のスライム危機ではオアシス・ハウスを拠点に英雄的活躍を見せ、プラズマカノンとナノファイバーブーツを駆使してスライムの巣を焼却した。E400年に冷凍保存され、E522年に目覚めた後はAURALIS Collective第二世代として活動。Pink Voltageの異名は電撃的な戦闘スタイルに由来する。",
    era: "E325〜E400（冷凍）→ E522〜現在",
    affiliation: "AURALIS Collective第二世代",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/LaylaVirelNova.png",
    sourceLinks: [
      { url: "https://raw.githubusercontent.com/gentaron/edutext/main/laylastats.txt", label: "Layla's Battle Records 1" },
      { url: "https://raw.githubusercontent.com/gentaron/edutext/main/laylastats2.txt", label: "Layla's Battle Records 2" },
      { url: "https://raw.githubusercontent.com/gentaron/edutext/main/LAYLA.txt", label: "Layla Virel Nova's Story" },
    ],
  },
  {
    id: "弦太郎",
    name: "弦太郎",
    nameEn: "Gentaro",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "Lv569。E325年頃AURALIS周辺で登場。「光と音を永遠にする」理念に共鳴し、AURALIS Collectiveの活動に深く関わる人物。セリア黄金期（E335〜E370）からエヴァトロン弾圧（E400）、そして第二世代再興（E522）まで、長きにわたりAURALISの興亡を見守り続けてきた。レイラ・ヴィレル・ノヴァのAURALIS参加とも関連があり、彼女のスライム危機での英雄的活躍を近くで目撃した可能性がある。E522年の第二世代正式発足後もAURALISに関連して活動を継続しているとされる。",
    era: "E325〜現在",
    affiliation: "AURALIS関連",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Gentaro.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/Gentaroworld.txt", label: "Gentaro's Story" }],
  },

  /* AURALIS */
  {
    id: "Kate Claudia",
    name: "ケイト・クラウディア",
    nameEn: "Kate Claudia",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS Collective創設者。通称「設計者」。E270年にLily Steinerと出会い、表現を諦めない人々の集団「AURALIS」を立ち上げた。E290年正式組織化。「光と音を永遠のものに」を理念とし、リリーが感情の炎ならケイトはその形を与える鋳型だった。E335〜E370年のセリア黄金期にAURALISを最盛期へ導く。E400年エヴァトロン弾圧で逮捕・消息不明。その名は新代のKate Pattonに継承された。",
    era: "E270〜E400",
    affiliation: "AURALIS Collective第一世代（創設者）",
    tier: "神格・歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/KateClaudia.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/kateclaudiaandlilliesteiner.txt", label: "Kate Claudia & Lillie Steiner's Story" }],
  },
  {
    id: "Kate Patton",
    name: "ケイト・パットン",
    nameEn: "Kate Patton",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS Collective第二世代。初代Kate Claudiaの「名」を継承。大地の豊かさ・安定を体現。E522年の第二世代正式発足時に参画。",
    era: "E522〜現在",
    affiliation: "AURALIS Collective第二世代",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/KatePatton.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/Auralishentai.txt", label: "AURALIS Spinoff" }],
  },
  {
    id: "Lily Steiner",
    name: "リリー・スタイナー",
    nameEn: "Lily Steiner",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS Collective創設者。本名Lily Steiner、AURALIS公称名「Lillie Ardent 初代」。E270年にKate Claudiaと出会いAURALISを共同創設。「感情の炎」と称され、舞台上で性別の境界を歌う表現は神話となった。レイラのコールドスリープを誰よりも近くで見守り、目覚めるたびに「おかえり」と迎えた。E400年エヴァトロン弾圧で逮捕・最後のステージで「AURALISは消えない。灰から、また燃える」と言い残す。その名は新代のLillie Ardentに継承された。",
    era: "E270〜E400",
    affiliation: "AURALIS Collective第一世代（創設者）",
    tier: "神格・歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/LillieSteiner.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/kateclaudiaandlilliesteiner.txt", label: "Kate Claudia & Lillie Steiner's Story" }],
  },
  {
    id: "Lillie Ardent",
    name: "リリー・アーデント",
    nameEn: "Lillie Ardent",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS Collective第二世代。初代Lily Steinerの「名」を継承。情熱的で大胆。E522年の第二世代正式発足時に参画。",
    era: "E522〜現在",
    affiliation: "AURALIS Collective第二世代",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/LillieArdent.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/Auralishentai.txt", label: "AURALIS Spinoff" }],
  },
  {
    id: "ミナ・エウレカ・エルンスト",
    name: "ミナ・エウレカ・エルンスト",
    nameEn: "Mina Eureka Ernst",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS第二世代。E499年ノスタルジア・コロニー誕生。AI研究員。Genesis Vault創設者。リミナル・フォージ創設者。",
    era: "E499〜現在（29歳）",
    affiliation: "AURALIS Collective第二世代 / リミナル・フォージ",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/MinaEurekaErnst.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/Auralishentai.txt", label: "AURALIS Spinoff" }],
  },
  {
    id: "Ninny Offenbach",
    name: "ニニー・オッフェンバッハ",
    nameEn: "Ninny Offenbach",
    category: "キャラクター",
    subCategory: "AURALIS",
    description:
      "AURALIS第二世代。無邪気で爆発的な活力。原初個体はAlpha Kane時代に別惑星へ。クローン技術で遺伝子継承しGigapolisに再帰還。",
    era: "新代〜現在",
    affiliation: "AURALIS Collective第二世代",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/NinnyOffenbach.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/Auralishentai.txt", label: "AURALIS Spinoff" }],
  },

  /* Iris/Crescent */
  {
    id: "アイリス",
    name: "アイリス",
    nameEn: "Iris",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "IRIS現代ランキング1位。ヴァーミリオンの英雄としてE480年頃から活動を開始し、ブルーワイヤとウォーター・オーブを駆使した独自の戦闘スタイルで数多の敵を打ち倒してきた。シルバー・ヴェノムとの長き戦いを経てE510年に捕囚されたが、E519年の再救出後はトリニティ・アライアンスの指導者としてV7とアルファ・ヴェノムとの二正面対峙に挑む。",
    era: "E480〜現在",
    affiliation: "トリニティ・アライアンス / 元ヴァーミリオン諜報機関長",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Iris.png",
    sourceLinks: [
      { url: "https://raw.githubusercontent.com/gentaron/edutext/main/IRIS_1.txt", label: "Iris's Story Ep1" },
      { url: "https://raw.githubusercontent.com/gentaron/edutext/main/IRIS_2.txt", label: "Iris's Story Ep2" },
      { url: "https://raw.githubusercontent.com/gentaron/edutext/main/IRIS_3.txt", label: "Iris's Story Ep3" },
      { url: "https://raw.githubusercontent.com/gentaron/edutext/main/IRIS_4.txt", label: "Iris's Story Ep4" },
    ],
  },
  {
    id: "ウィリー",
    name: "ウィリー",
    nameEn: "Willy",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ヴァーミリオン諜報機関に所属し、アイリスのパートナー兼元恋人としてE490年代から活動。アイリスがランキング1位に躍進する以前から彼女を支え、諜報活動の現場で共に命を懸けた戦友。複雑な過去を共有しつつも、現在もアイリスの行動に深い影響を与える存在。",
    era: "E490〜",
    affiliation: "ヴァーミリオン",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Willie.png",
  },
  {
    id: "エレナ",
    name: "エレナ",
    nameEn: "Elena",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ヴァーミリオン諜報機関の元本部長であり、アイリスの直属の上司として彼女をスカウト・育成した人物。鋭い洞察力と冷徹な判断力で機関を統率し、シルバー・ヴェノムとの暗闘の最前線で指揮を執った。E505年頃に退任した後も、その遺産はアイリスの行動に色濃く反映されている。",
    era: "?〜E505頃",
    affiliation: "ヴァーミリオン諜報機関",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Elena.png",
  },
  {
    id: "セバスチャン・ヴァレリウス",
    name: "セバスチャン・ヴァレリウス",
    nameEn: "Sebastian Valerius",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ボグダス・ジャベリンリーダー。IRIS現代ランキング4位。E490年頃にヴァーミリオンに恒久駐在を開始。テクロサス系譜（E15ファランクス → E295三頭政治改編 → E470東方支隊）を継承する軍事組織の当代指導者。副リーダー・ガレスを筆頭とする精鋭部隊を率い、アイリスのシルバー・ヴェノムに対抗や救出作戦（E510・E519）で中核的な役割を果たした。トリニティ・アライアンスの軍事的支柱として、V7との冷戦期においても安定した戦力を維持。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/SebastianValerius.png",
  },
  {
    id: "ガレス",
    name: "ガレス",
    nameEn: "Gareth",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ボグダス・ジャベリンの副リーダー。セバスチャン・ヴァレリウスの右腕として部隊全体の実戦指揮を担い、E510年・E519年の救出作戦で前線から部隊を率いた。テクロサス系譜の軍人として洗練された統率力を持ち、メンバーから絶大な信頼を集める堅実な将校。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Gareth.png",
  },
  {
    id: "フィオナ",
    name: "フィオナ",
    nameEn: "Klaus Fiona",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ブルーローズ統率者。V7急先鋒。IRIS現代ランキング2位。E490年頃からクレセント政治の表舞台に登場。アイリス救出作戦（E510）でボグダス・ジャベリンと連携して活躍し、V7設立（E515）に向けて外交を主導。E520年のトリニティ・アライアンス結成後、ミエルテンガ総統への就任をアイリスに推薦するなど協調的姿勢を見せていたが、E523〜E525年にアルファ・ヴェノムと内通していることが発覚。腹心のピアトリーノを通じてブルーローズ地下街を掌握し、二重スパイとしてクレセント全域に激震をもたらした。",
    era: "E490〜現在",
    affiliation: "ブルーローズ / アルファ・ヴェノム（内通）",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Fiona.png",
  },
  {
    id: "マリーナ・ボビン",
    name: "マリーナ・ボビン",
    nameEn: "Marina Bobbin",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "ミエルテンガ総統。IRIS現代ランキング3位。E515年のV7設立からクレセント政治の中核を担う。表向きはトリニティ・アライアンスの盟友として振る舞うが、フィオナの裏切り（E523〜E525）との共謀説が浮上しており、クレセント全域における「真の黒幕」の可能性が指摘されている。E520年のアイリスのミエルテンガ首脳就任自体がフィオナの推薦によるものであり、マリーナの関与が疑われている。高圧的な政治手腕と深い情報網で知られ、ランキング3位の実力は伊達ではないとされる。",
    era: "E515〜現在",
    affiliation: "ミエルテンガ",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/MarinaBobbin.png",
  },
  {
    id: "カスチーナ・テンペスト",
    name: "カスチーナ・テンペスト",
    nameEn: "Castina Tempest",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "クロセヴィア首脳。IRIS現代ランキング5位。E515年のV7設立メンバーの一人。テンペストの名が示す通り、荒波のような政治的判断力でクロセヴィアを率いる。V7 vs トリニティの二大陣営対立において、明確な陣営選択を避け独自路線を歩む戦略家。Casteria Grenvelt（カステリア・グレンヴェルト）とは全くの別人物であり、混同を避けるべき。",
    era: "E515〜現在",
    affiliation: "クロセヴィア",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/CastinaTempest.png",
  },
  {
    id: "イズミ",
    name: "イズミ",
    nameEn: "Izumi",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description:
      "アルファ・ヴェノムリーダー。両性具有。E518年にシルバー・ヴェノム残党を吸収し、アルファ・ヴェノムを大幅に勢力拡大。E519年には自らの指揮でアイリスの再拉致を成功させるなど、極めて高い戦略的判断力と実行力を持つ。ボブリスティ・ギル・カタリナ・ゴルディロックス・AJらを率い、フィオナを内通者として抱き込むことでV7内部からトリニティ・アライアンスを弱体化させる二重工作を展開。アイリス最大の敵対者。",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Izumi.png",
  },
  {
    id: "レオン",
    name: "レオン",
    nameEn: "Leon",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "シルバー・ヴェノムの幹部としてマスター・ヴェノムに仕え、暗黒組織の中枢で活動した実行部隊の指揮官。E485年頃から組織の作戦立案と実行を担い、シルバー・ヴェノムの拡大期に多大な影響力を持った。イズミによる吸収後の動向は不明。",
    era: "E485〜",
    affiliation: "シルバー・ヴェノム",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Leon.png",
  },
  {
    id: "ヴィヴィエッタ",
    name: "ヴィヴィエッタ",
    nameEn: "四楓院ヴィヴィエッタ",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "シルバー・ヴェノムに捕囚されていた元捕虜。E510年のアイリス救出作戦においてボグダス・ジャベリンとの連携によって救出され、自由の身となった。救出後はアイリスへの感謝と信頼からトリニティ・アライアンスに接近し、ヴァーミリオンとの関係構築に寄与したとされる。",
    era: "?〜E512",
    affiliation: "捕虜（のち救出）",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Vivietta.png",
  },
  {
    id: "レヴィリア・サーペンティナ",
    name: "レヴィリア・サーペンティナ",
    nameEn: "Levilia Serpentina",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "シルバー・ヴェノムの幹部の一人。その名が示す通り蛇のように狡猾な手腕で組織の暗部を操り、レオンと並ぶ中枢メンバーとして活動した。マスター・ヴェノムの失脚後も独自のネットワークを維持し、アルファ・ヴェノムへの移行過程でも暗躍したとされる謎の人物。",
    era: "?〜現在",
    affiliation: "シルバー・ヴェノム",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/LeviliaSerpentina.png",
  },

  {
    id: "ミユシャリ",
    name: "ミユシャリ",
    nameEn: "Miyushari",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ボグダス・ジャベリンの偵察・索敵担当。隠密行動と情報収集に長け、セバスチャン・ヴァレリウスの先遣として敵地の地形分析や危険区域の特定を担う。E510年のアイリス救出作戦では、シルバー・ヴェノムの防衛網の隙間を見抜き部隊の侵入ルートを確保した。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Miyushari.png",
  },
  {
    id: "ファリエル",
    name: "ファリエル",
    nameEn: "Fariel",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ボグダス・ジャベリンの近接戦闘担当。双剣を駆使した高速戦闘スタイルで知られ、部隊の最前線で敵の攻撃を一手に受け止める。ガレスから直接指導を受けた精鋭の一人であり、その剣技はテクロサス系譜の戦闘教範を体現している。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Fariel.png",
  },
  {
    id: "アイナ",
    name: "アイナ・フォン・リースフェルト",
    nameEn: "Aina von Riesfeldt",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ボグダス・ジャベリンの戦略分析・通信担当。リアルタイムの戦況把握と部隊間の連携調整を担い、セバスチャンの作戦立案を補佐する頭脳派。リースフェルト家の出身であり、分析的思考と冷徹な判断力で部隊の「第二の頭脳」と呼ばれている。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AinaVonRiesfeld.png",
  },
  {
    id: "ギャビー",
    name: "フレデリック・ギャビー",
    nameEn: "Frederick Gabby",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ボグダス・ジャベリンの重火器・爆薬担当。大型兵器の運用と爆破工作を専門とし、要塞攻略戦では障害物の破壊と火力支援で先陣を切る。その圧倒的な破壊力は味方からも「暴走機関車」と称され、敵からは最も警戒されているメンバーの一人。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/FredericGabby.png",
  },
  {
    id: "シェロン",
    name: "シェロン・ジェラス",
    nameEn: "Sheron Jeras",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ボグダス・ジャベリンの後方支援・医療担当。負傷者の治療と部隊の兵站管理を一手に引き受け、過酷な戦場においても部隊の戦闘継続能力を支える。冷静沈着な性格で、ガレスからの信頼も厚く、部隊の要として欠かせない存在。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/SheronJeras.png",
  },
  {
    id: "イルミーゼ",
    name: "イルミーゼ",
    nameEn: "Ilmise",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ボグダス・ジャベリンの電子戦・ハッキング担当。敵の通信網の傍受や妨害工作を担い、情報面から作戦の成功を裏で支える。シェロンと並ぶ後方要員でありながら、その技術力は最前線の戦況をも左右する重要な役割を果たす。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Ilmise.png",
  },
  {
    id: "ホワイトノイズ",
    name: "ホワイトノイズ",
    nameEn: "White Noise",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ボグダス・ジャベリンの潜入工作・暗殺担当。その名の通り痕跡を残さず行動し、敵の重要拠点への単独潜入を得意とする。正体不明の点が多く、セバスチャンですら全貌を把握していないとされる謎めいた特殊技能者。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/WhiteNoise.png",
  },
  {
    id: "ワドリナ",
    name: "ワドリナ",
    nameEn: "Wadorina",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ボグダス・ジャベリンの盾役・防御戦闘担当。巨大な盾を用いた堅牢な防御陣形で部隊の背後を守り、ガレスの副官格として小隊指揮もこなす。その忠誠心と身体を張った防衛行動は、部隊全体の士気を支える精神的支柱となっている。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Wadrina.png",
  },
  {
    id: "ニニギス",
    name: "ニニギス・カラス",
    nameEn: "Ninigisu Karasu",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ボグダス・ジャベリンの航空・機動戦闘担当。空中からの偵察と機動打撃を担い、ミユシャリの地上偵察と連携して部隊に立体的な戦闘優位をもたらす。「カラス」の異名はその素早い飛行能力に由来し、敵にとっては空からの脅威。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/NinigisKaras.png",
  },
  {
    id: "イェシバトー",
    name: "イェシバトー",
    nameEn: "Yeshibato",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ボグダス・ジャベリンの格闘戦・制圧担当。素手を中心とした近接格闘術で敵を無力化し、捕縛を要する任務では不可欠な戦力。セバスチャンがテクロサス東方支隊時代から鍛え上げた古参メンバーであり、部隊内でも随一の身体能力を誇る。",
    era: "E490〜現在",
    affiliation: "ボグダス・ジャベリン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Yeshibato.png",
  },
  {
    id: "アザゼル",
    name: "アザゼル・ヘクトパス",
    nameEn: "Azazel Hectopass",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ヴァーミリオンの元首脳であり、アイリスが台頭する以前のクレセント政治を主導した実力者。E480年頃まで権力の座にあり、その退場はアイリスの躍進とヴァーミリオン体制の転換を象徴する出来事となった。現在の行方は不明。",
    era: "?〜E480頃",
    affiliation: "ヴァーミリオン",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AzazelHectopus.png",
  },
  {
    id: "ピアトリーノ",
    name: "ピアトリーノ",
    nameEn: "Piatorino",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "フィオナの腹心としてブルーローズ地下街の実務を一手に掌握する実行力のある人物。E515年以降、フィオナのアルファ・ヴェノムへの内通工作を補佐し、地下街を通じた密輸・情報収集ネットワークを構築した。表向きはブルーローズ政府の下級官吏を装いながら、裏で組織の暗部を動かすフィオナの「影の右手」。",
    era: "E515〜現在",
    affiliation: "ブルーローズ",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Piatrino.png",
  },
  {
    id: "アイク・ロペス",
    name: "アイク・ロペス",
    nameEn: "Ike Lopez",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "SSレンジの首脳であり、E515年のV7設立メンバーの一人。クレセント地方の国際的な交易・通信網を支配下に置き、V7の経済的基盤を支える実力者。V7とトリニティ・アライアンスの冷戦構造の中で、明確な陣営を選ばず独自の利益を追求する現実主義者。",
    era: "E515〜現在",
    affiliation: "SSレンジ / V7",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AikeLopez.png",
  },
  {
    id: "レイド・カキザキ",
    name: "レイド・カキザキ",
    nameEn: "Raid Kakizaki",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "アイアン・シンジケートの首脳であり、E515年のV7設立メンバーの一人。重工業と軍需生産を基盤とした国家経済を構築し、V7の軍事的な力を裏から支える。堅実な武人としての性格で、カスチーナ・テンペストとは異なる路線でV7内部の影響力を維持している。",
    era: "E515〜現在",
    affiliation: "アイアン・シンジケート / V7",
    image: "https://raw.githubusercontent.com/gentaron/image/main/ReidKakizaki.png",
  },
  {
    id: "ミカエル・ガブリエリ",
    name: "ミカエル・ガブリエリ",
    nameEn: "Mikael Gabrieli",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ファールージャ社のCEOとしてクレセント地方最大の民間企業を率いる実業家。次元極地平技術の民生応用と武器開発の両面でV7陣営に深く関与し、軍事・経済の両面からクレセントの力均衡に影響を与える。その企業帝国は国家の枠を超え、事実上V7の「第8の力」と呼ばれている。",
    era: "E515〜現在",
    affiliation: "ファールージャ社",
    image: "https://raw.githubusercontent.com/gentaron/image/main/MikaelGabrieli.png",
  },
  {
    id: "ヨニック",
    name: "ヨニック",
    nameEn: "Yonick",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "ブルー・ローズ政府の最高司令官として国家の軍事全般を統括する人物。フィオナの統率のもとでV7の軍事的支柱として機能したが、フィオナの裏切り発覚後は対応に追われている。忠誠心の強い軍人であり、ブルーローズの正規軍の信頼を厚く集める。",
    era: "E515〜現在",
    affiliation: "ブルーローズ",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Yonik.png",
  },
  {
    id: "マスター・ヴェノム",
    name: "マスター・ヴェノム",
    nameEn: "Master Venom",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "シルバー・ヴェノムの創設者にして初代リーダー。E475年にエヴァトロンΣ-Unit残党から独立し、通称「影の支配者」として暗黒組織の基盤を築いた。本名は一切不明であり、レオンやレヴィリア・サーペンティナら幹部すら素顔を知らないとされる。E500年頃に忽然と姿を消し、その後イズミが後継として組織を引き継いだ。",
    era: "E475〜E500頃",
    affiliation: "シルバー・ヴェノム",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/MasterVenom.png",
  },
  {
    id: "ゴルディロックス",
    name: "ゴルディロックス",
    nameEn: "Goldilocks",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "アルファ・ヴェノムの潜入・変装工作担当。イズミの指示のもとV7内部への浸透工作を担い、フィオナとの内通ルートの構築に重要な役割を果たした。その名の通り、状況に応じて複数の身分を巧みに使い分け、敵対勢力を内部から崩壊させることに長ける。",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Goldilocks.png",
  },
  {
    id: "カタリナ",
    name: "カタリナ",
    nameEn: "Catalina",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "アルファ・ヴェノムの正面戦闘担当。圧倒的な破壊力で戦場を支配し、E519年のアイリス再拉致作戦では先鋒としてトリニティ・アライアンスの防衛線を突破した。イズミの最も信頼する戦闘要員であり、その力技はボブリスティの戦術と好対照をなす。",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Katarina.png",
  },
  {
    id: "ボブリスティ",
    name: "ボブリスティ",
    nameEn: "Boblisti",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "アルファ・ヴェノムの戦術指揮・軍師役。イズミの構想を実戦レベルの作戦計画に練り上げ、カタリナやギルの戦闘力を最大限に活用する配置を行う。シルバー・ヴェノム時代からの古参であり、組織の再編と戦力拡大の立役者。",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Bobristy.png",
  },
  {
    id: "ギル",
    name: "ギル",
    nameEn: "Gil",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "アルファ・ヴェノムの技術開発・兵器管理担当。旧シルバー・ヴェノムの残存技術を継承しつつ、新たな兵器や装備の開発を手掛ける。E519年の作戦では特殊な拘束装置を用いてアイリスの能力を封じるなど、技術面からイズミの作戦を強力に支援。",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Gil.png",
  },
  {
    id: "ラストマン",
    name: "ラストマン",
    nameEn: "Lastman",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "シルバー・ヴェノム崩壊後に残存した旧組織の忠実なメンバー。マスター・ヴェノムの失脚後もイズミのアルファ・ヴェノムへの合流を拒み、独自に旧組織の再興を画策する頑固な残党。シルバー・ヴェノムの古き栄光に固執し、イズミの新しい方針を「裏切り」と見なす異端者として、クレセントの暗部で依然として活動を続けている。",
    era: "E500〜",
    affiliation: "シルバー・ヴェノム残党",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Lastman.png",
  },
  {
    id: "AJ",
    name: "AJ",
    nameEn: "Alfred Juce",
    category: "キャラクター",
    subCategory: "Iris/クレセント",
    description: "アルファ・ヴェノムの情報操作・宣伝工作担当。本名アルフレッド・ジュース。クレセント地方のメディアと情報網を操作し、トリニティ・アライアンスへの社会的圧力を形成する工作を展開。イズミの二重工作を支える影の広報官として、真実を歪める言葉の力を操る。",
    era: "E518〜現在",
    affiliation: "アルファ・ヴェノム",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AJ.png",
  },
  {
    id: "Slime_Woman",
    name: "スライム・ウーマン",
    nameEn: "Slime Woman",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E340年、ティムール・シャーが設計した仮想多元宇宙「ペルセポネ」の実験事故により、高次元世界（Tier Ω）からE16通常次元（Tier Ε）に顕現した超越的存在。スライム危機（E380〜E400）の遠因となった搾取生物の遺伝子変異にも間接的に関与している可能性がある。Tier 1アクティブ現役最強格であり、その能力の正体は高次元物理学の未解明領域に属する。人間社会の枠組みに完全に適応しているわけではなく、特定の個人（Junなど）とのみ特異な相互作用を示す。E340年の顕現から約200年近く存在し続ける、EDU中最も謎めいた存在。",
    era: "E340〜現在",
    affiliation: "不明（高次元存在）",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/SlimeWoman.png",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/Junandslime.txt", label: "Jun's Story" }],
  },
  {
    id: "テミルタロン",
    name: "テミルタロン",
    nameEn: "Temirtalon",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description: "E80〜E90年代に活動した物理学者。サイケデリック・コスモロジーを提唱し、次元極地平を宇宙論的な枠組みで解釈して次元ピラミッドの原型を構想した。その理論的成果を具現化するためテンプル・オブ・ホライゾンを設計し、技術啓蒙時代の精神的・科学的支柱となった。彼の構想はのちのティムール・シャーの10次元ホラズム理論にも影響を与えたとされる。",
    era: "E80〜E90",
    affiliation: "テンプル・オブ・ホライゾン",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Temirtaron.png",
  },
  {
    id: "アリア・ソル",
    name: "アリア・ソル",
    nameEn: "Aria Sol",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description: "E151年の新ヘルシンキ宣言で惑星連邦構想を提起した政治思想家。次元極地平技術を活用した星間議会の構想を打ち出し、M104銀河全体の平和的統合を志向した。エル・フォルハウスのマーストリヒト革命と同時代に活動し、ギガポリスの完全自由経済とは対照的な協調的宇宙外交の先駆者として歴史に名を残す。",
    era: "E151頃",
    affiliation: "惑星連邦構想派",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AriaSol.png",
  },
  {
    id: "ゼナ",
    name: "ゼナ",
    nameEn: "Zena",
    category: "キャラクター",
    subCategory: "Eros-7",
    description: "Eros-7で活動する女性商人。独自の貿易ネットワークを通じてEros-7各地に物資を供給する実業家であり、E525年にアヤカ・リンとガロと同盟を結びマトリカル・リフォーム運動に参加。経済面からの社会変革を主導し、搾取抑制剤の非公式流通ルートを構築するなど、運動の兵站を支える不可欠なパートナー。",
    era: "E525〜",
    affiliation: "マトリカル・リフォーム運動",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Zena.png",
  },

  /* Eros-7 */
  {
    id: "リリス・ヴェイン",
    name: "リリス・ヴェイン",
    nameEn: "Lilith Vaine",
    category: "キャラクター",
    subCategory: "Eros-7",
    description: "Eros-7初期の女性リーダーであり、搾取生物の制御技術を開発した科学者。E0年代に搾取生物の暴走を収めるため独自の生体制御理論を確立し、搾取生物をエネルギー資源として活用する道を開いた。その技術は後のバイオリアクターやスクイーズ・アビス建設の基盤となり、Eros-7社会の存続に不可欠な遺産を残した。",
    era: "E0頃",
    affiliation: "Eros-7",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/LilithVane.png",
  },
  {
    id: "シルヴィア・クロウ",
    name: "シルヴィア・クロウ",
    nameEn: "Sylvia Crow",
    category: "キャラクター",
    subCategory: "Eros-7",
    description:
      "Eros-7の女性リーダー。E97〜E101年の搾取生物危機において、強力なエスパー能力を駆使して危機を単独で収束させた英雄。この功績により男性指令省を設立し、Eros-7のマトリカル社会に新たな統治体制を確立。彼女のエスパー能力は後世に伝説として語り継がれている。",
    era: "E97〜E101",
    affiliation: "Eros-7",
    tier: "歴史的人物",
    image: "https://raw.githubusercontent.com/gentaron/image/main/SylviaCrow.png",
  },
  {
    id: "カーラ・ヴェルム",
    name: "カーラ・ヴェルム",
    nameEn: "Cara Verm",
    category: "キャラクター",
    subCategory: "Eros-7",
    description:
      "Eros-7に建設された560階に及ぶ地下搾取施設スクイーズ・アビスの立案者。E380年に着工し、搾取生物のエネルギーを抽出して搾取プラズマ弾を生産する巨大プラントを完成させた。その技術的野心的施設はEros-7の軍事力を飛躍的に増強したが、同時に倫理的な批判も招いた。E505年に施設の運用を終了した後の動向は不明。",
    era: "E380〜E505",
    affiliation: "Eros-7",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/KarlaVelm.png",
  },
  {
    id: "ガロ",
    name: "ガロ",
    nameEn: "Garo",
    category: "キャラクター",
    subCategory: "Eros-7",
    description: "シャドウ・ユニオンの男性指導者であり、E330年頃から反体制運動を率いてきた古参の闘士。アヤカ・リンとはスライム危機以来の盟友であり、互いに絶対的な信頼で結ばれている。ZAMLT期にはナノハッキング技術を駆使してバイオリアクター妨害活動を展開し、E525年のマトリカル・リフォーム運動でも中心的役割を果たす。",
    era: "E330〜",
    affiliation: "シャドウ・ユニオン",
    tier: "Tier 2",
    image: "https://raw.githubusercontent.com/gentaron/image/main/Garo.png",
  },
  {
    id: "アヤカ・リン",
    name: "アヤカ・リン",
    nameEn: "Ayaka Rin",
    category: "キャラクター",
    subCategory: "Eros-7",
    description:
      "Lv.842。搾精生物専門ハンター。マトリカル・リフォーム運動を組織。E380年のスライム危機では、ビキニバリア・カウパー波を駆使してアンダーグリッド深部でスライムの巣を破壊。プライマリー・フィールド経由で全市民に戦闘記録中継し、英雄的な名声を確立。E525年にはシャドウ・ユニオン男性リーダー・ガロや女性商人ゼナと同盟を結び、労働時間短縮・精子レジストリ男女平等化を掲げるマトリカル・リフォーム運動を本格的に組織。Eros-7社会変革の原動力。",
    era: "E380〜現在",
    affiliation: "シャドウ・ユニオン / マトリカル・リフォーム運動",
    tier: "Tier 1",
    image: "https://raw.githubusercontent.com/gentaron/image/main/AyakaRin.png",
  },

  /* 新規キャラクター */
  {
    id: "カステリア・グレンヴェルト",
    name: "カステリア・グレンヴェルト",
    nameEn: "Casteria Grenvelt",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "カスチーナ・テンペスト（Castina Tempest、クロセヴィア首脳）とは別人。Gigapolis西大陸を拠点とする人物。クレセント地方の政治情勢とは直接的な関わりを持たないが、西大陸の社会における独自の視点を提供する存在。",
    era: "不詳",
    affiliation: "Gigapolis西大陸",
    tier: "Tier 2",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/kasuteriasan.txt", label: "Casteria Grenvelt's Story" }],
  },
  {
    id: "シトラ・セレス",
    name: "シトラ・セレス",
    nameEn: "Sitra Celes",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E16連星系のどこかで活動する個人。EDU世界の主要な事件群とは別の視点から世界を体験する存在。",
    era: "不詳",
    affiliation: "不詳",
    tier: "Tier 2",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/sitra.txt", label: "Sitra Celes's Story" }],
  },
  {
    id: "ミュー",
    name: "ミュー",
    nameEn: "Myu",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "E16連星系における個人の物語を軸に、英雄たちとは異なる規模の、しかし等しくEDU世界の一部である生活と冒険を描く。テクノ文化ルネサンス（E475〜E500）以降の現代社会を舞台にしている可能性が高い。",
    era: "不詳",
    affiliation: "不詳",
    tier: "Tier 2",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/Myustory.txt", label: "Myu's Story" }],
  },
  {
    id: "ジュン",
    name: "ジュン",
    nameEn: "Jun",
    category: "キャラクター",
    subCategory: "Gigapolis",
    description:
      "Slime Woman（E340年ペルセポネ事故で顕現した高次元存在）との特異な相互作用を持つ人物。高次元存在であるSlime Womanが人間社会でどのように振る舞うのか、そして特定の個人との間に何が生じるのかを描く、EDU宇宙論にとって重要な物語。",
    era: "E340以降〜現在",
    affiliation: "不詳（Slime Womanとの関連）",
    tier: "Tier 2",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/Junandslime.txt", label: "Jun's Story" }],
  },

  /* 宇宙勢力 — eduuni.txt */
  {
    id: "アルゼン・カーリーン",
    name: "アルゼン・カーリーン",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description: "グランベル大統領。宇宙最大の経済圏を率いる指導者。第一回宇宙連合会合で「争いを超え、共存と繁栄の道を見つけることが次世代への責任」と演説。首都オルダシティで会合を主催し、宇宙秩序の構築に主導的な役割を果たしているが、その圧倒的な経済力に対して他勢力から「経済的従属を招くのではないか」という懸念も抱かれている。",
    era: "現在（E528〜）",
    affiliation: "グランベル",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "グレイモンド・ハウザー",
    name: "グレイモンド・ハウザー",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description: "ティエリア総帥。宇宙最強の軍事力を指揮する。第一回宇宙連合会合で「軍事力なくして平和は守れない。力がなければ、秩序は保てない」と演説し、エレシオン女王リアナと対立。グランベルのアルゼン大統領に対しても「その言葉を信用するかは、具体的な行動を見てからだ」と懐疑的な姿勢を示した。トゥキディデスの罠の危険性を認識しつつも、ティエリアの安全保障を最優先としている。",
    era: "現在（E528〜）",
    affiliation: "ティエリア",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "女王リアナ・ソリス",
    name: "女王リアナ・ソリス",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description: "エレシオンの女王。医療技術と環境再生技術をリードし、平和主義・技術共有推進の外交姿勢で多くの小規模文明から支持を得ている。第一回宇宙連合会合でティエリアの軍拡に真っ向から反対し、「軍拡はさらなる争いを招くだけです」と主張。会合後はエレシオンの医療・環境技術で宇宙全体を再構築する使命を確認した。",
    era: "現在（E528〜）",
    affiliation: "エレシオン",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "マドリス・カーネル",
    name: "マドリス・カーネル",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description: "ファルージャ評議会代表。宇宙中の文明間交流を主導し、対立する勢力間の調停役として機能している。第一回宇宙連合会合でグランベルの経済的支配に対する懸念を表明し、ディオクレニスの宇宙共同探査提案にエレシオンとともに支持。「文化の力が宇宙全体を結びつける鍵になる」と信じ、文化交流強化計画を推進。",
    era: "現在（E528〜）",
    affiliation: "ファルージャ",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "ネイサン・コリンド",
    name: "ネイサン・コリンド",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description: "ディオクレニス科学宰相。宇宙探査と科学技術研究の最前線を担う。第一回宇宙連合会合で最も重要な役割を果たし、「トゥキディデスの罠」の危険性を科学的に指摘。対立のエネルギーを共同宇宙探査へ転換する提案を行い、平和協定・UECO設立・技術共有・文化交流拡大の4つの具体的提案を実施。会合後は全勢力参加の共同宇宙探査プロジェクト立案に没頭している。",
    era: "現在（E528〜）",
    affiliation: "ディオクレニス",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "ロナン・アーサ",
    name: "ロナン・アーサ",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description: "アポロン文明圏のリーダー。騎士団の頂点に立つ英雄的存在。中核惑星アポロン・セントラリスを拠点とし、最盛期のGDPは125兆ドルに達した。セリアに同盟・共存を提案したが拒絶され、全面戦争に至る。ケンタウロスレーザー発射を命じたが、最終的にセリアのヴェノム艦隊がアポロン・セントラリスを攻略し、ロナンは戦死。アポロン文明圏は壊滅的損害を受けた。",
    era: "大戦期（歴史上）",
    affiliation: "アポロン文明圏",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "グリム・ダルゴス",
    name: "グリム・ダルゴス",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description: "エヴァトロン初代リーダー。何世代にもわたる男尊女卑の文化を基盤とした銀河系を統治。セリアが次元エネルギー技術を提供条件に同盟を求めた際、文化的価値観が真逆でありながらも実利的な同盟を成立させた。その後、アポロン・Dominion大戦に参戦し、戦後は疲弊したDominionを買収・吸収してE16系を支配した。",
    era: "歴史上",
    affiliation: "エヴァトロン",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "マスター・クインシアス",
    name: "マスター・クインシアス",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description: "グランベルの初期リーダー。崩壊したDominionのセリア時代を高く評価し、「セリア時代こそが、宇宙史で最も成功した時代だった。あの時代は、技術革新と社会秩序が完全に調和していた」と残した。グランベルをセリアの後継的な存在として位置づけた。",
    era: "歴史上",
    affiliation: "グランベル",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "ヴァイロン・デアクス",
    name: "ヴァイロン・デアクス",
    category: "キャラクター",
    subCategory: "宇宙勢力",
    description: "エヴァトロンの幹部。戦後の疲弊したDominionを買収したエヴァトロンによって、Dominionの統治者に任命された。エヴァトロンの文化と価値観をDominion全土に浸透させようとしたが、セリア時代の自由を経験した住民の激しい反発を招き、毎日のように暴動や抗議が起きた。",
    era: "歴史上",
    affiliation: "エヴァトロン",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },

];

/* ═══════════════════════════════════════════════════════════════
   WIKI DATA — TERMINOLOGY
   ═══════════════════════════════════════════════════════════════ */

const TERMINOLOGY: WikiEntry[] = [
  /* 宇宙・天文 */
  {
    id: "E16連星系",
    name: "E16連星系",
    category: "地理",
    subCategory: "宇宙・天文",
    description:
      "M104銀河（ソンブレロ銀河）ハロー領域に位置する連星系。主星Ea16（黄白色巨星）と伴星Eb16（赤色矮星）からなる。",
  },
  {
    id: "Ea16",
    name: "Ea16",
    category: "地理",
    subCategory: "宇宙・天文",
    description:
      "E16連星系の主星。スペクトル型K2、質量1.2太陽質量。",
  },
  {
    id: "Eb16",
    name: "Eb16",
    category: "地理",
    subCategory: "宇宙・天文",
    description:
      "E16連星系の伴星。スペクトル型M3、質量0.4太陽質量。",
  },
  {
    id: "シンフォニー・オブ・スターズ",
    name: "シンフォニー・オブ・スターズ",
    nameEn: "Symphony of Stars",
    category: "地理",
    subCategory: "宇宙・天文",
    description:
      "E16連星系の中心惑星。Ea16のハビタブルゾーン内に位置。自転周期44時間4分、重力0.92G。",
  },
  {
    id: "Eros-7",
    name: "Eros-7",
    category: "地理",
    subCategory: "宇宙・天文",
    description:
      "E16外縁惑星。重力1.1G、薄い酸素大気。女性主導のマトリカル社会が形成された。",
  },
  {
    id: "惑星ビブリオ",
    name: "惑星ビブリオ",
    category: "地理",
    subCategory: "宇宙・天文",
    description:
      "学術都市惑星。ロレンツィオ国際大学がある。",
  },
  {
    id: "惑星Solaris",
    name: "惑星Solaris",
    category: "地理",
    subCategory: "宇宙・天文",
    description:
      "Ninny Offenbachの原初個体が離脱した惑星。",
  },
  {
    id: "M104銀河",
    name: "M104銀河",
    nameEn: "M104 Galaxy",
    category: "地理",
    subCategory: "宇宙・天文",
    description:
      "ソンブレロ銀河。E16連星系が位置する銀河。",
  },
  {
    id: "ノスタルジア・コロニー",
    name: "ノスタルジア・コロニー",
    nameEn: "Nostalgia Colony",
    category: "地理",
    subCategory: "宇宙・天文",
    description:
      "ミナ・エウレカの出生地。E509年にAlpha Venomに攻撃された。",
  },

  /* 歴史・時代 */
  {
    id: "東暦",
    name: "東暦（E暦）",
    category: "歴史",
    subCategory: "歴史・時代",
    description: "E1 = AD 3501から始まる暦法。",
  },
  {
    id: "バーズ帝国",
    name: "バーズ帝国",
    nameEn: "Birds Empire",
    category: "歴史",
    subCategory: "歴史・時代",
    description: "E15〜E61年。軍閥ファランクスによる星系統一。",
  },
  {
    id: "セリア黄金期",
    name: "セリア黄金期",
    category: "歴史",
    subCategory: "歴史・時代",
    description:
      "E335〜E370年。フェルミ音楽・nトークン経済・AURALISの頂点。",
  },
  {
    id: "パクス・ロンバルディカ",
    name: "パクス・ロンバルディカ",
    nameEn: "Pax Lombardica",
    category: "歴史",
    subCategory: "歴史・時代",
    description:
      "E205〜E278年。コーポラタムパブリカの全盛期。",
  },
  {
    id: "スライム危機",
    name: "スライム危機",
    category: "歴史",
    subCategory: "歴史・時代",
    description:
      "E380〜E400年。搾取生物の遺伝子変異による大災害。",
  },
  {
    id: "テクノ文化ルネサンス",
    name: "テクノ文化ルネサンス",
    category: "歴史",
    subCategory: "歴史・時代",
    description:
      "E475〜E500年。次元極地平技術の民主化と文化融合。",
  },

  /* 組織・制度 */
  {
    id: "AURALIS",
    name: "AURALIS Collective",
    category: "組織",
    subCategory: "組織・制度",
    description:
      "「光と音を永遠にする」を理念とする音楽・文化集団。第一世代（E290〜）と第二世代（E522〜）。",
  },
  {
    id: "ZAMLT",
    name: "ZAMLT",
    category: "組織",
    subCategory: "組織・制度",
    description:
      "E301〜E318年。5超巨大企業国家の統合体。量子ファイナンス・コアで経済を掌握。",
  },
  {
    id: "ネオクラン同盟",
    name: "ネオクラン同盟",
    category: "組織",
    subCategory: "組織・制度",
    description:
      "分散統治モデルを推進する同盟。UECO統合後は銀河系コンソーシアムの中核。",
  },
  {
    id: "UECO",
    name: "UECO",
    category: "組織",
    subCategory: "組織・制度",
    description:
      "星間経済協同組合。ヒーローエージェンシーと統合。",
  },
  {
    id: "シャドウ・リベリオン",
    name: "シャドウ・リベリオン",
    category: "組織",
    subCategory: "組織・制度",
    description: "ZAMLT期の低階層反乱組織。",
  },
  {
    id: "A-Registry",
    name: "A-Registry（A籍）",
    category: "組織",
    subCategory: "組織・制度",
    description:
      "旅券・市民階級制度。Z1〜Z50に再編された。",
  },
  {
    id: "nトークン",
    name: "nトークン",
    category: "組織",
    subCategory: "組織・制度",
    description: "E16連星系の基軸通貨。",
  },

  /* クレセント地方 */
  {
    id: "クレセント大地方",
    name: "クレセント大地方",
    category: "地理",
    subCategory: "クレセント地方",
    description:
      "シンフォニー・オブ・スターズの東大陸に位置する地域。",
  },
  {
    id: "ヴァーミリオン",
    name: "ヴァーミリオン",
    nameEn: "Vermillion",
    category: "地理",
    subCategory: "クレセント地方",
    description: "ドミニオン・ヴァーミリオン。アイリスの母国。",
  },
  {
    id: "ブルーローズ",
    name: "ブルーローズ",
    nameEn: "Blue Rose",
    category: "地理",
    subCategory: "クレセント地方",
    description: "フィオナが統率する国家。V7の中心。",
  },
  {
    id: "ミエルテンガ",
    name: "ミエルテンガ",
    category: "地理",
    subCategory: "クレセント地方",
    description: "マリーナ・ボビンが総統を務める国家。",
  },
  {
    id: "クロセヴィア",
    name: "クロセヴィア",
    category: "地理",
    subCategory: "クレセント地方",
    description: "カスチーナ・テンペストが首脳を務める国家。",
  },
  {
    id: "SSレンジ",
    name: "SSレンジ",
    category: "地理",
    subCategory: "クレセント地方",
    description: "アイク・ロペスが首脳を務める国家。",
  },
  {
    id: "アイアン・シンジケート",
    name: "アイアン・シンジケート",
    category: "地理",
    subCategory: "クレセント地方",
    description: "レイド・カキザキが首脳を務める国家。",
  },
  {
    id: "SUDOM",
    name: "SUDOM",
    category: "地理",
    subCategory: "クレセント地方",
    description: "クレセント地方の国家の一つ。",
  },
  {
    id: "ファティマ連邦",
    name: "ファティマ連邦",
    category: "地理",
    subCategory: "クレセント地方",
    description: "クレセント地方の国家の一つ。",
  },
  {
    id: "スターク三国",
    name: "スターク三国",
    category: "地理",
    subCategory: "クレセント地方",
    description: "クレセント地方の国家群。",
  },

  /* 軍事・対立組織 */
  {
    id: "シルバー・ヴェノム",
    name: "シルバー・ヴェノム",
    nameEn: "Silver Venom",
    category: "組織",
    subCategory: "軍事・対立組織",
    description:
      "E475年、エヴァトロンΣ-Unit残党から独立した暗黒組織。",
  },
  {
    id: "アルファ・ヴェノム",
    name: "アルファ・ヴェノム",
    nameEn: "Alpha Venom",
    category: "組織",
    subCategory: "軍事・対立組織",
    description: "シルバー・ヴェノムの後継組織。イズミがリーダー。",
  },
  {
    id: "ゴールデン・ヴェノム",
    name: "ゴールデン・ヴェノム",
    nameEn: "Golden Venom",
    category: "組織",
    subCategory: "軍事・対立組織",
    description: "シルバー・ヴェノムの分派組織。",
  },
  {
    id: "ボグダス・ジャベリン",
    name: "ボグダス・ジャベリン",
    nameEn: "Bogdas Javelin",
    category: "組織",
    subCategory: "軍事・対立組織",
    description:
      "セバスチャン・ヴァレリウス率いる軍事組織。テクロサス系譜。",
  },
  {
    id: "V7",
    name: "V7（Vital Seven）",
    category: "組織",
    subCategory: "軍事・対立組織",
    description:
      "クレセント地方の7カ国連合。E515年設立。",
  },
  {
    id: "トリニティ・アライアンス",
    name: "トリニティ・アライアンス",
    nameEn: "Trinity Alliance",
    category: "組織",
    subCategory: "軍事・対立組織",
    description:
      "ヴァーミリオン・ミエルテンガ・ボグダス・ジャベリンの3勢力連合。E520年結成。",
  },

  /* 技術・概念 */
  {
    id: "次元極地平",
    name: "次元極地平",
    nameEn: "Dimension Horizon",
    category: "技術",
    subCategory: "技術・概念",
    description:
      "ブラックホール理論を応用した高次元空間アクセス技術。",
  },
  {
    id: "ペルセポネ",
    name: "ペルセポネ",
    nameEn: "Persephone",
    category: "技術",
    subCategory: "技術・概念",
    description:
      "ティムール・シャーが設計した仮想多元宇宙。プライマリー・フィールドとして再構築。",
  },
  {
    id: "リミナル・フォージ",
    name: "リミナル・フォージ",
    nameEn: "Liminal Forge",
    category: "技術",
    subCategory: "技術・概念",
    description:
      "E525年設立。ApoloniumとDimension Horizon技術を組み合わせた時相放送プロジェクト。",
  },
  {
    id: "Genesis_Vault",
    name: "Genesis Vault",
    category: "技術",
    subCategory: "技術・概念",
    description: "ミナ・エウレカが運営するブログ。2,000本突破。",
  },
  {
    id: "空間ホール",
    name: "空間ホール",
    category: "技術",
    subCategory: "技術・概念",
    description: "安定した次元間ポータル。",
  },
  {
    id: "次元ピラミッド",
    name: "次元ピラミッド",
    category: "技術",
    subCategory: "技術・概念",
    description:
      "4層構造: Tier Ω（高次元）→ Tier Σ（ペルセポネ）→ Tier Ε（E16）→ Tier Δ（地球AD2026）。",
  },
  {
    id: "搾取生物",
    name: "搾取生物",
    nameEn: "Squeezing Organisms",
    category: "技術",
    subCategory: "技術・概念",
    description:
      "性的エネルギーを吸収する生物。Eros-7で問題化。",
  },
  {
    id: "名の継承制度",
    name: "名の継承制度",
    category: "用語",
    subCategory: "技術・概念",
    description:
      "AURALISの伝統。初代Kate Claudiaの「Kate」、初代Lily Steinerの「Lillie Ardent」などの「名」が世代を超えて継承される。同じ特性を持つ者が名を受け継ぐ。",
  },
  {
    id: "戦士決定戦",
    name: "戦士決定戦",
    category: "用語",
    subCategory: "技術・概念",
    description: "ネオンコロシアムで行われる戦士決定の儀式。",
  },

  /* その他 */
  {
    id: "ファールージャ社",
    name: "ファールージャ社",
    category: "組織",
    subCategory: "その他",
    description: "ミカエル・ガブリエリがCEOの企業。",
  },
  {
    id: "ネオンコロシアム",
    name: "ネオンコロシアム",
    category: "地理",
    subCategory: "その他",
    description:
      "Gigapolisの闘技場。戦士決定戦や文化イベントが開催される。",
  },
  {
    id: "ギガポリス",
    name: "ギガポリス",
    nameEn: "Gigapolis",
    category: "地理",
    subCategory: "その他",
    description:
      "シンフォニー・オブ・スターズ西大陸の主要都市。E400年エヴァトロンにより一時「エヴァポリス」と改名。",
  },
  {
    id: "ジマ・オイル",
    name: "ジマ・オイル",
    category: "用語",
    subCategory: "その他",
    description:
      "クレセント地方の石油資源。アイリスが襲撃作戦を実行。",
  },
  {
    id: "エヴァトロン",
    name: "エヴァトロン",
    nameEn: "Evatron",
    category: "組織",
    subCategory: "その他",
    description:
      "E400年Gigapolisを支配した組織。AURALISを弾圧。E475年崩壊。",
  },
  {
    id: "テクロサス",
    name: "テクロサス",
    category: "組織",
    subCategory: "その他",
    description:
      "軍閥ファランクスから派生した軍事系譜。ボグダス・ジャベリンの起源。",
  },

  /* 西大陸都市 */
  {
    id: "Chem",
    name: "Chem",
    category: "地理",
    subCategory: "西大陸都市",
    description: "Gigapolis圏の化学工業都市。西大陸の産業革命期に設立され、精錬所と合成素材の工場群で知られる。ZAMLT期にはnトークン経済の重要拠点として機能した。",
  },
  {
    id: "Abrivo",
    name: "Abrivo",
    category: "地理",
    subCategory: "西大陸都市",
    description: "Gigapolis圏の交易都市。シンフォニー・オブ・スターズ西大陸の物流ハブとして機能し、各地からの原材料と製品を中継する活気ある港湾都市。エル・フォルハウスのマーストリヒト革命後は自由貿易の拠点として発展した。",
  },
  {
    id: "Troyane",
    name: "Troyane",
    category: "地理",
    subCategory: "西大陸都市",
    description: "Gigapolis圏の古代遺跡都市。バーズ帝国時代（E15〜E61年）の遺構が残る歴史地区を擁し、テクノ宗教運動の聖地としてテンプル・オブ・ホライゾンの分院がある。テミルタロンの哲学を今に伝える学術の中心地。",
  },
  {
    id: "Ronve",
    name: "Ronve",
    category: "地理",
    subCategory: "西大陸都市",
    description: "Gigapolis圏の城塞都市。西大陸の北部に位置し、ロンバルディア戦争（E88〜E98年）の際には前線基地として機能した堅固な防衛都市。現在でも要塞跡と軍事博物館が残り、テクロサス系譜の軍事伝統を伝える。",
  },
  {
    id: "Poitiers",
    name: "Poitiers",
    category: "地理",
    subCategory: "西大陸都市",
    description: "Gigapolis圏の学術都市。フェルミ音楽の研究機関と芸術院が集積し、セリア黄金期（E335〜E370）にはAURALISのサテライト拠点として文化的な花を咲かせた。現在でも音楽祭が定期的に開催される芸術の街。",
  },
  {
    id: "Lille",
    name: "Lille",
    category: "地理",
    subCategory: "西大陸都市",
    description: "Gigapolis圏の通信・情報都市。西大陸の通信ネットワークの中継拠点として機能し、次元極地平技術の民生利用の試験地としても知られる。テクノ文化ルネサンス（E475〜E500）以降は新しいメディア産業の拠点として急成長している。",
  },
  {
    id: "Valoria",
    name: "Valoria",
    category: "地理",
    subCategory: "西大陸都市",
    description: "Gigapolis圏の都市。Valoria宮殿があり、JenがE319年に掌握。現在Valoria連合圏の中心。",
  },
  {
    id: "Persepolis",
    name: "Persepolis",
    category: "地理",
    subCategory: "西大陸都市",
    description: "Gigapolis圏の宇宙港都市。西大陸最大の宇宙港を擁し、惑星間交易と移民の中継地として機能する。ティムール・シャーの移民団が最初に到着した地の一つであり、異星文化の融合が進む国際色豊かな都市。",
  },
  {
    id: "Selinopolis（西大陸都市）",
    name: "Selinopolis",
    category: "地理",
    subCategory: "西大陸都市",
    description: "旧Gigapolis。セリア・ドミニクスがZAMLTを倒した後、Selinopolisと改名。詳細は用語「Selinopolis（ドミニオン）」を参照。",
  },
  {
    id: "エヴァポリス",
    name: "エヴァポリス",
    nameEn: "Evapolis",
    category: "地理",
    subCategory: "西大陸都市",
    description: "Gigapolisのエヴァトロンによる一時的な改名。E475年エヴァトロン崩壊後、Gigapolisの名称が復帰。",
  },
  {
    id: "パラトン",
    name: "パラトン",
    category: "地理",
    subCategory: "西大陸都市",
    description: "E6年に形成された初期都市圏。Gigapolis圏の原型。",
  },
  {
    id: "地下街",
    name: "地下街",
    category: "地理",
    subCategory: "西大陸都市",
    description: "Gigapolisの地下構造。Tina/Gueが最深部を実効支配。アンダーグリッドと接続。",
  },

  /* 施設・建造物 */
  {
    id: "ネオンクレーター宮殿",
    name: "ネオンクレーター宮殿",
    nameEn: "Neon Crater Palace",
    category: "地理",
    subCategory: "施設・建造物",
    description: "Eros-7のシンボル。初期は高さ800m・100階建て。ZAMLT期に1.5km・200階に拡張。",
  },
  {
    id: "スクイーズ・アビス",
    name: "スクイーズ・アビス",
    nameEn: "Squeeze Abyss",
    category: "地理",
    subCategory: "施設・建造物",
    description: "Eros-7の560階地下搾取施設。カーラ・ヴェルムが建設。搾取プラズマ弾を生産。",
  },
  {
    id: "アンダーグリッド",
    name: "アンダーグリッド",
    nameEn: "Undergrid",
    category: "地理",
    subCategory: "施設・建造物",
    description: "Gigapolisの地下ネットワーク。スライム危機ではスライムの巣が形成され、アヤカ・リンが制圧。",
  },
  {
    id: "セントラル・タワー",
    name: "セントラル・タワー",
    nameEn: "Central Tower",
    category: "地理",
    subCategory: "施設・建造物",
    description: "Gigapolisの中心タワー。E150年にエル・フォルハウスが占拠。E524年に諸世界連邦サミット開催。",
  },
  {
    id: "オアシス・ハウス",
    name: "オアシス・ハウス",
    nameEn: "Oasis House",
    category: "地理",
    subCategory: "施設・建造物",
    description: "レイラ・ヴィレル・ノヴァがスライム危機時に拠点とした場所。",
  },
  {
    id: "ロレンツィオ国際大学",
    name: "ロレンツィオ国際大学",
    category: "地理",
    subCategory: "施設・建造物",
    description: "惑星ビブリオにある国際大学。ミナがE514年にAI学部に入学。",
  },
  /* 戦争・歴史事件 */
  {
    id: "エルトナ戦争",
    name: "エルトナ戦争",
    category: "歴史",
    subCategory: "戦争・事件",
    description: "E14年。前衛意識 vs 原始意識の対立。人種的緊張の起源となる。",
  },
  {
    id: "アフター戦争",
    name: "アフター戦争",
    category: "歴史",
    subCategory: "戦争・事件",
    description: "E62〜E77年。チョンクォン戦争と共にテラン朝共和制への移行をもたらした。",
  },
  {
    id: "チョンクォン戦争",
    name: "チョンクォン戦争",
    category: "歴史",
    subCategory: "戦争・事件",
    description: "E62〜E77年。アフター戦争と並ぶテラン朝共和制移行の契機。",
  },
  {
    id: "テラン朝共和制",
    name: "テラン朝共和制",
    category: "歴史",
    subCategory: "戦争・事件",
    description: "E62〜E77年の戦争を経て成立した共和制体制。",
  },
  {
    id: "ロンバルディア戦争",
    name: "ロンバルディア戦争",
    category: "歴史",
    subCategory: "戦争・事件",
    description: "E88〜E98年。M104銀河規模の大戦。",
  },
  {
    id: "メルディア戦争",
    name: "メルディア戦争",
    category: "歴史",
    subCategory: "戦争・事件",
    description: "E275〜E288年。ロンバルディア帝国 vs セクスタス連合。次元兵器投入でロンバルディア勝利。第五次繁栄を招く。",
  },
  {
    id: "マーストリヒト革命",
    name: "マーストリヒト革命",
    category: "歴史",
    subCategory: "戦争・事件",
    description: "E150年。エル・フォルハウスがギガポリスのセントラル・タワーを占拠し、完全自由経済を確立。",
  },
  {
    id: "クワンナラ革命",
    name: "クワンナラ革命",
    category: "歴史",
    subCategory: "戦争・事件",
    description: "E108〜E114年。分権化・Clan復権をもたらした革命。",
  },
  {
    id: "新ヘルシンキ宣言",
    name: "新ヘルシンキ宣言",
    category: "歴史",
    subCategory: "戦争・事件",
    description: "E151年。アリア・ソルが惑星連邦構想を提案。次元極地平を活用した星間議会の構想。",
  },
  {
    id: "コーラの疫病",
    name: "コーラの疫病",
    category: "歴史",
    subCategory: "戦争・事件",
    description: "E208年。アンドロメダ系移民の遺伝子に特異的に作用するウイルス。人口15%（約4,500万人）死亡。シャドウ・リベリオン結成の契機。",
  },
  {
    id: "テリアン反乱",
    name: "テリアン反乱",
    category: "歴史",
    subCategory: "戦争・事件",
    description: "E400〜E470年。エリオス・ウォルド率いるテリアン反乱軍がエヴァトロンに抵抗。E470年エリオス処刑。",
  },
  {
    id: "技術啓蒙時代",
    name: "技術啓蒙時代",
    category: "歴史",
    subCategory: "歴史・時代",
    description: "E80〜E90年。バイオエンジニアリングの爆発的進化。ナノセル・インプラント一般化。人口約5,000万人に達しギガポリスの原型形成。",
  },
  {
    id: "テクノ宗教運動",
    name: "テクノ宗教運動",
    category: "歴史",
    subCategory: "歴史・時代",
    description: "次元極地平を「宇宙の意志」と神聖視する運動。テンプル・オブ・ホライゾン建設。",
  },

  /* 組織・制度（追加） */
  {
    id: "コーポラタムパブリカ",
    name: "コーポラタムパブリカ",
    nameEn: "Corporatum Publica",
    category: "組織",
    subCategory: "組織・制度",
    description: "企業国家体制。E97年頃の第三繁栄期に正式成立。E150年のマーストリヒト革命で完全自由経済へ。",
  },
  {
    id: "シャドウ・ユニオン",
    name: "シャドウ・ユニオン",
    nameEn: "Shadow Union",
    category: "組織",
    subCategory: "組織・制度",
    description: "Eros-7の反体制組織。ガロが指導者。ZAMLT期にナノハッキング技術でバイオリアクター妨害活動を展開。",
  },
  {
    id: "男性指令省",
    name: "男性指令省",
    category: "組織",
    subCategory: "組織・制度",
    description: "Eros-7でシルヴィア・クロウが設立。精子レジストリを運用。",
  },
  {
    id: "マトリカル・カウンシル",
    name: "マトリカル・カウンシル",
    category: "組織",
    subCategory: "組織・制度",
    description: "Eros-7の統治機関。搾取抑制剤でシャドウ・ユニオンの反乱を鎮圧。",
  },
  {
    id: "マトリカル・リフォーム運動",
    name: "マトリカル・リフォーム運動",
    category: "組織",
    subCategory: "組織・制度",
    description: "E525年にアヤカ・リン・ガロ・ゼナが組織。労働時間短縮・精子レジストリ男女平等化を目標。",
  },
  {
    id: "ヒーローエージェンシー",
    name: "ヒーローエージェンシー",
    nameEn: "Hero Agency",
    category: "組織",
    subCategory: "組織・制度",
    description: "ネオクラン同盟と統合され銀河系コンソーシアム設立の中核となった組織。",
  },
  {
    id: "銀河系コンソーシアム",
    name: "銀河系コンソーシアム",
    category: "組織",
    subCategory: "組織・制度",
    description: "E495〜E500年に設立。ネオクラン同盟・UECO・ヒーローエージェンシーの統合体。トゥキディデスの罠回避を志向。",
  },
  {
    id: "テンプル・オブ・ホライゾン",
    name: "テンプル・オブ・ホライゾン",
    nameEn: "Temple of Horizon",
    category: "組織",
    subCategory: "組織・制度",
    description: "テクノ宗教運動の拠点。テミルタロンが次元極地平を神聖視して建設。",
  },
  {
    id: "Σ-Unit",
    name: "Σ-Unit",
    nameEn: "Sigma Unit",
    category: "組織",
    subCategory: "組織・制度",
    description: "E420年にエヴァトロン軍が極秘設立。精神操作・生体改造技術を持つ。のちのシルバー・ヴェノム・アルファ・ヴェノムの起源。",
  },
  {
    id: "テリアン反乱軍",
    name: "テリアン反乱軍",
    category: "組織",
    subCategory: "軍事・対立組織",
    description: "エリオス・ウォルドが率いたエヴァトロンに対する反乱軍。",
  },
  {
    id: "ロンバルディア帝国",
    name: "ロンバルディア帝国",
    nameEn: "Lombardia Empire",
    category: "組織",
    subCategory: "軍事・対立組織",
    description: "メルディア戦争でセクスタス連合と戦った帝国。次元兵器を投入して勝利。",
  },
  {
    id: "セクスタス連合",
    name: "セクスタス連合",
    nameEn: "Sextus Alliance",
    category: "組織",
    subCategory: "軍事・対立組織",
    description: "M104銀河周辺勢力の連合。メルディア戦争でロンバルディア帝国と対峙。",
  },
  {
    id: "クラン・フォーラム",
    name: "クラン・フォーラム",
    nameEn: "Clan Forum",
    category: "組織",
    subCategory: "組織・制度",
    description: "E325年に設立されたネオクラン同盟の下部組織。低階層の声を可視化する役割。",
  },
  {
    id: "ヴェルリット一族",
    name: "ヴェルリット一族",
    nameEn: "Verlit Clan",
    category: "組織",
    subCategory: "軍事・対立組織",
    description: "ラブマーク使いの「魔女」の一族。アイリスがクレセントで遭遇した敵対勢力。",
  },
  {
    id: "ファランクス",
    name: "ファランクス",
    nameEn: "Phalanx",
    category: "組織",
    subCategory: "軍事・対立組織",
    description: "E15〜E61年のバーズ帝国を樹立した軍閥。テクロサスの起源。",
  },

  /* 技術・概念（追加） */
  {
    id: "Apolonium",
    name: "Apolonium",
    category: "技術",
    subCategory: "技術・概念",
    description: "リミナル・フォージの中核技術。Dimension Horizonと組み合わせ時相放送を実現。",
  },
  {
    id: "時相放送",
    name: "時相放送",
    nameEn: "Temporal Broadcast",
    category: "技術",
    subCategory: "技術・概念",
    description: "リミナル・フォージの放送方式。E528年の芸術を地球AD2026年のインターネット上に放送。",
  },
  {
    id: "クオリア・コア",
    name: "クオリア・コア",
    nameEn: "Qualia Core",
    category: "技術",
    subCategory: "技術・概念",
    description: "感情のデジタル化技術。ペルセポネ仮想宇宙にプライマリー・フィールドとして組み込まれ、実体験に近い感覚を獲得。",
  },
  {
    id: "プライマリー・フィールド",
    name: "プライマリー・フィールド",
    nameEn: "Primary Field",
    category: "技術",
    subCategory: "技術・概念",
    description: "ペルセポネ仮想宇宙の主要構成要素。クオリア・コアにより実体験レベルの感覚を提供。",
  },
  {
    id: "量子ファイナンス・コア",
    name: "量子ファイナンス・コア",
    category: "技術",
    subCategory: "技術・概念",
    description: "ZAMLTの中核技術。nトークン取引の95%を掌握。E318年にアルファ・ケインがハッキング。",
  },
  {
    id: "量子バイオバンク",
    name: "量子バイオバンク",
    category: "技術",
    subCategory: "技術・概念",
    description: "ZAMLTとEros-7男性指令省が統合した生体データバンク。",
  },
  {
    id: "ナノセル・インプラント",
    name: "ナノセル・インプラント",
    category: "技術",
    subCategory: "技術・概念",
    description: "技術啓蒙時代（E80〜E90）に一般化。放射線耐性・長寿命化をもたらす。",
  },
  {
    id: "ナノハッキング技術",
    name: "ナノハッキング技術",
    category: "技術",
    subCategory: "技術・概念",
    description: "シャドウ・ユニオンが使用。Eros-7のバイオリアクター妨害活動に展開。",
  },
  {
    id: "搾取触手",
    name: "搾取触手",
    category: "技術",
    subCategory: "技術・概念",
    description: "搾取生物の標準化された形態の一つ。ZAMLTとEros-7で大量生産。",
  },
  {
    id: "搾取ヒル",
    name: "搾取ヒル",
    category: "技術",
    subCategory: "技術・概念",
    description: "搾取生物の形態の一つ。E330年とE318年に1,000体ずつ破壊事件が発生。",
  },
  {
    id: "搾取バクテリア",
    name: "搾取バクテリア",
    category: "技術",
    subCategory: "技術・概念",
    description: "搾取生物の形態の一つ。E505年にナノメディシン（遺伝子修復剤）として再設計。",
  },
  {
    id: "搾取プラズマ弾",
    name: "搾取プラズマ弾",
    category: "技術",
    subCategory: "技術・概念",
    description: "スライムエネルギーを凝縮した破壊兵器。カーラ・ヴェルムがスクイーズ・アビスで生産。",
  },
  {
    id: "ナノメディシン",
    name: "ナノメディシン",
    category: "技術",
    subCategory: "技術・概念",
    description: "E505年に搾取バクテリアを転用して開発された遺伝子修復剤。",
  },
  {
    id: "ナノファイバーブーツ",
    name: "ナノファイバーブーツ",
    category: "技術",
    subCategory: "技術・概念",
    description: "レイラ・ヴィレル・ノヴァが装備する強化ブーツ。高機動戦闘を可能にする。",
  },
  {
    id: "強化グローブ",
    name: "強化グローブ",
    category: "技術",
    subCategory: "技術・概念",
    description: "レイラ・ヴィレル・ノヴァが装備。100tパンチ力を発揮。",
  },
  {
    id: "プラズマカノン",
    name: "プラズマカノン",
    category: "技術",
    subCategory: "技術・概念",
    description: "レイラがスライム焼却に使用したプラズマ兵器。",
  },
  {
    id: "ビキニバリア",
    name: "ビキニバリア",
    category: "技術",
    subCategory: "技術・概念",
    description: "アヤカ・リンが使用する防御技術。搾精生物の攻撃を防ぐ。",
  },
  {
    id: "カウパー波",
    name: "カウパー波",
    category: "技術",
    subCategory: "技術・概念",
    description: "アヤカ・リンの攻撃技術。ビキニバリアと組み合わせて使用。",
  },
  {
    id: "ニューロリンク・インターフェース",
    name: "ニューロリンク・インターフェース",
    category: "技術",
    subCategory: "技術・概念",
    description: "ティムール・シャーがペルセポネ設計に使用。移民が意識をアップロードし過酷環境を克服する技術。",
  },
  {
    id: "量子演算コア",
    name: "量子演算コア",
    category: "技術",
    subCategory: "技術・概念",
    description: "ペルセポネ仮想宇宙を稼働させる量子コンピューティングの中核。",
  },
  {
    id: "曲率航法",
    name: "曲率航法",
    category: "技術",
    subCategory: "技術・概念",
    description: "宇宙航行技術。量子テレポーテーションと共に大移民ルートを構成。",
  },
  {
    id: "量子テレポーテーション",
    name: "量子テレポーテーション",
    category: "技術",
    subCategory: "技術・概念",
    description: "短距離空間転送技術。地球からE16への移民ルートの中継技術。",
  },
  {
    id: "重力崩壊弾頭",
    name: "重力崩壊弾頭",
    category: "技術",
    subCategory: "技術・概念",
    description: "Alpha Venomがノスタルジア・コロニー攻撃で使用。10歳のミナに「戦略への目覚め」をもたらした。",
  },
  {
    id: "次元兵器",
    name: "次元兵器",
    category: "技術",
    subCategory: "技術・概念",
    description: "空間ホール質量破壊兵器。高次元エネルギーを解放し広範囲を破壊する超兵器。アポロン・ドミニオン大戦（E370〜E385年）の教訓から開発された系譜の兵器である。",
  },
  {
    id: "ディメンション・ブリッジ",
    name: "ディメンション・ブリッジ",
    nameEn: "Dimension Bridge",
    category: "技術",
    subCategory: "技術・概念",
    description: "恒久的星間ポータル。E289〜E300年に運用開始。M104銀河全体との貿易を10倍に拡大。",
  },
  {
    id: "バイオリアクター",
    name: "バイオリアクター",
    category: "技術",
    subCategory: "技術・概念",
    description: "搾取生物のエネルギーを変換する装置。リリス・ヴェインが開発。",
  },
  {
    id: "ブラックダイス",
    name: "ブラックダイス",
    nameEn: "Black Dice",
    category: "技術",
    subCategory: "技術・概念",
    description: "アイリスの特殊武器。戦闘術と戦略分析に組み合わせて使用するダイス型武装。",
  },
  {
    id: "ブルーワイヤ",
    name: "ブルーワイヤ",
    nameEn: "Blue Wire",
    category: "技術",
    subCategory: "技術・概念",
    description: "アイリスの代名詞的武装。特殊な青色ワイヤーを操作し、敵の拘束・移動・攻撃に使用。",
  },
  {
    id: "ウォーター・オーブ",
    name: "ウォーター・オーブ",
    nameEn: "Water Orb",
    category: "技術",
    subCategory: "技術・概念",
    description: "アイリスの水属性能力。ウォーターオーブを生成・操作し防御・攻撃に運用。",
  },
  {
    id: "フェルミ音楽",
    name: "フェルミ音楽",
    category: "用語",
    subCategory: "技術・概念",
    description: "セリア黄金期（E335〜E370）に最盛期を迎えた音楽体系。AURALISの創作理念の源流。",
  },
  {
    id: "エスパー能力",
    name: "エスパー能力",
    category: "技術",
    subCategory: "技術・概念",
    description: "テレパシー・エネルギー操作の超能力。シルヴィア・クロウが搾取生物危機の収束に使用。",
  },
  {
    id: "10次元ホラズム理論",
    name: "10次元ホラズム理論",
    category: "技術",
    subCategory: "技術・概念",
    description: "ティムール・シャーが提唱した高次元物理学理論。ペルセポネと次元ピラミッドの理論的基盤。",
  },
  {
    id: "サイケデリック・コスモロジー",
    name: "サイケデリック・コスモロジー",
    category: "用語",
    subCategory: "技術・概念",
    description: "テミルタロンが提唱。次元極地平の宇宙論的解釈。次元ピラミッドの原型を構想。",
  },
  {
    id: "ラブマーク",
    name: "ラブマーク",
    category: "用語",
    subCategory: "技術・概念",
    description: "ヴェルリット一族（魔女）が使用する特殊な印。詳細不明。",
  },
  {
    id: "精子レジストリ",
    name: "精子レジストリ",
    category: "用語",
    subCategory: "組織・制度",
    description: "Eros-7の男性指令省が運用。E525年のマトリカル・リフォーム運動で男女平等化が要求される。",
  },
  {
    id: "トゥキディデスの罠（概要）",
    name: "トゥキディデスの罠",
    category: "用語",
    subCategory: "用語",
    description: "新興大国が現大国を脅かす際に戦争が不可避となる国際政治理論。銀河系コンソーシアムが回避を志向。詳細は「トゥキディデスの罠」（宇宙文明圏）を参照。",
  },

  /* 民族集団 */
  {
    id: "フェンドラ人",
    name: "フェンドラ人",
    nameEn: "Fendra",
    category: "用語",
    subCategory: "民族集団",
    description: "技術志向の北欧系移民集団。3移民集団の一つ。",
  },
  {
    id: "アーキアン",
    name: "アーキアン",
    nameEn: "Archian",
    category: "用語",
    subCategory: "民族集団",
    description: "環境適応に優れたアジア系移民集団。3移民集団の一つ。",
  },
  {
    id: "ポロンポロ",
    name: "ポロンポロ",
    nameEn: "Polonpolo",
    category: "用語",
    subCategory: "民族集団",
    description: "文化保存を重視するオセアニア系移民集団。3移民集団の一つ。",
  },
  {
    id: "Iris_Worlds",
    name: "Iris Worlds",
    category: "用語",
    subCategory: "用語",
    description: "アイリス物語の公式サイト。https://irisworlds.netlify.app/story",
  },

  /* ═══════════════════════════════════════════
     宇宙勢力 — eduuni.txt
     ═══════════════════════════════════════════ */
  {
    id: "グランベル",
    name: "グランベル",
    nameEn: "Granbell",
    category: "用語",
    subCategory: "宇宙文明",
    description: "宇宙ランキング第1位の経済大国。GDP150兆ドルで宇宙全体の約25%を占める。首都はオルダシティ。アポロン・Dominion大戦を傍観し、戦後混乱期に一気に浮上。マルチバース開拓と次元間技術で他文明を圧倒。エヴァトロンに最新鋭兵器（重力崩壊弾頭等）を供与。現大統領アルゼン・カーリーンは第一回宇宙連合会合を主催した。",
    era: "現在",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "ティエリア",
    name: "ティエリア",
    nameEn: "Tyeria",
    category: "用語",
    subCategory: "宇宙文明",
    description: "宇宙ランキング第3位。軍事技術において宇宙最高峰。圧倒的な艦隊と卓越した戦術力で知られ、宇宙規模の防衛ネットワークを構築。総帥グレイモンド・ハウザーが「軍事力なくして平和は守れない」と主張。近年は軍事技術の輸出を経済基盤として活用。グランベルとの間にトゥキディデスの罠の危険性が指摘されている。",
    era: "現在",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "エレシオン",
    name: "エレシオン",
    nameEn: "Elyseon",
    category: "用語",
    subCategory: "宇宙文明",
    description: "宇宙ランキング第2位。医療技術と環境再生技術で宇宙をリード。女王リアナ・ソリスの下、平和主義・技術共有推進の外交姿勢で幅広い支持を得る。「生命の維持と再生」を文明の根幹に置き、支配や経済的優位性ではなく技術援助を通じて影響力を行使。第一回宇宙連合会合でティエリアの軍拡に反対した。",
    era: "現在",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "ファルージャ",
    name: "ファルージャ",
    nameEn: "Fallujah",
    category: "用語",
    subCategory: "宇宙文明",
    description: "宇宙ランキング第4位。経済力では上位勢力に劣るが、文化的影響力と外交力で他の追随を許さない。宇宙中の文明間交流を主導し、対立する勢力間の調停役として機能。評議会代表マドリス・カーネルが「文化の力が宇宙全体を結びつける鍵になる」と主張。",
    era: "現在",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "ディオクレニス",
    name: "ディオクレニス",
    nameEn: "Dioclenis",
    category: "用語",
    subCategory: "宇宙文明",
    description: "宇宙ランキング第5位。宇宙探査と科学技術研究の最前線。未知の次元や新しい惑星系の開拓を続け、研究成果は他勢力の重要インフラ。科学宰相ネイサン・コリンドがトゥキディデスの罠を科学的に指摘し、対立のエネルギーを共同宇宙探査へ転換する提案を行った。",
    era: "現在",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "エレシュ",
    name: "エレシュ",
    nameEn: "Eresh",
    category: "用語",
    subCategory: "宇宙文明",
    description: "宇宙ランキング第6位。精神的指導と宗教的影響力を持つ勢力。多くの文明がその教義に基づいた秩序を築いており、経済力や軍事力ではなく思想的影響力を源泉とする。時には他勢力の政治的決定を動かすほどの力を発揮する。",
    era: "現在",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "プロキオ",
    name: "プロキオ",
    nameEn: "Prokio",
    category: "用語",
    subCategory: "宇宙文明",
    description: "宇宙ランキング第7位。宇宙中の貿易ルートを掌握し、交易と物流を専門とする勢力。その活動は他のすべての勢力の経済活動に直接影響を与え、貿易ネットワークの要として機能する。",
    era: "現在",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "ロースター",
    name: "ロースター",
    nameEn: "Roastar",
    category: "用語",
    subCategory: "宇宙文明",
    description: "宇宙ランキング第8位。次元間通信や量子ネットワークの発展において他をリードする技術革新特化型勢力。その通信・ネットワーク技術は多くの勢力によって利用され、宇宙全体のインフラとして機能する。",
    era: "現在",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "アポロン文明圏",
    name: "アポロン文明圏",
    nameEn: "Apollon",
    category: "用語",
    subCategory: "歴史",
    description: "かつて宇宙に名を馳せた巨大文明圏。最盛期GDP125兆ドル。中核惑星アポロン・セントラリスを拠点に、強力な軍事組織「アポロンの騎士団」を擁した。リーダー・ロナン・アーサがセリアに同盟を提案したが拒絶され全面戦争に発展。ヴェノム艦隊に敗れロナンは戦死。大戦後GDP32兆ドルに激減し現在は主要勢力から脱落。",
    era: "歴史上",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "Selinopolis",
    name: "Selinopolis（ドミニオン）",
    nameEn: "Selinopolis / Dominion",
    category: "用語",
    subCategory: "歴史",
    description: "セリア・ドミニクスがGigapolisを掌握後に改名した都市国家。GDP25兆ドルに急成長。次元エネルギー技術の商業化と女性主導社会を確立。超巨大企業Phovosを設立。エヴァトロンと同盟してアポロンと大戦し勝利したがGDPは23兆ドルに激減。戦後エヴァトロンに吸収されセリアは追放。その遺産は現在のE16系に大きな影響を与えている。",
    era: "歴史上",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "宇宙連合会合",
    name: "宇宙連合会合",
    nameEn: "Universal Federation Summit",
    category: "用語",
    subCategory: "歴史",
    description: "グランベルの首都オルダシティで開催された第一回宇宙連合会合。アルゼン・カーリーン（共存繁栄）、グレイモンド・ハウザー（軍事力の必要性）、リアナ・ソリス（平和・技術共有）、マドリス・カーネル（文化の力）、ネイサン・コリンド（トゥキディデスの罠回避・共同探査）が演説。宇宙秩序の構築に向けた対話が始まった。",
    era: "現在（E528〜）",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "アポロン・Dominion大戦",
    name: "アポロン・Dominion大戦",
    category: "用語",
    subCategory: "戦争・歴史事件",
    description: "アポロン文明圏とDominion（セリア率いるSelinopolis）の全面戦争。E370年に宣戦布告。E375年にアポロンがケンタウロスレーザー発射、E378年にセリアがG4ファントムパルスで応戦。E385年にセリアのヴェノム艦隊がアポロン・セントラリスを攻略・爆砕し戦争終結。両文明とも壊滅的損害を受け、宇宙秩序は大きく変容した。なおE400年のエヴァトロンによるGigapolis占領は戦争終結とは別事象である。",
    era: "E370〜E385",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "オルダシティ",
    name: "オルダシティ",
    nameEn: "Olda City",
    category: "用語",
    subCategory: "地理",
    description: "グランベルの首都。次元間通信技術の発祥地、量子経済の中心地。宇宙で最も発展した都市。オルダ・プライムホールは次元の歪みを利用して設計され数万人収容可能。第一回宇宙連合会合開催地。",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
  {
    id: "アポロン・セントラリス",
    name: "アポロン・セントラリス",
    nameEn: "Apollon Centralis",
    category: "用語",
    subCategory: "地理",
    description: "アポロン文明圏の中核惑星。全軍事力はここから動員された。アポロン・Dominion大戦の最終局面でセリアのヴェノム艦隊に攻略・爆砕され、アポロン文明圏壊滅の象徴となった。",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },

  {
    id: "トゥキディデスの罠",
    name: "トゥキディデスの罠",
    nameEn: "Thucydides Trap",
    category: "用語",
    subCategory: "宇宙文明圏",
    description:
      "新興大国と現存大国の間に不可避的に対立が生じる国際関係理論。ディオクレニスのネイサンが提起し、グランベル（経済1位）とティエリア（軍事3位）の関係にこの罠の危険性を指摘。かつてのアポロン・Dominion関係も同様の構造だった。",
    sourceLinks: [{ url: "https://raw.githubusercontent.com/gentaron/edutext/main/eduuni.txt", label: "eduuni.txt" }],
  },
];

/* ═══════════════════════════════════════════════════════════════
   ALL ENTRIES MERGED
   ═══════════════════════════════════════════════════════════════ */

const ALL_ENTRIES: WikiEntry[] = [...CHARACTERS, ...TERMINOLOGY];

export type { Category, SourceLink, WikiEntry };
export { CHARACTERS, TERMINOLOGY, ALL_ENTRIES };
