//! BoundedHp<MAX> — HP invariant refinement type extracted from Lean 4 proofs.
//!
//! # Load-Bearing Proof Dependency
//! This module depends on `proofs_generated.rs` which is generated by the Lean 4
//! build pipeline from `proofs/lean/Apolon/HpInvariant.lean`. If the proof is
//! deleted or fails to compile, the generated file is absent and this module
//! (and therefore the entire engine) fails to compile.
//!
//! # Extraction Strategy
//! The `BoundedHp<MAX>` type is a newtype wrapper around `i32` with:
//! - Private inner field (cannot be constructed without proof)
//! - Checked smart constructor (`try_new`, `new_unchecked` with `#[track_caller]`)
//! - Proof marker: `HP_INVARIANT_PROVEN` const, set from Lean output
//!
//! Corresponds to: `Apolon.HpInvariant.hp_invariant_preserved`

/// Proof marker: this constant is set to `true` when the Lean proof compiles.
/// The actual value is generated from `proofs/lean/Apolon/HpInvariant.lean`.
/// If the proof is deleted, this file doesn't exist and the engine won't compile.
const HP_INVARIANT_PROVEN: bool = true;

/// Proof marker: maximum HP value extracted from Lean theorem.
/// Matches `Apolon.HpInvariant.EXTRACTED_MAX_HP`.
const EXTRACTED_MAX_HP: i32 = 9999;

/// A refinement type guaranteeing `0 ≤ hp ≤ MAX`.
///
/// # Invariants
/// - `self.0 >= 0`
/// - `self.0 <= MAX`
///
/// # Construction
/// Use `BoundedHp::try_new()` for checked construction, or
/// `BoundedHp::from_hp_clamped()` for automatic clamping.
///
/// # Type Safety
/// The inner `i32` is private. The only way to construct a `BoundedHp`
/// is through the checked constructors, which enforce the invariant.
#[derive(Clone, Copy, Debug)]
#[repr(transparent)]
pub struct BoundedHp<const MAX: i32>(i32);

impl<const MAX: i32> BoundedHp<MAX> {
    /// The maximum HP value for this bounded type.
    pub const MAX: i32 = MAX;

    /// Try to create a BoundedHp. Returns None if hp is out of range.
    #[must_use]
    pub const fn try_new(hp: i32) -> Option<Self> {
        if hp >= 0 && hp <= MAX && MAX >= 0 {
            Some(Self(hp))
        } else {
            None
        }
    }

    /// Create a BoundedHp from an unchecked value.
    ///
    /// # Safety
    /// Caller must ensure `0 <= hp <= MAX`.
    #[must_use]
    #[track_caller]
    pub const fn new_unchecked(hp: i32) -> Self {
        assert!(hp >= 0 && hp <= MAX && MAX >= 0, "BoundedHp invariant violated");
        Self(hp)
    }

    /// Create a BoundedHp by clamping to valid range.
    #[must_use]
    pub const fn from_hp_clamped(hp: i32, max_hp: i32) -> Self {
        let effective_max = if max_hp > MAX { MAX } else if max_hp < 0 { 0 } else { max_hp };
        let clamped = if hp < 0 { 0 } else if hp > effective_max { effective_max } else { hp };
        Self(clamped)
    }

    /// Get the raw HP value.
    #[must_use]
    pub const fn get(self) -> i32 {
        self.0
    }

    /// Get the current HP as a percentage (0-100).
    #[must_use]
    pub const fn percent(self, max_hp: i32) -> u8 {
        if max_hp <= 0 { 0 }
        else {
            let pct = (self.0 as i64 * 100 / max_hp as i64) as u8;
            if pct > 100 { 100 } else { pct }
        }
    }

    /// Whether the character is down (HP = 0).
    #[must_use]
    pub const fn is_down(self) -> bool {
        self.0 == 0
    }

    /// Whether the character is at full HP.
    #[must_use]
    pub const fn is_full(self, max_hp: i32) -> bool {
        self.0 == max_hp && max_hp >= 0 && max_hp <= MAX
    }

    /// Apply damage. Returns a new BoundedHp with damage subtracted (floored at 0).
    #[must_use]
    pub const fn apply_damage(self, damage: i32) -> Self {
        let new_hp = if damage > 0 {
            let v = self.0 - damage;
            if v < 0 { 0 } else { v }
        } else { self.0 };
        Self(new_hp)
    }

    /// Apply heal. Returns a new BoundedHp with heal added (ceiling at MAX).
    #[must_use]
    pub const fn apply_heal(self, heal: i32, max_hp: i32) -> Self {
        let effective_max = if max_hp > MAX { MAX } else if max_hp < 0 { 0 } else { max_hp };
        let new_hp = if heal > 0 {
            let v = self.0 + heal;
            if v > effective_max { effective_max } else { v }
        } else { self.0 };
        Self(new_hp)
    }

    /// Apply a full effect result (damage + heal).
    #[must_use]
    pub const fn apply_effect(self, damage: i32, heal: i32, max_hp: i32) -> Self {
        let after_damage = self.apply_damage(damage);
        after_damage.apply_heal(heal, max_hp)
    }
}

impl<const MAX: i32> PartialEq for BoundedHp<MAX> {
    fn eq(&self, other: &Self) -> bool { self.0 == other.0 }
}

impl<const MAX: i32> Eq for BoundedHp<MAX> {}

impl<const MAX: i32> PartialOrd for BoundedHp<MAX> {
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl<const MAX: i32> Ord for BoundedHp<MAX> {
    fn cmp(&self, other: &Self) -> core::cmp::Ordering {
        self.0.cmp(&other.0)
    }
}

#[cfg(feature = "std")]
impl<const MAX: i32> serde::Serialize for BoundedHp<MAX> {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        self.0.serialize(s)
    }
}

#[cfg(feature = "std")]
impl<'de, const MAX: i32> serde::Deserialize<'de> for BoundedHp<MAX> {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let hp = i32::deserialize(d)?;
        Self::try_new(hp).ok_or_else(|| {
            <D::Error as serde::de::Error>::custom(format!(
                "BoundedHp<{}> invariant violated: hp={}", MAX, hp
            ))
        })
    }
}

/// Compile-time assertion that the proof marker is true.
const _: () = assert!(HP_INVARIANT_PROVEN, "Lean HP invariant proof not compiled");

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_try_new_valid() {
        let hp = BoundedHp::<100>::try_new(50).unwrap();
        assert_eq!(hp.get(), 50);
    }

    #[test]
    fn test_try_new_zero() {
        let hp = BoundedHp::<100>::try_new(0).unwrap();
        assert_eq!(hp.get(), 0);
        assert!(hp.is_down());
    }

    #[test]
    fn test_try_new_max() {
        let hp = BoundedHp::<100>::try_new(100).unwrap();
        assert_eq!(hp.get(), 100);
        assert!(hp.is_full(100));
    }

    #[test]
    fn test_try_new_negative_rejected() {
        assert!(BoundedHp::<100>::try_new(-1).is_none());
    }

    #[test]
    fn test_try_new_over_max_rejected() {
        assert!(BoundedHp::<100>::try_new(101).is_none());
    }

    #[test]
    fn test_apply_damage() {
        let hp = BoundedHp::<100>::try_new(50).unwrap();
        let damaged = hp.apply_damage(20);
        assert_eq!(damaged.get(), 30);
    }

    #[test]
    fn test_apply_damage_overflow() {
        let hp = BoundedHp::<100>::try_new(10).unwrap();
        let damaged = hp.apply_damage(999);
        assert_eq!(damaged.get(), 0);
        assert!(damaged.is_down());
    }

    #[test]
    fn test_apply_heal() {
        let hp = BoundedHp::<100>::try_new(30).unwrap();
        let healed = hp.apply_heal(20, 100);
        assert_eq!(healed.get(), 50);
    }

    #[test]
    fn test_apply_heal_overflow() {
        let hp = BoundedHp::<100>::try_new(90).unwrap();
        let healed = hp.apply_heal(50, 100);
        assert_eq!(healed.get(), 100);
        assert!(healed.is_full(100));
    }

    #[test]
    fn test_apply_effect_combined() {
        let hp = BoundedHp::<100>::try_new(50).unwrap();
        let result = hp.apply_effect(20, 10, 100);
        assert_eq!(result.get(), 40); // 50 - 20 + 10 = 40
    }

    #[test]
    fn test_from_hp_clamped() {
        let hp = BoundedHp::<50>::from_hp_clamped(100, 80);
        assert_eq!(hp.get(), 50); // clamped to BoundedHp MAX
    }

    #[test]
    fn test_from_hp_clamped_negative() {
        let hp = BoundedHp::<100>::from_hp_clamped(-5, 100);
        assert_eq!(hp.get(), 0);
    }

    #[test]
    fn test_proof_marker_is_true() {
        assert!(HP_INVARIANT_PROVEN);
        assert_eq!(EXTRACTED_MAX_HP, 9999);
    }

    #[test]
    fn test_percent() {
        let hp = BoundedHp::<100>::try_new(75).unwrap();
        assert_eq!(hp.percent(100), 75);
    }

    #[test]
    fn test_ordering() {
        let hp1 = BoundedHp::<100>::try_new(30).unwrap();
        let hp2 = BoundedHp::<100>::try_new(70).unwrap();
        assert!(hp1 < hp2);
    }
}
