import type { Enemy } from "@/types"

/* ═══════════════════════════════════════════════════════
   10体のエネミー
   ═══════════════════════════════════════════════════════ */
export const ENEMIES: Enemy[] = [
  /* ── NORMAL ×4 ── */
  {
    id: "stardust-dragon",
    name: "スターダスト・ドラゴン",
    title: "星屑の守護者",
    maxHp: 28,
    attackPower: 4,
    imageUrl: "/logo.svg",
    description: "E16連星系の深部に棲む古代竜。星屑を纏い、その息吹は小惑星を灰に変える。",
    difficulty: "NORMAL",
    reward: "星屑の鱗を入手",
    phases: [{ triggerHpPercent: 50, message: "翼を広げ炎を吐く！", attackBonus: 2 }],
  },
  {
    id: "phantom-walker",
    name: "霊体ウォーカー",
    title: "彷徨える亡者",
    maxHp: 22,
    attackPower: 3,
    imageUrl: "/logo.svg",
    description: "次元境界を彷徨う幽霊のような存在。実体を持たず、傷ついても自ら再生する。",
    difficulty: "NORMAL",
    reward: "霊体の核を入手",
    phases: [
      {
        triggerHpPercent: 40,
        message: "霊体が揺らめく…",
        attackBonus: 1,
        selfHealPerTurn: 2,
      },
    ],
    specialRule: "HP40%以下から毎ターン2回復する",
  },
  {
    id: "iron-golem",
    name: "鉄塊ゴーレム",
    title: "廃工場の番人",
    maxHp: 35,
    attackPower: 5,
    imageUrl: "/logo.svg",
    description: "放棄された軍事工場で自動稼働する巨大な機械番人。装甲はどんな攻撃も弾く。",
    difficulty: "NORMAL",
    reward: "精製鉄塊を入手",
    phases: [{ triggerHpPercent: 60, message: "装甲が赤く焼ける！", attackBonus: 3 }],
    specialRule: "防御能力の効果が半減する（シールド値÷2）",
  },
  {
    id: "venom-hydra",
    name: "毒沼ヒュドラ",
    title: "沼地の多頭竜",
    maxHp: 30,
    attackPower: 3,
    imageUrl: "/logo.svg",
    description: "瘴気に満ちた沼に潜む多頭の竜。首を斬っても再生し、毒で敵を蝕む。",
    difficulty: "NORMAL",
    reward: "毒腺エキスを入手",
    phases: [
      { triggerHpPercent: 66, message: "首が1本再生した！", attackBonus: 1 },
      { triggerHpPercent: 33, message: "さらに首が増える！", attackBonus: 2 },
    ],
    specialRule: "毎ターン終了時プレイヤーに1毒ダメージ",
  },
  /* ── HARD ×3 ── */
  {
    id: "frost-guardian",
    name: "氷獄の守護者",
    title: "絶対零度の鎧",
    maxHp: 42,
    attackPower: 5,
    imageUrl: "/logo.svg",
    description: "永久凍土の最深部で眠る氷の巨人。その鎧は絶対零度の冷気で硬化している。",
    difficulty: "HARD",
    reward: "永久凍土の結晶を入手",
    phases: [
      {
        triggerHpPercent: 50,
        message: "氷の鎧が砕け…本体が現れた！",
        attackBonus: 4,
      },
    ],
    specialRule: "バトル開始時味方全体に1ダメージ。防御能力の効果が半減する（シールド値÷2）",
  },
  {
    id: "flame-spirit",
    name: "炎の精霊王",
    title: "業火の化身",
    maxHp: 36,
    attackPower: 7,
    imageUrl: "/logo.svg",
    description: "太古の火山に宿る炎の精霊。その熱量は防壁すら溶かし、近づく者を灰に変える。",
    difficulty: "HARD",
    reward: "業火の核石を入手",
    phases: [
      { triggerHpPercent: 70, message: "炎が激しくなる！", attackBonus: 2 },
      { triggerHpPercent: 30, message: "核爆発！", attackBonus: 4 },
    ],
    specialRule: "防御能力を使うたびに自分が1ダメージ",
  },
  {
    id: "void-spider",
    name: "深淵の大蜘蛛",
    title: "虚無の糸使い",
    maxHp: 45,
    attackPower: 4,
    imageUrl: "/logo.svg",
    description: "次元の裂け目に巣食う巨大蜘蛛。透明な糸で獲物を縛り上げ、動きを封じる。",
    difficulty: "HARD",
    reward: "次元の糸を入手",
    phases: [{ triggerHpPercent: 45, message: "捕縛糸を放つ！", attackBonus: 2 }],
    specialRule: "偶数ターンはプレイヤーが防御能力を使用できない",
  },
  /* ── BOSS ×2 ── */
  {
    id: "fallen-angel",
    name: "堕落した天使",
    title: "翼なき裁判者",
    maxHp: 65,
    attackPower: 8,
    imageUrl: "/logo.svg",
    description:
      "かつてAURALISの守護天使だったが、次元崩壊に巻き込まれ堕天した。3段階の怒りを持つ。",
    difficulty: "BOSS",
    reward: "堕天の羽根を入手",
    phases: [
      {
        triggerHpPercent: 66,
        message: "神の怒りを解放する！",
        attackBonus: 2,
      },
      {
        triggerHpPercent: 33,
        message: "最後の審判…！",
        attackBonus: 4,
        selfHealPerTurn: 3,
      },
    ],
    specialRule: "HP33%以下から毎ターン3回復＋攻撃力+4",
  },
  {
    id: "void-reaper",
    name: "ヴォイドリーパー",
    title: "時空の刈り手",
    maxHp: 75,
    attackPower: 9,
    imageUrl: "/logo.svg",
    description: "虚無から現れ、存在そのものを刈り取る死神。3フェーズの力で時空を歪める。",
    difficulty: "BOSS",
    reward: "虚無の鎌を入手",
    phases: [
      { triggerHpPercent: 75, message: "時空が歪む…", attackBonus: 1 },
      { triggerHpPercent: 50, message: "次元切断！", attackBonus: 3 },
      { triggerHpPercent: 25, message: "存在が消えていく…", attackBonus: 5 },
    ],
    specialRule: "フェーズ移行時プレイヤーに3ダメージ",
  },
  /* ── FINAL ×1 ── */
  {
    id: "void-king",
    name: "虚無の王",
    title: "終焉の支配者",
    maxHp: 100,
    attackPower: 11,
    imageUrl: "/logo.svg",
    description:
      "全ての虚無の根源。宇宙の終わりを体現する存在。必殺能力のみが最終フェーズを突破できる。",
    difficulty: "FINAL",
    reward: "虚無の王冠を入手。全クリア達成！",
    phases: [
      { triggerHpPercent: 80, message: "宇宙が震える…", attackBonus: 2 },
      { triggerHpPercent: 55, message: "虚無の爆発！", attackBonus: 4 },
      {
        triggerHpPercent: 30,
        message: "終焉の意志…！",
        attackBonus: 6,
        selfHealPerTurn: 5,
      },
    ],
    specialRule: "HP30%以下から毎ターン5回復。必殺能力のみが最終フェーズを突破できる",
  },
]
