import type { EnemyId, Enemy } from "@/types"

/* ═══════════════════════════════════════════════════════
   10体のエネミー
   ═══════════════════════════════════════════════════════ */
export const ENEMIES = [
  /* ── NORMAL ×4 ── */
  {
    id: "stardust-dragon" as EnemyId,
    name: "スターダスト・ドラゴン",
    nameEn: "Stardust Dragon",
    title: "星屑の守護者",
    titleEn: "Guardian of Stardust",
    maxHp: 28,
    attackPower: 4,
    imageUrl: "/logo.svg",
    description: "E16連星系の深部に棲む古代竜。星屑を纏い、その息吹は小惑星を灰に変える。",
    descriptionEn:
      "An ancient dragon dwelling in the depths of the E16 star cluster. Cloaked in stardust, its breath turns asteroids to ash.",
    difficulty: "NORMAL",
    reward: "星屑の鱗を入手",
    rewardEn: "Obtained Stardust Scale",
    phases: [
      {
        triggerHpPercent: 50,
        message: "翼を広げ炎を吐く！",
        messageEn: "It spreads its wings and breathes fire!",
        attackBonus: 2,
      },
    ],
  },
  {
    id: "phantom-walker" as EnemyId,
    name: "霊体ウォーカー",
    nameEn: "Phantom Walker",
    title: "彷徨える亡者",
    titleEn: "Wandering Wraith",
    maxHp: 22,
    attackPower: 3,
    imageUrl: "/logo.svg",
    description: "次元境界を彷徨う幽霊のような存在。実体を持たず、傷ついても自ら再生する。",
    descriptionEn:
      "A ghost-like entity wandering the dimensional boundary. Lacks physical form and regenerates when wounded.",
    difficulty: "NORMAL",
    reward: "霊体の核を入手",
    rewardEn: "Obtained Phantom Core",
    phases: [
      {
        triggerHpPercent: 40,
        message: "霊体が揺らめく…",
        messageEn: "The phantom flickers…",
        attackBonus: 1,
        selfHealPerTurn: 2,
      },
    ],
    specialRule: "HP40%以下から毎ターン2回復する",
  },
  {
    id: "iron-golem" as EnemyId,
    name: "鉄塊ゴーレム",
    nameEn: "Iron Golem",
    title: "廃工場の番人",
    titleEn: "Keeper of the Abandoned Factory",
    maxHp: 35,
    attackPower: 5,
    imageUrl: "/logo.svg",
    description: "放棄された軍事工場で自動稼働する巨大な機械番人。装甲はどんな攻撃も弾く。",
    descriptionEn:
      "A colossal mechanical sentinel that runs automatically in an abandoned military factory. Its armor deflects any attack.",
    difficulty: "NORMAL",
    reward: "精製鉄塊を入手",
    rewardEn: "Obtained Refined Iron Block",
    phases: [
      {
        triggerHpPercent: 60,
        message: "装甲が赤く焼ける！",
        messageEn: "Its armor glows red-hot!",
        attackBonus: 3,
      },
    ],
    specialRule: "防御能力の効果が半減する（シールド値÷2）",
  },
  {
    id: "venom-hydra" as EnemyId,
    name: "毒沼ヒュドラ",
    nameEn: "Venom Hydra",
    title: "沼地の多頭竜",
    titleEn: "Multi-Headed Dragon of the Swamp",
    maxHp: 30,
    attackPower: 3,
    imageUrl: "/logo.svg",
    description: "瘴気に満ちた沼に潜む多頭の竜。首を斬っても再生し、毒で敵を蝕む。",
    descriptionEn:
      "A multi-headed dragon lurking in a miasma-filled swamp. Heads regenerate when severed, and its venom corrodes enemies.",
    difficulty: "NORMAL",
    reward: "毒腺エキスを入手",
    rewardEn: "Obtained Venom Gland Extract",
    phases: [
      {
        triggerHpPercent: 66,
        message: "首が1本再生した！",
        messageEn: "One head has regenerated!",
        attackBonus: 1,
      },
      {
        triggerHpPercent: 33,
        message: "さらに首が増える！",
        messageEn: "Even more heads appear!",
        attackBonus: 2,
      },
    ],
    specialRule: "毎ターン終了時プレイヤーに1毒ダメージ",
  },
  /* ── HARD ×3 ── */
  {
    id: "frost-guardian" as EnemyId,
    name: "氷獄の守護者",
    nameEn: "Frost Guardian",
    title: "絶対零度の鎧",
    titleEn: "Armor of Absolute Zero",
    maxHp: 42,
    attackPower: 5,
    imageUrl: "/logo.svg",
    description: "永久凍土の最深部で眠る氷の巨人。その鎧は絶対零度の冷気で硬化している。",
    descriptionEn:
      "A frost giant sleeping in the deepest permafrost. Its armor is hardened by the cold of absolute zero.",
    difficulty: "HARD",
    reward: "永久凍土の結晶を入手",
    rewardEn: "Obtained Permafrost Crystal",
    phases: [
      {
        triggerHpPercent: 50,
        message: "氷の鎧が砕け…本体が現れた！",
        messageEn: "The ice armor shatters… the true body emerges!",
        attackBonus: 4,
      },
    ],
    specialRule: "バトル開始時味方全体に1ダメージ。防御能力の効果が半減する（シールド値÷2）",
  },
  {
    id: "flame-spirit" as EnemyId,
    name: "炎の精霊王",
    nameEn: "Flame Spirit King",
    title: "業火の化身",
    titleEn: "Incarnation of Hellfire",
    maxHp: 36,
    attackPower: 7,
    imageUrl: "/logo.svg",
    description: "太古の火山に宿る炎の精霊。その熱量は防壁すら溶かし、近づく者を灰に変える。",
    descriptionEn:
      "A fire spirit inhabiting an ancient volcano. Its heat melts even barriers, turning all who approach to ash.",
    difficulty: "HARD",
    reward: "業火の核石を入手",
    rewardEn: "Obtained Hellfire Core Stone",
    phases: [
      {
        triggerHpPercent: 70,
        message: "炎が激しくなる！",
        messageEn: "The flames intensify!",
        attackBonus: 2,
      },
      { triggerHpPercent: 30, message: "核爆発！", messageEn: "Core explosion!", attackBonus: 4 },
    ],
    specialRule: "防御能力を使うたびに自分が1ダメージ",
  },
  {
    id: "void-spider" as EnemyId,
    name: "深淵の大蜘蛛",
    nameEn: "Abyss Spider",
    title: "虚無の糸使い",
    titleEn: "Weaver of the Void",
    maxHp: 45,
    attackPower: 4,
    imageUrl: "/logo.svg",
    description: "次元の裂け目に巣食う巨大蜘蛛。透明な糸で獲物を縛り上げ、動きを封じる。",
    descriptionEn:
      "A colossal spider nesting in dimensional rifts. It binds prey with invisible threads, sealing their movement.",
    difficulty: "HARD",
    reward: "次元の糸を入手",
    rewardEn: "Obtained Dimensional Thread",
    phases: [
      {
        triggerHpPercent: 45,
        message: "捕縛糸を放つ！",
        messageEn: "It fires binding threads!",
        attackBonus: 2,
      },
    ],
    specialRule: "偶数ターンはプレイヤーが防御能力を使用できない",
  },
  /* ── BOSS ×2 ── */
  {
    id: "fallen-angel" as EnemyId,
    name: "堕落した天使",
    nameEn: "Fallen Angel",
    title: "翼なき裁判者",
    titleEn: "The Wingless Judge",
    maxHp: 65,
    attackPower: 8,
    imageUrl: "/logo.svg",
    description:
      "かつてAURALISの守護天使だったが、次元崩壊に巻き込まれ堕天した。3段階の怒りを持つ。",
    descriptionEn:
      "Once a guardian angel of AURALIS, she fell from grace after being caught in a dimensional collapse. Possesses three stages of wrath.",
    difficulty: "BOSS",
    reward: "堕天の羽根を入手",
    rewardEn: "Obtained Fallen Feather",
    phases: [
      {
        triggerHpPercent: 66,
        message: "神の怒りを解放する！",
        messageEn: "Divine wrath unleashed!",
        attackBonus: 2,
      },
      {
        triggerHpPercent: 33,
        message: "最後の審判…！",
        messageEn: "The Final Judgment…!",
        attackBonus: 4,
        selfHealPerTurn: 3,
      },
    ],
    specialRule: "HP33%以下から毎ターン3回復＋攻撃力+4",
  },
  {
    id: "void-reaper" as EnemyId,
    name: "ヴォイドリーパー",
    nameEn: "Void Reaper",
    title: "時空の刈り手",
    titleEn: "Reaper of Spacetime",
    maxHp: 75,
    attackPower: 9,
    imageUrl: "/logo.svg",
    description: "虚無から現れ、存在そのものを刈り取る死神。3フェーズの力で時空を歪める。",
    descriptionEn:
      "A reaper that emerges from the void to harvest existence itself. Warps spacetime with three phases of power.",
    difficulty: "BOSS",
    reward: "虚無の鎌を入手",
    rewardEn: "Obtained Void Scythe",
    phases: [
      {
        triggerHpPercent: 75,
        message: "時空が歪む…",
        messageEn: "Spacetime distorts…",
        attackBonus: 1,
      },
      {
        triggerHpPercent: 50,
        message: "次元切断！",
        messageEn: "Dimensional Severance!",
        attackBonus: 3,
      },
      {
        triggerHpPercent: 25,
        message: "存在が消えていく…",
        messageEn: "Existence fades away…",
        attackBonus: 5,
      },
    ],
    specialRule: "フェーズ移行時プレイヤーに3ダメージ",
  },
  /* ── FINAL ×1 ── */
  {
    id: "void-king" as EnemyId,
    name: "虚無の王",
    nameEn: "Void King",
    title: "終焉の支配者",
    titleEn: "Sovereign of Demise",
    maxHp: 100,
    attackPower: 11,
    imageUrl: "/logo.svg",
    description:
      "全ての虚無の根源。宇宙の終わりを体現する存在。必殺能力のみが最終フェーズを突破できる。",
    descriptionEn:
      "The root of all voids. An entity embodying the end of the universe. Only ultimate abilities can break through the final phase.",
    difficulty: "FINAL",
    reward: "虚無の王冠を入手。全クリア達成！",
    rewardEn: "Obtained Void Crown. Full clear achieved!",
    phases: [
      {
        triggerHpPercent: 80,
        message: "宇宙が震える…",
        messageEn: "The universe trembles…",
        attackBonus: 2,
      },
      {
        triggerHpPercent: 55,
        message: "虚無の爆発！",
        messageEn: "Void Explosion!",
        attackBonus: 4,
      },
      {
        triggerHpPercent: 30,
        message: "終焉の意志…！",
        messageEn: "Will of Demise…!",
        attackBonus: 6,
        selfHealPerTurn: 5,
      },
    ],
    specialRule: "HP30%以下から毎ターン5回復。必殺能力のみが最終フェーズを突破できる",
  },
] as const satisfies readonly Enemy[]
