/* ─── Data ─── */
export interface RankingEntry {
  rank: number
  name: string
  title: string
  wealth: string
  wealthNum: number // for sorting/display
  source: string
  affiliation: string
  era: string
  isHistorical: boolean
  wikiId: string
}

export const RANKING_DATA: RankingEntry[] = [
  {
    rank: 1,
    name: "アルゼン・カーリーン",
    title: "グランベル大統領",
    wealth: "150兆n",
    wealthNum: 1500000,
    source: "宇宙最大経済圏・量子経済・次元間技術",
    affiliation: "グランベル / 5大文明圏",
    era: "現在",
    isHistorical: false,
    wikiId: "アルゼン・カーリーン",
  },
  {
    rank: 2,
    name: "ミカエル・ガブリエリ",
    title: "ファールージャ社CEO",
    wealth: "8兆5,000億n",
    wealthNum: 85000,
    source: "次元技術・武器開発",
    affiliation: "ファールージャ社 / V7",
    era: "E515〜現在",
    isHistorical: false,
    wikiId: "ミカエル・ガブリエリ",
  },
  {
    rank: 3,
    name: "アイク・ロペス",
    title: "SSレンジ首脳",
    wealth: "4兆2,000億n",
    wealthNum: 42000,
    source: "国際交易・通信網支配",
    affiliation: "SSレンジ / V7",
    era: "E515〜現在",
    isHistorical: false,
    wikiId: "アイク・ロペス",
  },
  {
    rank: 4,
    name: "グレイモンド・ハウザー",
    title: "ティエリア総帥",
    wealth: "3兆8,000億n",
    wealthNum: 38000,
    source: "軍事技術輸出・防衛ネットワーク",
    affiliation: "ティエリア / 5大文明圏",
    era: "現在",
    isHistorical: false,
    wikiId: "グレイモンド・ハウザー",
  },
  {
    rank: 5,
    name: "レイド・カキザキ",
    title: "アイアン・シンジケート首脳",
    wealth: "2兆8,000億n",
    wealthNum: 28000,
    source: "重工業・軍需生産",
    affiliation: "アイアン・シンジケート / V7",
    era: "E515〜現在",
    isHistorical: false,
    wikiId: "レイド・カキザキ",
  },
  {
    rank: 6,
    name: "ネイサン・コリンド",
    title: "ディオクレニス科学宰相",
    wealth: "2兆5,000億n",
    wealthNum: 25000,
    source: "宇宙探査技術・次元技術研究",
    affiliation: "ディオクレニス / 5大文明圏",
    era: "現在",
    isHistorical: false,
    wikiId: "ネイサン・コリンド",
  },
  {
    rank: 7,
    name: "マドリス・カーネル",
    title: "ファルージャ評議会代表",
    wealth: "2兆1,000億n",
    wealthNum: 21000,
    source: "文化交流・外交・調停",
    affiliation: "ファルージャ / 5大文明圏",
    era: "現在",
    isHistorical: false,
    wikiId: "マドリス・カーネル",
  },
  {
    rank: 8,
    name: "リアナ・ソリス",
    title: "エレシオン女王",
    wealth: "1兆8,000億n",
    wealthNum: 18000,
    source: "医療技術・環境再生技術",
    affiliation: "エレシオン / 5大文明圏",
    era: "現在",
    isHistorical: false,
    wikiId: "リアナ・ソリス",
  },
  {
    rank: 9,
    name: "ティナ/グエ",
    title: "地下街の支配者",
    wealth: "1兆9,500億n",
    wealthNum: 19500,
    source: "地下経済の掌握・情報網",
    affiliation: "地下街",
    era: "E400〜現在",
    isHistorical: false,
    wikiId: "Tina/Gue",
  },
  {
    rank: 10,
    name: "フィオナ",
    title: "ブルーローズ統率者",
    wealth: "1兆4,000億n",
    wealthNum: 14000,
    source: "V7外交・暗躍資金",
    affiliation: "ブルーローズ / V7",
    era: "E490〜現在",
    isHistorical: false,
    wikiId: "フィオナ",
  },
  {
    rank: 11,
    name: "ゼナ",
    title: "Eros-7女性商人",
    wealth: "4,500億n",
    wealthNum: 4500,
    source: "貿易ネットワーク・軍資金供給",
    affiliation: "Eros-7 / マトリカル・リフォーム",
    era: "E525〜現在",
    isHistorical: false,
    wikiId: "ゼナ",
  },
  {
    rank: 12,
    name: "カーラ・ヴェルム",
    title: "スクイーズ・アビス建設者",
    wealth: "3,800億n",
    wealthNum: 3800,
    source: "搾取プラズマ弾生産",
    affiliation: "Eros-7",
    era: "E380〜E505",
    isHistorical: false,
    wikiId: "カーラ・ヴェルム",
  },
  {
    rank: 13,
    name: "セリア・ドミニクス",
    title: "セリア黄金期の創設者",
    wealth: "1,800億n",
    wealthNum: 1800,
    source: "nトークン経済の確立・次元エネルギー技術",
    affiliation: "Selinopolis/Dominion（歴史的人物）",
    era: "E335〜E370",
    isHistorical: true,
    wikiId: "セリア・ドミニクス",
  },
  {
    rank: 14,
    name: "エル・フォルハウス",
    title: "革命家「新時代のルーキー」",
    wealth: "1,500億n",
    wealthNum: 1500,
    source: "完全自由経済の確立",
    affiliation: "コーポラタムパブリカ（歴史的人物）",
    era: "E150",
    isHistorical: true,
    wikiId: "エル・フォルハウス",
  },
  {
    rank: 15,
    name: "アルファ・ケイン",
    title: "シャドウ・リベリオンのリーダー",
    wealth: "1,200億n",
    wealthNum: 1200,
    source: "オムニバス・エンジン掌握",
    affiliation: "シャドウ・リベリオン（歴史的人物）",
    era: "E318",
    isHistorical: true,
    wikiId: "アルファ・ケイン",
  },
]
