import type { CivilizationLeader } from "@/types"

export const CIVILIZATION_LEADERS: CivilizationLeader[] = [
  {
    name: "アルゼン・カーリーン",
    title: "グランベル大統領",
    civilization: "グランベル",
    civilizationColor: "text-amber-400",
    wealth: "150兆ドル（国家GDP）",
    source: "宇宙最大経済圏の指導",
    era: "現在",
    wikiId: "アルゼン・カーリーン",
  },
  {
    name: "女王リアナ・ソリス",
    title: "エレシオン女王",
    civilization: "エレシオン",
    civilizationColor: "text-emerald-400",
    wealth: "医療技術・環境再生（非公開）",
    source: "宇宙第2位の医療大国",
    era: "現在",
    wikiId: "女王リアナ・ソリス",
  },
  {
    name: "総帥グレイモンド・ハウザー",
    title: "ティエリア総帥",
    civilization: "ティエリア",
    civilizationColor: "text-rose-400",
    wealth: "軍事技術輸出（非公開）",
    source: "宇宙最強の軍事力",
    era: "現在",
    wikiId: "グレイモンド・ハウザー",
  },
  {
    name: "マドリス・カーネル",
    title: "ファルージャ評議会代表",
    civilization: "ファルージャ",
    civilizationColor: "text-violet-400",
    wealth: "文化外交収入（非公開）",
    source: "宇宙第4位の文化的影響力",
    era: "現在",
    wikiId: "マドリス・カーネル",
  },
  {
    name: "ネイサン・コリンド",
    title: "ディオクレニス科学宰相",
    civilization: "ディオクレニス",
    civilizationColor: "text-cyan-400",
    wealth: "科学技術研究費（非公開）",
    source: "宇宙探査の最前線",
    era: "現在",
    wikiId: "ネイサン・コリンド",
  },
  {
    name: "大司教",
    title: "エレシュ大司教",
    civilization: "エレシュ",
    civilizationColor: "text-purple-400",
    wealth: "宗教的影響力（非公開）",
    source: "宇宙最大の信仰共同体",
    era: "現在",
    wikiId: "大司教",
  },
  {
    name: "商工会議長",
    title: "プロキオ商工会議長",
    civilization: "プロキオ",
    civilizationColor: "text-orange-400",
    wealth: "全宇宙貿易取引（非公開）",
    source: "宇宙全貿易ルートの掌握",
    era: "現在",
    wikiId: "商工会議長",
  },
  {
    name: "通信長官",
    title: "ロースター通信長官",
    civilization: "ロースター",
    civilizationColor: "text-pink-400",
    wealth: "通信インフラ収入（非公開）",
    source: "全宇宙通信インフラの管理",
    era: "現在",
    wikiId: "通信長官",
  },
]
