#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# Performance Baseline Capture Script
# Phase 2.5 — Unified performance measurement
# Usage: ./scripts/capture-baseline.sh
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPORT_DIR="$PROJECT_ROOT/performance-reports"
TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
REPORT="$REPORT_DIR/baseline-${TIMESTAMP}.md"

mkdir -p "$REPORT_DIR"

echo "📊 Capturing performance baseline..."

# ── 1. Bundle Size ───────────────────────────────────────────
echo "  📦 Measuring bundle size..."
BUNDLE_JSON=$(cd "$PROJECT_ROOT" && bash scripts/measure-bundle-size.sh --json 2>/dev/null || echo '{}')
JS_TOTAL=$(echo "$BUNDLE_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin).get('js_chunks',{}).get('total_bytes',0))" 2>/dev/null || echo "N/A")
WASM_SIZE=$(echo "$BUNDLE_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin).get('wasm',{}).get('binary_bytes',0))" 2>/dev/null || echo "N/A")
WASM_GZ=$(echo "$BUNDLE_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin).get('wasm',{}).get('binary_gzipped_bytes',0))" 2>/dev/null || echo "N/A")

# ── 2. Test Suite ───────────────────────────────────────────
echo "  🧪 Running test suite..."
TEST_OUTPUT=$(cd "$PROJECT_ROOT" && npx vitest run 2>&1 | tail -5)
TEST_COUNT=$(echo "$TEST_OUTPUT" | grep -oP '\d+(?= tests)' | head -1 || echo "N/A")
TEST_PASS=$(echo "$TEST_OUTPUT" | grep -oP '\d+(?= passed)' | head -1 || echo "N/A")
TEST_FAIL=$(echo "$TEST_OUTPUT" | grep -oP '\d+(?= failed)' | head -1 || echo "0")
TEST_TIME=$(echo "$TEST_OUTPUT" | grep -oP '[\d.]+(?=s \(transform)' | head -1 || echo "N/A")

# ── 3. Coverage ─────────────────────────────────────────────
echo "  📈 Measuring coverage..."
COVERAGE_OUTPUT=$(cd "$PROJECT_ROOT" && npx vitest run --coverage 2>&1 | grep "All files" || echo "")
STMTS_COV=$(echo "$COVERAGE_OUTPUT" | awk '{print $2}' | head -1 || echo "N/A")
BRANCH_COV=$(echo "$COVERAGE_OUTPUT" | awk '{print $3}' | head -1 || echo "N/A")
FUNCS_COV=$(echo "$COVERAGE_OUTPUT" | awk '{print $4}' | head -1 || echo "N/A")
LINES_COV=$(echo "$COVERAGE_OUTPUT" | awk '{print $5}' | head -1 || echo "N/A")

# ── 4. Build Time ───────────────────────────────────────────
echo "  🔨 Measuring build time..."
BUILD_START=$(date +%s%N)
cd "$PROJECT_ROOT" && ANALYZE=false bun run build > /dev/null 2>&1
BUILD_END=$(date +%s%N)
BUILD_TIME_MS=$(( (BUILD_END - BUILD_START) / 1000000 ))

# ── 5. Environment ──────────────────────────────────────────
NODE_VERSION=$(node --version 2>/dev/null || echo "N/A")
BUN_VERSION=$(bun --version 2>/dev/null || echo "N/A")
RUST_VERSION=$(rustc --version 2>/dev/null || echo "N/A")

# ── Write Report ────────────────────────────────────────────
cat > "$REPORT" <<EOF
# Performance Baseline — $TIMESTAMP

## Environment
| Component | Version |
|-----------|---------|
| Node.js | $NODE_VERSION |
| Bun | $BUN_VERSION |
| Rust | $RUST_VERSION |

## Bundle Size
| Metric | Value |
|--------|-------|
| JS Chunks Total | ${JS_TOTAL} bytes |
| WASM Binary | ${WASM_SIZE} bytes |
| WASM Gzipped | ${WASM_GZ} bytes |

## Test Suite
| Metric | Value |
|--------|-------|
| Total Tests | $TEST_COUNT |
| Passed | $TEST_PASS |
| Failed | $TEST_FAIL |
| Duration | ${TEST_TIME}s |

## Coverage
| Metric | Value |
|--------|-------|
| Statements | $STMTS_COV |
| Branches | $BRANCH_COV |
| Functions | $FUNCS_COV |
| Lines | $LINES_COV |

## Build
| Metric | Value |
|--------|-------|
| Build Time | ${BUILD_TIME_MS}ms |

---
Generated by scripts/capture-baseline.sh
EOF

echo ""
echo "✅ Baseline saved: $REPORT"
echo ""
cat "$REPORT"
