import type { CardId, GameCard } from "@/types"
import { EffectType } from "@/types"

/* ═══════════════════════════════════════════════════════
   64枚のキャラクターカードプール
   Wiki全キャラクターを1枚ずつのカードとして収録
   ═══════════════════════════════════════════════════════ */
const I = (n: string) => `https://raw.githubusercontent.com/gentaron/image/main/${n}`

export const ALL_CARDS = [
  /* ════════════════════════════════════════
     SR ×14 — 伝説級キャラクター
     ════════════════════════════════════════ */
  {
    id: "char-diana" as CardId,
    name: "ディアナ",
    nameEn: "Diana",
    imageUrl: I("Diana.png"),
    flavorText: "「初代Wonder Woman。光の裁きが悪を断つ。」",
    flavorTextEn: '"The first Wonder Woman. Her light of judgment severs evil."',
    rarity: "SR",
    affiliation: "Gigapolis西大陸",
    affiliationEn: "Gigapolis Western Continent",
    attack: 7,
    defense: 4,
    effect: "シールド+5",
    effectEn: "Shield+5",
    effectType: EffectType.SHIELD,
    effectValue: 5,
    ultimate: 16,
    ultimateName: "光の裁き",
    ultimateNameEn: "Light of Judgment",
  },
  {
    id: "char-jen" as CardId,
    name: "ジェン",
    nameEn: "Jen",
    imageUrl: I("Jen.png"),
    flavorText: "「Lv938+。Valoriaの覇者が放つ絶対的一撃。」",
    flavorTextEn: '"Lv938+. The absolute strike of the Valoria hegemon."',
    rarity: "SR",
    affiliation: "Valoria連合圏",
    affiliationEn: "Valoria Alliance",
    attack: 8,
    defense: 3,
    effect: "敵に5ダメージ＋HPを2回復",
    effectEn: "Deal 5 damage to enemy + Heal 2 HP",
    effectType: EffectType.DAMAGE_HEAL,
    effectValue: 5,
    ultimate: 18,
    ultimateName: "覇王の絶対一撃",
    ultimateNameEn: "Hegemon's Absolute Strike",
  },
  {
    id: "char-celia" as CardId,
    name: "セリア・ドミニクス",
    nameEn: "Celia Dominix",
    imageUrl: I("CeliaDminix.png"),
    flavorText: "「黄金期の女王。一撃に全ての栄光を込めて。」",
    flavorTextEn: '"Queen of the Golden Age. All glory embedded in a single strike."',
    rarity: "SR",
    affiliation: "Selinopolis",
    affiliationEn: "Selinopolis",
    attack: 7,
    defense: 5,
    effect: "HPを5回復",
    effectEn: "Heal 5 HP",
    effectType: EffectType.HEAL,
    effectValue: 5,
    ultimate: 17,
    ultimateName: "黄金の皇劍",
    ultimateNameEn: "Golden Imperial Blade",
  },
  {
    id: "char-alpha-kane" as CardId,
    name: "アルファ・ケイン",
    nameEn: "Alpha Kane",
    imageUrl: I("AlphaKane.png"),
    flavorText: "「シャドウ・リベリオンの魂。量子ハックで世界を変えた。」",
    flavorTextEn: '"Soul of the Shadow Rebellion. Changed the world through quantum hacking."',
    rarity: "SR",
    affiliation: "シャドウ・リベリオン",
    affiliationEn: "Shadow Rebellion",
    attack: 8,
    defense: 3,
    effect: "敵の攻撃力低下",
    effectEn: "Reduce enemy attack power",
    effectType: EffectType.ATTACK_REDUCTION,
    effectValue: 3,
    ultimate: 17,
    ultimateName: "量子ハック・カオス",
    ultimateNameEn: "Quantum Hack Chaos",
  },
  {
    id: "char-layla" as CardId,
    name: "レイラ・ヴィレル・ノヴァ",
    nameEn: "Layla Virel Nova",
    imageUrl: "https://raw.githubusercontent.com/gentaron/image/main/LaylaVirellNova.png",
    flavorText: "「Pink Voltageの最終演舞。プラズマが全てを焼き尽くす。」",
    flavorTextEn: '"Pink Voltage\'s final dance. Plasma incinerates everything."',
    rarity: "SR",
    affiliation: "AURALIS第二世代",
    affiliationEn: "AURALIS 2nd Generation",
    attack: 9,
    defense: 3,
    effect: "敵に6ダメージ",
    effectEn: "Deal 6 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 6,
    ultimate: 18,
    ultimateName: "プラズマ・フィナーレ",
    ultimateNameEn: "Plasma Finale",
  },
  {
    id: "char-kate-claudia" as CardId,
    name: "ケイト・クラウディア",
    nameEn: "Kate Claudia",
    imageUrl: I("KateClaudia.png"),
    flavorText: "「AURALIS創設者。共鳴の極致が敵を滅ぼす。」",
    flavorTextEn: '"AURALIS founder. The pinnacle of resonance annihilates enemies."',
    rarity: "SR",
    affiliation: "AURALIS第一世代",
    affiliationEn: "AURALIS 1st Generation",
    attack: 6,
    defense: 5,
    effect: "HPを5回復＋シールド+3",
    effectEn: "Heal 5 HP + Shield+3",
    effectType: EffectType.HEAL_SHIELD,
    effectValue: 5,
    ultimate: 15,
    ultimateName: "共鳴の極致",
    ultimateNameEn: "Pinnacle of Resonance",
  },
  {
    id: "char-lily-steiner" as CardId,
    name: "リリー・スタイナー",
    nameEn: "Lily Steiner",
    imageUrl: I("LillieSteiner.png"),
    flavorText: "「最終章の歌。旋律が刃となり敵を貫く。」",
    flavorTextEn: '"Song of the final chapter. Melody becomes a blade that pierces enemies."',
    rarity: "SR",
    affiliation: "AURALIS第一世代",
    affiliationEn: "AURALIS 1st Generation",
    attack: 6,
    defense: 5,
    effect: "HPを4回復",
    effectEn: "Heal 4 HP",
    effectType: EffectType.HEAL,
    effectValue: 4,
    ultimate: 15,
    ultimateName: "終章の鎮魂歌",
    ultimateNameEn: "Requiem of the Final Chapter",
  },
  {
    id: "char-mina" as CardId,
    name: "ミナ・エウレカ・エルンスト",
    nameEn: "Mina Eureka Ernst",
    imageUrl: I("MinaEurekaErnst.png"),
    flavorText: "「超次元弾発射。次元を超えた一撃が標的を消滅させる。」",
    flavorTextEn:
      '"Hyperdimensional shell fired. A strike beyond dimensions obliterates the target."',
    rarity: "SR",
    affiliation: "AURALIS第二世代",
    affiliationEn: "AURALIS 2nd Generation",
    attack: 8,
    defense: 3,
    effect: "次元階梯パンディクト展開",
    effectEn: "Deploy Dimensional Stairway Pandict",
    effectType: EffectType.SPECIAL_PANDICT,
    effectValue: 5,
    ultimate: 18,
    ultimateName: "超次元弾",
    ultimateNameEn: "Hyperdimensional Shell",
  },
  {
    id: "char-iris" as CardId,
    name: "アイリス",
    nameEn: "Iris",
    imageUrl: I("Iris.png"),
    flavorText: "「トリニティの指導者。次元の刃で運命を断ち切る。」",
    flavorTextEn: '"Leader of Trinity. Severs destiny with a blade of dimensions."',
    rarity: "SR",
    affiliation: "トリニティ・アライアンス",
    affiliationEn: "Trinity Alliance",
    attack: 7,
    defense: 4,
    effect: "敵に5ダメージ＋シールド+3",
    effectEn: "Deal 5 damage to enemy + Shield+3",
    effectType: EffectType.DAMAGE_SHIELD,
    effectValue: 5,
    ultimate: 17,
    ultimateName: "次元斬り",
    ultimateNameEn: "Dimension Slash",
  },
  {
    id: "char-sylvia-crow" as CardId,
    name: "シルヴィア・クロウ",
    nameEn: "Sylvia Crow",
    imageUrl: I("SylviaCrow.png"),
    flavorText: "「Eros-7のエスパー。念動力の嵐が敵を圧倒する。」",
    flavorTextEn: '"Esper of Eros-7. A storm of psychokinesis overwhelms enemies."',
    rarity: "SR",
    affiliation: "Eros-7",
    affiliationEn: "Eros-7",
    attack: 7,
    defense: 4,
    effect: "敵に5ダメージ",
    effectEn: "Deal 5 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 5,
    ultimate: 16,
    ultimateName: "念動嵐撃",
    ultimateNameEn: "Psychokinetic Storm Strike",
  },
  {
    id: "char-ayaka-rin" as CardId,
    name: "アヤカ・リン",
    nameEn: "Ayaka Rin",
    imageUrl: I("AyakaRin.png"),
    flavorText: "「Lv.842搾精ハンター。カウパー波が全てを狩る。」",
    flavorTextEn: '"Lv.842 Extraction Hunter. Couper waves hunt everything."',
    rarity: "SR",
    affiliation: "Eros-7",
    affiliationEn: "Eros-7",
    attack: 8,
    defense: 3,
    effect: "敵の攻撃力低下",
    effectEn: "Reduce enemy attack power",
    effectType: EffectType.ATTACK_REDUCTION,
    effectValue: 3,
    ultimate: 17,
    ultimateName: "カウパー波・インフィニティ",
    ultimateNameEn: "Couper Wave Infinity",
  },
  {
    id: "char-fariel" as CardId,
    name: "ファリエル",
    nameEn: "Fariel",
    imageUrl: I("Fariel.png"),
    flavorText: "「ボグダス最強の戦力。旋風の一撃が山を断つ。」",
    flavorTextEn: '"Bogdas\'s strongest warrior. A whirlwind strike that severs mountains."',
    rarity: "SR",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 7,
    defense: 5,
    effect: "シールド+5",
    effectEn: "Shield+5",
    effectType: EffectType.SHIELD,
    effectValue: 5,
    ultimate: 16,
    ultimateName: "旋風断山撃",
    ultimateNameEn: "Whirlwind Mountain-Severing Strike",
  },
  {
    id: "char-ninigis" as CardId,
    name: "ニニギス・カラス",
    nameEn: "Ninigis Karas",
    imageUrl: I("NinigisKaras.png"),
    flavorText: "「ボグダスの切り札。カラスの如き速さで標的を屠る。」",
    flavorTextEn: '"Bogdas\'s trump card. Slaughters targets with crow-like speed."',
    rarity: "SR",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 8,
    defense: 3,
    effect: "敵に5ダメージ",
    effectEn: "Deal 5 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 5,
    ultimate: 16,
    ultimateName: "鴉魔一閃",
    ultimateNameEn: "Crow Demon Flash",
  },
  {
    id: "char-slime-woman" as CardId,
    name: "スライム・ウーマン",
    nameEn: "Slime Woman",
    imageUrl: I("SlimeWoman.png"),
    flavorText: "「高次元からの干渉。スライムの波が全てを飲み込む。」",
    flavorTextEn: '"Interference from a higher dimension. A slime wave swallows everything."',
    rarity: "SR",
    affiliation: "高次元存在",
    affiliationEn: "Higher-Dimensional Entity",
    attack: 6,
    defense: 6,
    effect: "敵に4ダメージ＋HPを4回復",
    effectEn: "Deal 4 damage to enemy + Heal 4 HP",
    effectType: EffectType.DAMAGE_HEAL,
    effectValue: 4,
    ultimate: 15,
    ultimateName: "高次元スライム・ウェーブ",
    ultimateNameEn: "Higher-Dimensional Slime Wave",
  },

  /* ════════════════════════════════════════
     R ×32 — 中堅キャラクター
     ════════════════════════════════════════ */
  {
    id: "char-erios-wald" as CardId,
    name: "エリオス・ウォルド",
    nameEn: "Erios Wald",
    imageUrl: I("EriosWald.png"),
    flavorText: "「テリアン反乱軍の旗手。自由のための剣。」",
    flavorTextEn: '"Standard-bearer of the Terian Rebel Army. A sword for freedom."',
    rarity: "R",
    affiliation: "テリアン反乱軍",
    affiliationEn: "Terian Rebel Army",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ",
    effectEn: "Deal 3 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "自由の反乱剣",
    ultimateNameEn: "Sword of Freedom's Rebellion",
  },
  {
    id: "char-gentaro" as CardId,
    name: "弦太郎",
    nameEn: "Gentaro",
    imageUrl: I("Gentaro.png"),
    flavorText: "「Lv569。AURALISを支える不屈の戦士。」",
    flavorTextEn: '"Lv569. The indomitable warrior who supports AURALIS."',
    rarity: "R",
    affiliation: "AURALIS関連",
    affiliationEn: "AURALIS Affiliated",
    attack: 5,
    defense: 3,
    effect: "シールド+3",
    effectEn: "Shield+3",
    effectType: EffectType.SHIELD,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "不屈の居合斬り",
    ultimateNameEn: "Indomitable Iai Slash",
  },
  {
    id: "char-sebastian" as CardId,
    name: "セバスチャン・ヴァレリウス",
    nameEn: "Sebastian Valerius",
    imageUrl: I("SebastianValerius.png"),
    flavorText: "「ボグダス・ジャベリンの指揮官。正確無比な一射。」",
    flavorTextEn: '"Commander of Bogdas Javelin. An unrivaled precision shot."',
    rarity: "R",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ",
    effectEn: "Deal 3 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 3,
    ultimate: 11,
    ultimateName: "精密狙撃弾",
    ultimateNameEn: "Precision Sniper Round",
  },
  {
    id: "char-gareth" as CardId,
    name: "ガレス",
    nameEn: "Gareth",
    imageUrl: I("Gareth.png"),
    flavorText: "「ボグダスの猛将。正面突破を信条とする。」",
    flavorTextEn: '"Fierce general of Bogdas. Believes in frontal assault."',
    rarity: "R",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 5,
    defense: 3,
    effect: "シールド+3",
    effectEn: "Shield+3",
    effectType: EffectType.SHIELD,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "正面突破・粉砕",
    ultimateNameEn: "Frontal Assault: Crush",
  },
  {
    id: "char-leon" as CardId,
    name: "レオン",
    nameEn: "Leon",
    imageUrl: I("Leon.png"),
    flavorText: "「シルバー・ヴェノム幹部。冷酷な一撃。」",
    flavorTextEn: '"Executive of Silver Venom. A cold-hearted strike."',
    rarity: "R",
    affiliation: "シルバー・ヴェノム",
    affiliationEn: "Silver Venom",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ＋HPを2回復",
    effectEn: "Deal 3 damage to enemy + Heal 2 HP",
    effectType: EffectType.DAMAGE_HEAL,
    effectValue: 3,
    ultimate: 11,
    ultimateName: "毒牙の冷刃",
    ultimateNameEn: "Cold Blade of Venom Fangs",
  },
  {
    id: "char-izumi" as CardId,
    name: "イズミ",
    nameEn: "Izumi",
    imageUrl: I("Izumi.png"),
    flavorText: "「アルファ・ヴェノムのリーダー。両性具有の戦闘力。」",
    flavorTextEn: '"Leader of Alpha Venom. Dual-natured combat prowess."',
    rarity: "R",
    affiliation: "アルファ・ヴェノム",
    affiliationEn: "Alpha Venom",
    attack: 6,
    defense: 2,
    effect: "敵に4ダメージ",
    effectEn: "Deal 4 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 4,
    ultimate: 12,
    ultimateName: "双極のヴェノム・ストライク",
    ultimateNameEn: "Dual-Pole Venom Strike",
  },
  {
    id: "char-goldilocks" as CardId,
    name: "ゴルディロックス",
    nameEn: "Goldilocks",
    imageUrl: I("Goldilocks.png"),
    flavorText: "「アルファ・ヴェノムの破壊担当。」",
    flavorTextEn: '"Destruction specialist of Alpha Venom."',
    rarity: "R",
    affiliation: "アルファ・ヴェノム",
    affiliationEn: "Alpha Venom",
    attack: 6,
    defense: 2,
    effect: "敵に3ダメージ",
    effectEn: "Deal 3 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "暴走破壊衝動",
    ultimateNameEn: "Rampaging Destruction Impulse",
  },
  {
    id: "char-lastman" as CardId,
    name: "ラストマン",
    nameEn: "Lastman",
    imageUrl: I("Lastman.png"),
    flavorText: "「シルバー・ヴェノム残党。最後の力を振り絞る一撃。」",
    flavorTextEn:
      '"Remnant of Silver Venom. A strike that squeezes out the last ounce of strength."',
    rarity: "R",
    affiliation: "シルバー・ヴェノム残党",
    affiliationEn: "Silver Venom Remnants",
    attack: 6,
    defense: 2,
    effect: "HPを3回復",
    effectEn: "Heal 3 HP",
    effectType: EffectType.HEAL,
    effectValue: 3,
    ultimate: 11,
    ultimateName: "ラスト・リベンジャー",
    ultimateNameEn: "Last Avenger",
  },
  {
    id: "char-temirtaron" as CardId,
    name: "テミルタロン",
    nameEn: "Temirtaron",
    imageUrl: I("Temirtaron.png"),
    flavorText: "「サイケデリック・コスモロジーの具現化。」",
    flavorTextEn: '"Incarnation of psychedelic cosmology."',
    rarity: "R",
    affiliation: "テンプル・オブ・ホライゾン",
    affiliationEn: "Temple of Horizon",
    attack: 5,
    defense: 3,
    effect: "敵の攻撃力低下",
    effectEn: "Reduce enemy attack power",
    effectType: EffectType.ATTACK_REDUCTION,
    effectValue: 2,
    ultimate: 10,
    ultimateName: "幻覚波動・コスモロジー",
    ultimateNameEn: "Hallucinatory Wave Cosmology",
  },
  {
    id: "char-lilith-vane" as CardId,
    name: "リリス・ヴェイン",
    nameEn: "Lilith Vane",
    imageUrl: I("LilithVane.png"),
    flavorText: "「Eros-7の女性リーダー。搾取技術の制圧者。」",
    flavorTextEn: '"Female leader of Eros-7. Dominator of extraction technology."',
    rarity: "R",
    affiliation: "Eros-7",
    affiliationEn: "Eros-7",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ＋シールド+2",
    effectEn: "Deal 3 damage to enemy + Shield+2",
    effectType: EffectType.DAMAGE_SHIELD,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "搾取の支配者・インペリアル",
    ultimateNameEn: "Dominator of Extraction: Imperial",
  },
  {
    id: "char-garo" as CardId,
    name: "ガロ",
    nameEn: "Garo",
    imageUrl: I("Garo.png"),
    flavorText: "「シャドウ・ユニオンの男性リーダー。反逆の剣。」",
    flavorTextEn: '"Male leader of Shadow Union. Sword of rebellion."',
    rarity: "R",
    affiliation: "シャドウ・ユニオン",
    affiliationEn: "Shadow Union",
    attack: 6,
    defense: 2,
    effect: "敵に3ダメージ",
    effectEn: "Deal 3 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 3,
    ultimate: 11,
    ultimateName: "反逆者の漆黒剣",
    ultimateNameEn: "Rebel's Jet-Black Sword",
  },
  {
    id: "char-karla-velm" as CardId,
    name: "カーラ・ヴェルム",
    nameEn: "Karla Velm",
    imageUrl: I("KarlaVelm.png"),
    flavorText: "「スクイーズ・アビスの建設者。搾取プラズマ弾。」",
    flavorTextEn: '"Builder of the Squeeze Abyss. Extraction plasma shell."',
    rarity: "R",
    affiliation: "Eros-7",
    affiliationEn: "Eros-7",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ",
    effectEn: "Deal 3 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "搾取プラズマカノン",
    ultimateNameEn: "Extraction Plasma Cannon",
  },
  {
    id: "char-aria-sol" as CardId,
    name: "アリア・ソル",
    nameEn: "Aria Sol",
    imageUrl: I("AriaSol.png"),
    flavorText: "「惑星連邦構想の推進者。次元の光で敵を射抜く。」",
    flavorTextEn:
      '"Champion of the Planetary Federation Initiative. Pierces enemies with dimensional light."',
    rarity: "R",
    affiliation: "惑星連邦構想派",
    affiliationEn: "Planetary Federation Faction",
    attack: 5,
    defense: 3,
    effect: "HPを3回復",
    effectEn: "Heal 3 HP",
    effectType: EffectType.HEAL,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "次元光線・フェデレーション",
    ultimateNameEn: "Dimensional Beam: Federation",
  },
  {
    id: "char-tina-gue" as CardId,
    name: "ティナ/グエ",
    nameEn: "Tina/Gue",
    imageUrl: I("TinaGue.png"),
    flavorText: "「地下街の支配者。深い闇が仲間を守る。」",
    flavorTextEn: '"Ruler of the Underground. Deep darkness protects allies."',
    rarity: "R",
    affiliation: "地下街",
    affiliationEn: "Underground City",
    attack: 4,
    defense: 4,
    effect: "シールド+4",
    effectEn: "Shield+4",
    effectType: EffectType.SHIELD,
    effectValue: 4,
    ultimate: 9,
    ultimateName: "地下街の深淵結界",
    ultimateNameEn: "Abyssal Barrier of the Underground",
  },
  {
    id: "char-kate-patton" as CardId,
    name: "ケイト・パットン",
    nameEn: "Kate Patton",
    imageUrl: I("KatePatton.png"),
    flavorText: "「AURALIS第二世代。癒やしの共鳴で隊を守る。」",
    flavorTextEn: '"AURALIS 2nd Generation. Protects the squad with healing resonance."',
    rarity: "R",
    affiliation: "AURALIS第二世代",
    affiliationEn: "AURALIS 2nd Generation",
    attack: 4,
    defense: 4,
    effect: "HPを4回復",
    effectEn: "Heal 4 HP",
    effectType: EffectType.HEAL,
    effectValue: 4,
    ultimate: 9,
    ultimateName: "共鳴の癒やし・リジェネ",
    ultimateNameEn: "Resonance Healing: Regene",
  },
  {
    id: "char-castina" as CardId,
    name: "カスチーナ・テンペスト",
    nameEn: "Castina Tempest",
    imageUrl: I("CastinaTempest.png"),
    flavorText: "「クロセヴィアの守護者。嵐の如き防壁。」",
    flavorTextEn: '"Guardian of Crosevia. A storm-like bulwark."',
    rarity: "R",
    affiliation: "クロセヴィア",
    affiliationEn: "Crosevia",
    attack: 4,
    defense: 5,
    effect: "シールド+4",
    effectEn: "Shield+4",
    effectType: EffectType.SHIELD,
    effectValue: 4,
    ultimate: 9,
    ultimateName: "嵐の絶対防壁",
    ultimateNameEn: "Absolute Storm Bulwark",
  },
  {
    id: "char-elena" as CardId,
    name: "エレナ",
    nameEn: "Elena",
    imageUrl: I("Elena.png"),
    flavorText: "「ヴァーミリオン元機関長。経験に裏打ちされた結界。」",
    flavorTextEn: '"Former chief of Vermillion Intelligence. A barrier backed by experience."',
    rarity: "R",
    affiliation: "ヴァーミリオン諜報機関",
    affiliationEn: "Vermillion Intelligence Agency",
    attack: 4,
    defense: 5,
    effect: "シールド+4",
    effectEn: "Shield+4",
    effectType: EffectType.SHIELD,
    effectValue: 4,
    ultimate: 9,
    ultimateName: "経験の鉄壁結界",
    ultimateNameEn: "Ironclad Barrier of Experience",
  },
  {
    id: "char-aina" as CardId,
    name: "アイナ・フォン・リースフェルト",
    nameEn: "Aina von Riesfeld",
    imageUrl: I("AinaVonRiesfeld.png"),
    flavorText: "「ボグダス歴戦の防衛兵。堅牢な盾。」",
    flavorTextEn: '"Battle-hardened defender of Bogdas. A stalwart shield."',
    rarity: "R",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 3,
    defense: 5,
    effect: "シールド+4",
    effectEn: "Shield+4",
    effectType: EffectType.SHIELD,
    effectValue: 4,
    ultimate: 8,
    ultimateName: "リースフェルト大盾陣",
    ultimateNameEn: "Riesfeld Greatshield Formation",
  },
  {
    id: "char-casteria" as CardId,
    name: "カステリア・グレンヴェルト",
    nameEn: "Casteria Grenvelt",
    imageUrl: I("CasteriaGrenvelt.png"),
    flavorText: "「Gigapolis西大陸の防衛者。」",
    flavorTextEn: '"Defender of the Gigapolis Western Continent."',
    rarity: "R",
    affiliation: "Gigapolis西大陸",
    affiliationEn: "Gigapolis Western Continent",
    attack: 4,
    defense: 4,
    effect: "HPを3回復＋シールド+2",
    effectEn: "Heal 3 HP + Shield+2",
    effectType: EffectType.HEAL_SHIELD,
    effectValue: 3,
    ultimate: 9,
    ultimateName: "西大陸防衛陣",
    ultimateNameEn: "Western Continent Defense Formation",
  },
  {
    id: "char-timur-shah" as CardId,
    name: "ティムール・シャー",
    nameEn: "Timur Shah",
    imageUrl: I("TimurShah.png"),
    flavorText: "「移民団のリーダー。10次元理論の防壁。」",
    flavorTextEn: '"Leader of the Immigrant Fleet. A bulwark of 10th-dimensional theory."',
    rarity: "R",
    affiliation: "移民団",
    affiliationEn: "Immigrant Fleet",
    attack: 4,
    defense: 4,
    effect: "敵の攻撃力低下",
    effectEn: "Reduce enemy attack power",
    effectType: EffectType.ATTACK_REDUCTION,
    effectValue: 2,
    ultimate: 9,
    ultimateName: "10次元理論の防壁",
    ultimateNameEn: "Bulwark of 10th-Dimensional Theory",
  },
  {
    id: "char-zena" as CardId,
    name: "ゼナ",
    nameEn: "Zena",
    imageUrl: I("Zena.png"),
    flavorText: "「Eros-7の女性商人。商売の利益で軍資金を供給。」",
    flavorTextEn: '"Female merchant of Eros-7. Supplies war funds through trade profits."',
    rarity: "R",
    affiliation: "Eros-7",
    affiliationEn: "Eros-7",
    attack: 4,
    defense: 4,
    effect: "HPを3回復",
    effectEn: "Heal 3 HP",
    effectType: EffectType.HEAL,
    effectValue: 3,
    ultimate: 9,
    ultimateName: "利潤の補給戦略",
    ultimateNameEn: "Profit Supply Strategy",
  },
  {
    id: "char-el-forhaus" as CardId,
    name: "エル・フォルハウス",
    nameEn: "El Forhaus",
    imageUrl: I("ElForhaus.png"),
    flavorText: "「新時代のルーキー。経済改革の先駆者。」",
    flavorTextEn: '"Rookie of the new era. Pioneer of economic reform."',
    rarity: "R",
    affiliation: "コーポラタムパブリカ",
    affiliationEn: "Corporatum Publica",
    attack: 4,
    defense: 3,
    effect: "HPを3回復＋シールド+2",
    effectEn: "Heal 3 HP + Shield+2",
    effectType: EffectType.HEAL_SHIELD,
    effectValue: 3,
    ultimate: 9,
    ultimateName: "経済改革ショックウェーブ",
    ultimateNameEn: "Economic Reform Shockwave",
  },
  {
    id: "char-lillie-ardent" as CardId,
    name: "リリー・アーデント",
    nameEn: "Lillie Ardent",
    imageUrl: I("LillieArdent.png"),
    flavorText: "「AURALIS第二世代。献身的な癒やしの手。」",
    flavorTextEn: '"AURALIS 2nd Generation. Devoted healing hands."',
    rarity: "R",
    affiliation: "AURALIS第二世代",
    affiliationEn: "AURALIS 2nd Generation",
    attack: 3,
    defense: 4,
    effect: "HPを4回復",
    effectEn: "Heal 4 HP",
    effectType: EffectType.HEAL,
    effectValue: 4,
    ultimate: 9,
    ultimateName: "献身の聖なる手",
    ultimateNameEn: "Devout Sacred Hands",
  },
  {
    id: "char-ninny" as CardId,
    name: "ニニー・オッフェンバッハ",
    nameEn: "Ninny Offenbach",
    imageUrl: I("NinnyOffenbach.png"),
    flavorText: "「クローン継承のハッカー。計算された一撃。」",
    flavorTextEn: '"Clone-inheritance hacker. A calculated strike."',
    rarity: "R",
    affiliation: "AURALIS第二世代",
    affiliationEn: "AURALIS 2nd Generation",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ＋HPを2回復",
    effectEn: "Deal 3 damage to enemy + Heal 2 HP",
    effectType: EffectType.DAMAGE_HEAL,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "クローン・ハック・オーバーロード",
    ultimateNameEn: "Clone Hack Overload",
  },
  {
    id: "char-fiona" as CardId,
    name: "フィオナ",
    nameEn: "Fiona",
    imageUrl: I("Fiona.png"),
    flavorText: "「ブルーローズのCOO。計算高い策略。」",
    flavorTextEn: '"COO of Blue Rose. A calculating strategy."',
    rarity: "R",
    affiliation: "ブルーローズ",
    affiliationEn: "Blue Rose",
    attack: 4,
    defense: 3,
    effect: "敵に3ダメージ＋シールド+2",
    effectEn: "Deal 3 damage to enemy + Shield+2",
    effectType: EffectType.DAMAGE_SHIELD,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "策略の青薔薇一撃",
    ultimateNameEn: "Strategist's Blue Rose Strike",
  },
  {
    id: "char-marina" as CardId,
    name: "マリーナ・ボビン",
    nameEn: "Marina Bobbin",
    imageUrl: I("MarinaBobbin.png"),
    flavorText: "「ミエルテンガ総統。国を癒やす手。」",
    flavorTextEn: '"President of MielTenga. Hands that heal the nation."',
    rarity: "R",
    affiliation: "ミエルテンガ",
    affiliationEn: "MielTenga",
    attack: 3,
    defense: 4,
    effect: "HPを4回復",
    effectEn: "Heal 4 HP",
    effectType: EffectType.HEAL,
    effectValue: 4,
    ultimate: 9,
    ultimateName: "総統の癒やしの手",
    ultimateNameEn: "President's Healing Hands",
  },
  {
    id: "char-levilia" as CardId,
    name: "レヴィリア・サーペンティナ",
    nameEn: "Levilia Serpentina",
    imageUrl: I("LeviliaSerpentina.png"),
    flavorText: "「シルバー・ヴェノムの毒蛇。見えない毒牙。」",
    flavorTextEn: '"Viper of Silver Venom. Invisible venom fangs."',
    rarity: "R",
    affiliation: "シルバー・ヴェノム",
    affiliationEn: "Silver Venom",
    attack: 5,
    defense: 3,
    effect: "敵に4ダメージ",
    effectEn: "Deal 4 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 4,
    ultimate: 11,
    ultimateName: "毒蛇の幻影牙",
    ultimateNameEn: "Phantom Fangs of the Viper",
  },
  {
    id: "char-willie" as CardId,
    name: "ウィリー",
    nameEn: "Willie",
    imageUrl: I("Willie.png"),
    flavorText: "「アイリスのパートナー。常に側で支える。」",
    flavorTextEn: '"Iris\'s partner. Always by her side, offering support."',
    rarity: "R",
    affiliation: "ヴァーミリオン",
    affiliationEn: "Vermillion",
    attack: 4,
    defense: 4,
    effect: "HPを3回復＋シールド+2",
    effectEn: "Heal 3 HP + Shield+2",
    effectType: EffectType.HEAL_SHIELD,
    effectValue: 3,
    ultimate: 9,
    ultimateName: "絆の共鳴シールド",
    ultimateNameEn: "Bond of Resonance Shield",
  },
  {
    id: "char-white-noise" as CardId,
    name: "ホワイトノイズ",
    nameEn: "White Noise",
    imageUrl: I("WhiteNoise.png"),
    flavorText: "「ボグダスの通信兵。情報の流れが勝利を導く。」",
    flavorTextEn: '"Bogdas communications officer. The flow of information leads to victory."',
    rarity: "R",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 4,
    defense: 3,
    effect: "敵の攻撃力低下",
    effectEn: "Reduce enemy attack power",
    effectType: EffectType.ATTACK_REDUCTION,
    effectValue: 2,
    ultimate: 9,
    ultimateName: "ノイズ・ジャミング・ウェーブ",
    ultimateNameEn: "Noise Jamming Wave",
  },
  {
    id: "char-wadrina" as CardId,
    name: "ワドリナ",
    nameEn: "Wadrina",
    imageUrl: I("Wadrina.png"),
    flavorText: "「ボグダスの後方要員。」",
    flavorTextEn: '"Bogdas rear-support personnel."',
    rarity: "R",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 4,
    defense: 4,
    effect: "シールド+3",
    effectEn: "Shield+3",
    effectType: EffectType.SHIELD,
    effectValue: 3,
    ultimate: 8,
    ultimateName: "後方支援プロトコル",
    ultimateNameEn: "Rear Support Protocol",
  },
  {
    id: "char-azazel" as CardId,
    name: "アザゼル・ヘクトパス",
    nameEn: "Azazel Hectopas",
    imageUrl: I("AzazelHectopus.png"),
    flavorText: "「ヴァーミリオンの異形戦力。触手の一撃。」",
    flavorTextEn: '"Bizarre combat asset of Vermillion. A tentacle strike."',
    rarity: "R",
    affiliation: "ヴァーミリオン",
    affiliationEn: "Vermillion",
    attack: 5,
    defense: 3,
    effect: "敵に4ダメージ",
    effectEn: "Deal 4 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 4,
    ultimate: 11,
    ultimateName: "触手の異形捕縛",
    ultimateNameEn: "Tentacle Bizarre Binding",
  },
  {
    id: "char-jun" as CardId,
    name: "ジュン",
    nameEn: "Jun",
    imageUrl: I("Jun.png"),
    flavorText: "「スライム・ウーマンと関わりを持つ者。不可解な力。」",
    flavorTextEn: '"One connected to the Slime Woman. An incomprehensible power."',
    rarity: "R",
    affiliation: "不詳",
    affiliationEn: "Unknown",
    attack: 4,
    defense: 4,
    effect: "HPを3回復＋敵に2ダメージ",
    effectEn: "Heal 3 HP + Deal 2 damage to enemy",
    effectType: EffectType.HEAL_DAMAGE,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "不可解次元干渉波",
    ultimateNameEn: "Incomprehensible Dimensional Interference Wave",
  },

  /* ── 宇宙文明圏カード ── */
  {
    id: "char-alzen-carlin" as CardId,
    name: "アルゼン・カーリーン",
    nameEn: "Alzen Carlin",
    imageUrl: "/logo.svg",
    flavorText: "「グランベル大統領。宇宙最大の経済帝国を率いる。」",
    flavorTextEn: '"President of Granbel. Leads the largest economic empire in space."',
    rarity: "R",
    affiliation: "グランベル",
    affiliationEn: "Granbel",
    attack: 5,
    defense: 5,
    effect: "HPを4回復",
    effectEn: "Heal 4 HP",
    effectType: EffectType.HEAL,
    effectValue: 4,
    ultimate: 11,
    ultimateName: "経済帝国の絶対支配",
    ultimateNameEn: "Absolute Dominion of the Economic Empire",
  },
  {
    id: "char-greymond-houser" as CardId,
    name: "グレイモンド・ハウザー",
    nameEn: "Greymond Houser",
    imageUrl: "/logo.svg",
    flavorText: "「ティエリア総帥。宇宙最強の軍事力を指揮する。」",
    flavorTextEn: '"Supreme Commander of Tieria. Commands the strongest military force in space."',
    rarity: "R",
    affiliation: "ティエリア",
    affiliationEn: "Tieria",
    attack: 6,
    defense: 3,
    effect: "敵に4ダメージ",
    effectEn: "Deal 4 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 4,
    ultimate: 11,
    ultimateName: "軍事力の絶対防衛",
    ultimateNameEn: "Absolute Military Defense",
  },
  {
    id: "char-liana-solis" as CardId,
    name: "女王リアナ・ソリス",
    nameEn: "Queen Liana Solis",
    imageUrl: "/logo.svg",
    flavorText: "「エレシオン女王。医療と再生の力で宇宙を癒す。」",
    flavorTextEn: '"Queen of Erecion. Heals the universe with medical and regenerative power."',
    rarity: "R",
    affiliation: "エレシオン",
    affiliationEn: "Erecion",
    attack: 4,
    defense: 5,
    effect: "HPを4回復＋シールド+2",
    effectEn: "Heal 4 HP + Shield+2",
    effectType: EffectType.HEAL_SHIELD,
    effectValue: 4,
    ultimate: 10,
    ultimateName: "再生の女王の慈悲",
    ultimateNameEn: "Mercy of the Regeneration Queen",
  },
  {
    id: "char-madris-kernel" as CardId,
    name: "マドリス・カーネル",
    nameEn: "Madris Kernel",
    imageUrl: "/logo.svg",
    flavorText: "「ファルージャ代表。文化の力で争いを鎮める。」",
    flavorTextEn: '"Representative of Faluja. Quells conflict through the power of culture."',
    rarity: "R",
    affiliation: "ファルージャ",
    affiliationEn: "Faluja",
    attack: 3,
    defense: 4,
    effect: "敵の攻撃力低下",
    effectEn: "Reduce enemy attack power",
    effectType: EffectType.ATTACK_REDUCTION,
    effectValue: 2,
    ultimate: 9,
    ultimateName: "文化調停の外交術",
    ultimateNameEn: "Cultural Mediation Diplomacy",
  },
  {
    id: "char-nathan-corind" as CardId,
    name: "ネイサン・コリンド",
    nameEn: "Nathan Corind",
    imageUrl: "/logo.svg",
    flavorText: "「ディオクレニス宰相。科学で宇宙の未来を拓く。」",
    flavorTextEn: '"Chancellor of Dioclenis. Pioneers the future of space through science."',
    rarity: "R",
    affiliation: "ディオクレニス",
    affiliationEn: "Dioclenis",
    attack: 4,
    defense: 4,
    effect: "シールド+4",
    effectEn: "Shield+4",
    effectType: EffectType.SHIELD,
    effectValue: 4,
    ultimate: 10,
    ultimateName: "科学の結晶シールド",
    ultimateNameEn: "Crystal Shield of Science",
  },
  {
    id: "char-ronan-arthur" as CardId,
    name: "ロナン・アーサ",
    nameEn: "Ronan Arthur",
    imageUrl: "/logo.svg",
    flavorText: "「アポロンの騎士王。ケンタウロスレーザーの英雄。」",
    flavorTextEn: '"Knight King of Apollo. Hero of the Centaurus Laser."',
    rarity: "SR",
    affiliation: "アポロン文明圏",
    affiliationEn: "Apollo Civilization Sphere",
    attack: 7,
    defense: 4,
    effect: "敵に5ダメージ",
    effectEn: "Deal 5 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 5,
    ultimate: 17,
    ultimateName: "ケンタウロスレーザー",
    ultimateNameEn: "Centaurus Laser",
  },

  /* ════════════════════════════════════════
     C ×18 — 一般キャラクター
     ════════════════════════════════════════ */
  {
    id: "char-vivietta" as CardId,
    name: "ヴィヴィエッタ",
    nameEn: "Vivietta",
    imageUrl: I("Vivietta.png"),
    flavorText: "「四楓院ヴィヴィエッタ。救出された後も力を尽くす。」",
    flavorTextEn: '"Vivietta Shihouin. Continues to give her all even after being rescued."',
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 3,
    defense: 3,
    effect: "HPを2回復",
    effectEn: "Heal 2 HP",
    effectType: EffectType.HEAL,
    effectValue: 2,
    ultimate: 7,
    ultimateName: "四楓院の慈悲",
    ultimateNameEn: "Mercy of the Shihouin",
  },
  {
    id: "char-sheron" as CardId,
    name: "シェロン・ジェラス",
    nameEn: "Sheron Jeras",
    imageUrl: I("SheronJeras.png"),
    flavorText: "「ボグダスの後方支援兵。」",
    flavorTextEn: '"Bogdas rear-support soldier."',
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 3,
    defense: 2,
    effect: "シールド+2",
    effectEn: "Shield+2",
    effectType: EffectType.SHIELD,
    effectValue: 2,
    ultimate: 6,
    ultimateName: "支援兵の陣太鼓",
    ultimateNameEn: "Support Soldier's War Drum",
  },
  {
    id: "char-ilmise" as CardId,
    name: "イルミーゼ",
    nameEn: "Ilmise",
    imageUrl: I("Ilmise.png"),
    flavorText: "「ボグダスの衛生兵。負傷者を守る。」",
    flavorTextEn: '"Bogdas medic. Protects the wounded."',
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 2,
    defense: 3,
    effect: "HPを3回復",
    effectEn: "Heal 3 HP",
    effectType: EffectType.HEAL,
    effectValue: 3,
    ultimate: 6,
    ultimateName: "衛生兵の救急処置",
    ultimateNameEn: "Medic's First Aid",
  },
  {
    id: "char-piatrino" as CardId,
    name: "ピアトリーノ",
    nameEn: "Piatrino",
    imageUrl: I("Piatrino.png"),
    flavorText: "「ブルーローズの防衛兵。」",
    flavorTextEn: '"Blue Rose defender."',
    rarity: "C",
    affiliation: "ブルーローズ",
    affiliationEn: "Blue Rose",
    attack: 3,
    defense: 3,
    effect: "シールド+3",
    effectEn: "Shield+3",
    effectType: EffectType.SHIELD,
    effectValue: 3,
    ultimate: 7,
    ultimateName: "青薔薇の守護陣",
    ultimateNameEn: "Blue Rose Guardian Formation",
  },
  {
    id: "char-myu" as CardId,
    name: "ミュー",
    nameEn: "Myu",
    imageUrl: I("Myu.png"),
    flavorText: "「Gigapolisの守護存在。」",
    flavorTextEn: '"Guardian entity of Gigapolis."',
    rarity: "C",
    affiliation: "Gigapolis",
    affiliationEn: "Gigapolis",
    attack: 3,
    defense: 3,
    effect: "HPを2回復＋シールド+1",
    effectEn: "Heal 2 HP + Shield+1",
    effectType: EffectType.HEAL_SHIELD,
    effectValue: 2,
    ultimate: 7,
    ultimateName: "守護ミュー・バリア",
    ultimateNameEn: "Guardian Myu Barrier",
  },
  {
    id: "char-gil" as CardId,
    name: "ギル",
    nameEn: "Gil",
    imageUrl: I("Gil.png"),
    flavorText: "「アルファ・ヴェノムの盾役。」",
    flavorTextEn: '"Shield-bearer of Alpha Venom."',
    rarity: "C",
    affiliation: "アルファ・ヴェノム",
    affiliationEn: "Alpha Venom",
    attack: 2,
    defense: 3,
    effect: "シールド+3",
    effectEn: "Shield+3",
    effectType: EffectType.SHIELD,
    effectValue: 3,
    ultimate: 6,
    ultimateName: "ヴェノム・ガード",
    ultimateNameEn: "Venom Guard",
  },
  {
    id: "char-aj" as CardId,
    name: "AJ",
    nameEn: "AJ",
    imageUrl: I("AJ.png"),
    flavorText: "「アルファ・ヴェノムの情報屋。」",
    flavorTextEn: '"Intelligence agent of Alpha Venom."',
    rarity: "C",
    affiliation: "アルファ・ヴェノム",
    affiliationEn: "Alpha Venom",
    attack: 3,
    defense: 2,
    effect: "敵に2ダメージ",
    effectEn: "Deal 2 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 2,
    ultimate: 6,
    ultimateName: "情報ハック・クラック",
    ultimateNameEn: "Info Hack Crack",
  },
  {
    id: "char-sitra" as CardId,
    name: "シトラ・セレス",
    nameEn: "Sitra Celes",
    imageUrl: I("SitraCeles.png"),
    flavorText: "「Gigapolisの謎めいた存在。」",
    flavorTextEn: '"Enigmatic entity of Gigapolis."',
    rarity: "C",
    affiliation: "Gigapolis",
    affiliationEn: "Gigapolis",
    attack: 3,
    defense: 2,
    effect: "敵に2ダメージ",
    effectEn: "Deal 2 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 2,
    ultimate: 7,
    ultimateName: "セレスの神秘光",
    ultimateNameEn: "Mystic Light of Celes",
  },
  {
    id: "char-master-venom" as CardId,
    name: "マスター・ヴェノム",
    nameEn: "Master Venom",
    imageUrl: I("MasterVenom.png"),
    flavorText: "「シルバー・ヴェノムの創設者。毒の知識。」",
    flavorTextEn: '"Founder of Silver Venom. Master of venom lore."',
    rarity: "C",
    affiliation: "シルバー・ヴェノム",
    affiliationEn: "Silver Venom",
    attack: 3,
    defense: 2,
    effect: "敵に3ダメージ",
    effectEn: "Deal 3 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 3,
    ultimate: 7,
    ultimateName: "マスターヴェノム・エキス",
    ultimateNameEn: "Master Venom Extract",
  },
  {
    id: "char-gabby" as CardId,
    name: "フレデリック・ギャビー",
    nameEn: "Frederic Gabby",
    imageUrl: I("FredericGabby.png"),
    flavorText: "「ボグダスの歴戦の兵。着実な一撃。」",
    flavorTextEn: '"Battle-hardened soldier of Bogdas. A steady strike."',
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 3,
    defense: 2,
    effect: "敵に2ダメージ",
    effectEn: "Deal 2 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 2,
    ultimate: 6,
    ultimateName: "歴戦のベテラン斬り",
    ultimateNameEn: "Veteran's Battle Slash",
  },
  {
    id: "char-miyushari" as CardId,
    name: "ミユシャリ",
    nameEn: "Miyushari",
    imageUrl: I("Miyushari.png"),
    flavorText: "「ボグダス・ジャベリンの歩兵部隊。」",
    flavorTextEn: '"Infantry unit of Bogdas Javelin."',
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 3,
    defense: 2,
    effect: "シールド+2",
    effectEn: "Shield+2",
    effectType: EffectType.SHIELD,
    effectValue: 2,
    ultimate: 6,
    ultimateName: "ジャベリン突撃陣形",
    ultimateNameEn: "Javelin Assault Formation",
  },
  {
    id: "char-yeshibato" as CardId,
    name: "イェシバトー",
    nameEn: "Yeshibato",
    imageUrl: I("Yeshibato.png"),
    flavorText: "「ボグダス・ジャベリンの斥候兵。」",
    flavorTextEn: '"Scout of Bogdas Javelin."',
    rarity: "C",
    affiliation: "ボグダス・ジャベリン",
    affiliationEn: "Bogdas Javelin",
    attack: 3,
    defense: 2,
    effect: "敵に2ダメージ",
    effectEn: "Deal 2 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 2,
    ultimate: 6,
    ultimateName: "斥候の隠密射撃",
    ultimateNameEn: "Scout's Covert Shot",
  },
  {
    id: "char-yonik" as CardId,
    name: "ヨニック",
    nameEn: "Yonik",
    imageUrl: I("Yonik.png"),
    flavorText: "「ブルーローズの戦士。堅実な剣術。」",
    flavorTextEn: '"Warrior of Blue Rose. Steady swordsmanship."',
    rarity: "C",
    affiliation: "ブルーローズ",
    affiliationEn: "Blue Rose",
    attack: 3,
    defense: 3,
    effect: "シールド+2",
    effectEn: "Shield+2",
    effectType: EffectType.SHIELD,
    effectValue: 2,
    ultimate: 7,
    ultimateName: "ブルーローズの剣舞",
    ultimateNameEn: "Blue Rose Sword Dance",
  },
  {
    id: "char-bobristy" as CardId,
    name: "ボブリスティ",
    nameEn: "Bobristy",
    imageUrl: I("Bobristy.png"),
    flavorText: "「アルファ・ヴェノムの突撃兵。」",
    flavorTextEn: '"Assault soldier of Alpha Venom."',
    rarity: "C",
    affiliation: "アルファ・ヴェノム",
    affiliationEn: "Alpha Venom",
    attack: 4,
    defense: 1,
    effect: "敵に2ダメージ",
    effectEn: "Deal 2 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 2,
    ultimate: 6,
    ultimateName: "ヴェノム・ラッシュ",
    ultimateNameEn: "Venom Rush",
  },
  {
    id: "char-aike-lopez" as CardId,
    name: "アイク・ロペス",
    nameEn: "Aike Lopez",
    imageUrl: I("AikeLopez.png"),
    flavorText: "「SSレンジ / V7の戦闘要員。」",
    flavorTextEn: '"Combat operative of SS Range / V7."',
    rarity: "C",
    affiliation: "SSレンジ",
    affiliationEn: "SS Range",
    attack: 3,
    defense: 2,
    effect: "敵に2ダメージ",
    effectEn: "Deal 2 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 2,
    ultimate: 7,
    ultimateName: "SSレンジ・アサルト",
    ultimateNameEn: "SS Range Assault",
  },
  {
    id: "char-katarina" as CardId,
    name: "カタリナ",
    nameEn: "Katarina",
    imageUrl: I("Katarina.png"),
    flavorText: "「アルファ・ヴェノムの暗殺者。速い一撃。」",
    flavorTextEn: '"Assassin of Alpha Venom. A lightning-fast strike."',
    rarity: "C",
    affiliation: "アルファ・ヴェノム",
    affiliationEn: "Alpha Venom",
    attack: 4,
    defense: 1,
    effect: "敵に3ダメージ",
    effectEn: "Deal 3 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 3,
    ultimate: 7,
    ultimateName: "暗殺者の疾風ナイフ",
    ultimateNameEn: "Assassin's Gale Knife",
  },
  {
    id: "char-rafael-drake" as CardId,
    name: "ラファエル・ドレイク",
    nameEn: "Rafael Drake",
    imageUrl: "/logo.svg",
    flavorText: "「トロン・コーポレーションCEO。ZAMLTの宇宙軍事力を統括。旗艦カリバーンを指揮。」",
    flavorTextEn:
      '"CEO of Tron Corporation. Commands ZAMLT\'s space military forces. Leads the flagship Caliburn."',
    rarity: "R",
    affiliation: "ZAMLT",
    affiliationEn: "ZAMLT",
    attack: 5,
    defense: 3,
    effect: "敵に3ダメージ",
    effectEn: "Deal 3 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "重工業の鉄槌",
    ultimateNameEn: "Iron Hammer of Heavy Industry",
  },
  {
    id: "char-carlos-vandam" as CardId,
    name: "カルロス・ヴァンダム",
    nameEn: "Carlos Vandam",
    imageUrl: "/logo.svg",
    flavorText: "「マモン・コーポレーションCEO。ZAMLTの経済的基盤を構築。慎重な戦略家。」",
    flavorTextEn:
      '"CEO of Mamon Corporation. Built ZAMLT\'s economic foundation. A prudent strategist."',
    rarity: "R",
    affiliation: "ZAMLT",
    affiliationEn: "ZAMLT",
    attack: 4,
    defense: 4,
    effect: "シールド+3",
    effectEn: "Shield+3",
    effectType: EffectType.SHIELD,
    effectValue: 3,
    ultimate: 9,
    ultimateName: "金融の支配者",
    ultimateNameEn: "Master of Finance",
  },
  {
    id: "char-arthur-grimm" as CardId,
    name: "アーサー・グリム",
    nameEn: "Arthur Grimm",
    imageUrl: "/logo.svg",
    flavorText: "「ゼブラ・コーポレーションCEO。次元技術を独占するZAMLT最危険の企業。」",
    flavorTextEn:
      '"CEO of Zebra Corporation. ZAMLT\'s most dangerous enterprise, monopolizing dimension technology."',
    rarity: "R",
    affiliation: "ZAMLT",
    affiliationEn: "ZAMLT",
    attack: 3,
    defense: 5,
    effect: "敵の攻撃力低下",
    effectEn: "Reduce enemy attack power",
    effectType: EffectType.ATTACK_REDUCTION,
    effectValue: 3,
    ultimate: 9,
    ultimateName: "情報操作の黒幕",
    ultimateNameEn: "Mastermind of Information Manipulation",
  },
  {
    id: "char-elizabeth-lindberg" as CardId,
    name: "エリザベス・リンドバーグ",
    nameEn: "Elizabeth Lindberg",
    imageUrl: "/logo.svg",
    flavorText: "「ルレンツ・コーポレーションCEO。次元の塔とカタリスト・コア建造を主導。」",
    flavorTextEn:
      '"CEO of Lulenz Corporation. Led the construction of the Dimensional Tower and Catalyst Core."',
    rarity: "R",
    affiliation: "ZAMLT",
    affiliationEn: "ZAMLT",
    attack: 4,
    defense: 4,
    effect: "シールド+3",
    effectEn: "Shield+3",
    effectType: EffectType.SHIELD,
    effectValue: 3,
    ultimate: 10,
    ultimateName: "Registryの絶対管理",
    ultimateNameEn: "Absolute Registry Control",
  },
  {
    id: "char-iris-nova" as CardId,
    name: "アイリス・ノヴァ",
    nameEn: "Iris Nova",
    imageUrl: "/logo.svg",
    flavorText: "「アロエオイル・コーポレーションCEO。次元エネルギー兵器開発の専門家。」",
    flavorTextEn: '"CEO of Aloe Oil Corporation. Expert in dimensional energy weapon development."',
    rarity: "R",
    affiliation: "ZAMLT",
    affiliationEn: "ZAMLT",
    attack: 4,
    defense: 3,
    effect: "敵に3ダメージ",
    effectEn: "Deal 3 damage to enemy",
    effectType: EffectType.DAMAGE,
    effectValue: 3,
    ultimate: 9,
    ultimateName: "インフラ掌握の一手",
    ultimateNameEn: "Masterstroke of Infrastructure Control",
  },
  {
    id: "char-elliot-strass" as CardId,
    name: "エリオット・シュトラス",
    nameEn: "Elliot Strass",
    imageUrl: "/logo.svg",
    flavorText: "「ZAMLT総帥。経済支配の絶対権力。」",
    flavorTextEn: '"Supreme Commander of ZAMLT. Absolute power of economic domination."',
    rarity: "R",
    affiliation: "ZAMLT",
    affiliationEn: "ZAMLT",
    attack: 5,
    defense: 4,
    effect: "シールド+4",
    effectEn: "Shield+4",
    effectType: EffectType.SHIELD,
    effectValue: 4,
    ultimate: 11,
    ultimateName: "経済支配の絶対命令",
    ultimateNameEn: "Absolute Decree of Economic Domination",
  },
  {
    id: "char-reid-kakizaki" as CardId,
    name: "レイド・カキザキ",
    nameEn: "Reid Kakizaki",
    imageUrl: I("ReidKakizaki.png"),
    flavorText: "「アイアン・シンジケートの戦士。」",
    flavorTextEn: '"Warrior of the Iron Syndicate."',
    rarity: "C",
    affiliation: "アイアン・シンジケート",
    affiliationEn: "Iron Syndicate",
    attack: 3,
    defense: 2,
    effect: "シールド+2",
    effectEn: "Shield+2",
    effectType: EffectType.SHIELD,
    effectValue: 2,
    ultimate: 6,
    ultimateName: "シンジケート・アイアンパンチ",
    ultimateNameEn: "Syndicate Iron Punch",
  },
  {
    id: "char-mikael-gabrieli" as CardId,
    name: "ミカエル・ガブリエリ",
    nameEn: "Mikael Gabrieli",
    imageUrl: I("MikaelGabrieli.png"),
    flavorText: "「ファールージャ社の警備員。」",
    flavorTextEn: '"Security guard of Faluja Company."',
    rarity: "C",
    affiliation: "ファールージャ社",
    affiliationEn: "Faluja Company",
    attack: 3,
    defense: 3,
    effect: "シールド+2",
    effectEn: "Shield+2",
    effectType: EffectType.SHIELD,
    effectValue: 2,
    ultimate: 6,
    ultimateName: "警備員の警棒スマッシュ",
    ultimateNameEn: "Security Guard's Baton Smash",
  },
] as const satisfies readonly GameCard[]
